### ISSUE TITLE
Εισαγωγή νέου μαθήματος επιλογής «Ελεύθερη Επιλογή» στο B' εξάμηνο

### ISSUE THREAD

**Issue by Rigas-A** [ioniodi/sitegr#102]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη του μαθήματος «Ελεύθερη Επιλογή» στο B' εξάμηνο στο πρόγραμμα των προπτυχιακών σπουδών. Η αλλάγη θα συμβεί στο [courses](https://github.com/ioniodi/sitegr/tree/master/all_collections/_courses)  στο οποίο θα προσθέσω ένα νέο .md αρχείο αντίστοιχα για το μάθημα. Προφανώς  τις πληροφορίες για το μάθημα θα τις αντλήσω από την επίσημη ιστοσελίδα του πανεπιστημίου, το μάθημα που θα προσθέσω βρίσκεται [εδώ](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/643/).
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
έχεις τσεκάρει το κουτάκι αλλά λινκ δεν μας δίνεις!

> Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω

**Comment by Rigas-A** [comment]
> έχεις τσεκάρει το κουτάκι αλλά λινκ δεν μας δίνεις!
> 
> > Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω

Ναι κατάλαβα λάθος :( .  Έκανα edit και προσέθεσα αντίστοιχα links.
