### ISSUE TITLE
Διόρθωση του footer responsiveness

### ISSUE THREAD

**Issue by dimpram** [ioniodi/sitegr#109]
### Δήλωση Θέματος
- Το footer προκαλεί overflow όταν ο χρήστης προβάλει την σελίδα σε mobile view και αυτό ευθύνεται σε πρόβλημα της CSS στο αποθετήριο του θέματος ([minimal-ionio](https://github.com/ioniodi/minimal-ionio)). Η αναμενόμενη συμπεριφορά είναι η κάθε λίστα με links να πηγαίνει αυτό η μια κάτω από την άλλη δηλαδή να στοιχίζονται κάθετα και όχι οριζόντια όπως τώρα.
 
![2021-03-06](https://user-images.githubusercontent.com/44473195/110214735-ab671180-7eae-11eb-9446-ccdde9124072.png)

- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by dimpram** [comment]
[PR](https://github.com/ioniodi/minimal-ionio/pull/39) ready στο minimal-ionio

**Comment by epidrome** [comment]
τελικά είναι λάθος το λογικό (!?) σχόλιο μου https://github.com/ioniodi/minimal-ionio/pull/39

έκλεισε αυτόματα εξ αποστάσεως (!?) ;-)

**Comment by dimpram** [comment]
Παρατήρησα οτι άμα γράψεις `closes #αριθμό` αλλά τον αριθμό τον βάλεις με συντακτικό link έχοντας το link του issue  από άλλο repository δηλαδή `closes [#109](https://github.com/ioniodi/sitegr/issues/109)` από οτι φαίνεται κλείνει όντως το issue που του αντιστοιχεί.
