### ISSUE TITLE
Προσθήκη Ανακοίνωσης: "Αναστολή εισερχόμενης και εξερχόμενης κινητικότητας Εrasmus με φυσική παρουσία στις χώρες υποδοχής -φοιτητών & προσωπικού- εαρινού εξαμήνου ακαδ. έτους 2020-2021 λόγω της πανδημίας COVID-19"

### ISSUE THREAD

**Issue by MariaXristinaPapatheodwrou** [ioniodi/sitegr#110]
### Προσθήκη Ανακοίνωσης 
- Σύντομη περιγραφή των επικείμενων αλλαγών: Ανάρτηση ανακοίνωσης ΄΄Επείγουσα Ανακοίνωση : "Αναστολή εισερχόμενης και εξερχόμενης κινητικότητας Εrasmus με φυσική παρουσία στις χώρες υποδοχής -φοιτητών & προσωπικού- εαρινού εξαμήνου ακαδ. έτους 2020-2021 λόγω της πανδημίας COVID-19"
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Παρακαλώ η ανακοίνωση στον τίτλο.
