### ISSUE TITLE
Προσθήκη Ανακοίνωσης Επιστημονική Τηλε-διημερίδα: «Η μετάβαση της εκπαιδευτικής κοινότητας στην ψηφιακή εποχή και η αξιοποίηση της εξ αποστάσεως εκπαίδευσης: Από τη θεωρία στην πράξη»

### ISSUE THREAD

**Issue by DimitrisTzer** [ioniodi/sitegr#117]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη Ανακοίνωσης Επιστημονική Τηλε-διημερίδα: «Η μετάβαση της εκπαιδευτικής κοινότητας στην ψηφιακή εποχή και η αξιοποίηση της εξ αποστάσεως εκπαίδευσης: Από τη θεωρία στην πράξη»(05-02-2021)
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:Ανακοίνωση

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Παρακαλώ η ανακοίνωση στον τίτλο.
