### ISSUE TITLE
Προσθήκη ανακοίνωσης εκδήλωσης: "Διεθνές Συνέδριο Sunbelt XXVII"

### ISSUE THREAD

**Issue by rawmann** [ioniodi/sitegr#118]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: : Προσθήκη ανακοίνωσης: "Διεθνές Συνέδριο Sunbelt XXVIΙ". [Link ανακοίνωσης](https://di.ionio.gr/gr/news/113/)
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Παρακαλώ η ανακοίνωση στον τίτλο.
