### ISSUE TITLE
Προσθήκη Επισκέπτη Καθηγητή Μουρατίδης Χάρης

### ISSUE THREAD

**Issue by NikosKar23** [ioniodi/sitegr#120]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: προσθήκη προσωπικού επισκέπτη καθηγητή: Χάρης Μουρατίδης και ενημέρωση των πληροφοριών σύμφωνα με https://di.ionio.gr/gr/department/staff/574-mouratidis/
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσής) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Duplicate #120
