### ISSUE TITLE
Προσθήκη καθηγητή ΕΔΙΠ Κατωμέρης Γιώργος

### ISSUE THREAD

**Issue by NikosKar23** [ioniodi/sitegr#122]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: προσθήκη προσωπικού, μέλος ΕΔΙΠ Κατωμέρη Γιώργο σύμφωνα με https://di.ionio.gr/gr/department/staff/575-katomeris/ και http://gram-web.ionio.gr/unistudent/stafflist.asp?mnuid=depart&depID=211&level=2  (email)
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσής) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Duplicate #28 
Έκανες 2 Duplicate requests.

**Comment by NikosKar23** [comment]
ναι κοίταζα τα issues όπως λέει και η 3η υπενθύμιση "Έχω ελέγξει ότι το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό" αλλά τα πρωτότυπα αιτήματα βρισκόντουσαν στα pull request. Αφού παρατήρησα μετά ότι βρισκόντουσαν στα pull request τα άφησα ανοιχτά μήπως και δεν γινόντουσαν δεκτά τα pull request των συναδέλφων μου και άνοιξα το τελικό issue #125 για παν ενδεχόμενο.
