### ISSUE TITLE
Προσθήκη ανακοίνωσης "Συνάντηση του Εργαστηρίου Υπολογιστικής Μοντελοποίησης του Ιονίου Πανεπιστημίου με εκπροσώπους του Δήμου Κεντρικής Κέρκυρας και Διαποντίων Νήσων"

### ISSUE THREAD

**Issue by p15bako** [ioniodi/sitegr#124]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη ανακοίνωσης "Συνάντηση του Εργαστηρίου Υπολογιστικής Μοντελοποίησης του Ιονίου Πανεπιστημίου με εκπροσώπους του Δήμου Κεντρικής Κέρκυρας και Διαποντίων Νήσων"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Παρακαλώ η ανακοίνωση στον τίτλο.

**Comment by p15bako** [comment]
Τώρα είναι εντάξει;
