### ISSUE TITLE
Προσθήκη Ανακοίνωσης ΚΑΤΑΤΑΚΤΗΡΙΕΣ

### ISSUE THREAD

**Issue by NikosKar23** [ioniodi/sitegr#125]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Πρόσθεσα την κατηγορία των κατατακτηρίων στη σελίδα των σπουδών
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by NikosKar23** [comment]
Ναι βεβαίως!
Αρχικά, άντλησα έμπνευση από το #60 (Διδακτορικές σπουδές)  και από το #103  (Πρακτική άσκηση).
Στην επίσημη σελίδα, στην κατηγορία των σπουδών υπάρχουν πληροφορίες και για τις κατατακτήριες εξετάσεις 
link ionio: https://di.ionio.gr/gr/studies/undergraduate-studies/

Αφού έκανα το πρώτο site και πρόσθεσα την κατηγορία των κατατακτήριων στην κορυφή πριν τα μαθήματα, σκέφτηκα ότι θα ήταν καλύτερη μια δεύτερη πρόταση, να τοποθετηθεί στο τέλος των μαθημάτων, πριν τις διδακτορικές σπουδές.

link 1ης πρότασης: https://silly-pasteur-4dd93c.netlify.app/courses/
link 2ης πρότασης: https://katataktiries1.netlify.app/courses/

@epidrome

**Comment by epidrome** [comment]
ωραία, τώρα κατάλαβα!

το γεγονός ότι στο επίσημο το έχουν στις σπουδές δεν πάει να πει ότι είναι και σωστό! ας αντιγράψουμε μόνο τα σωστά

επίσης, από την δουλειά που έκανες καταλαβαίνω ότι οι κατατακτήριες είναι περισσότερο μια ανακοίνωση που βγαίνει μια φορά τον χρόνο με κάποια επισυναπτόμενα

οπότε πρόσθεσα την ετικέτα
https://github.com/ioniodi/sitegr/wiki/Taxonomy

και προτείνω το θέμα εδώ να γίνει ανακοίνωση αντί για επέμβαση στην σελίδα σπουδές

**Comment by NikosKar23** [comment]
Έκανα την αλλαγή που αναφέρατε στο όνομα του θέματος χαρακτηρίζοντας το ως "Ανακοίνωση"

Πρόσθεσα και το αντίστοιχο .md στην περιοχή των ανακοινώσεων:
https://github.com/NikosKar23/sitegr/blob/2018112/all_collections/_posts/2020-2021-Katataktiries.md

Παρόλα αυτά στο site δεν περνάνε οι παραπάνω αλλαγές παρόλο που έκανα 5-6 διαφορετικά site δοκιμάζοντας διάφορες παραλλαγές.
Το link του site μου: https://cranky-wiles-f4bebf.netlify.app/posts/

Σημείωση: Αρχικά για tag είχα - Κατατακτήριες ,αλλά το άλλαξα σε - Conference , μήπως και διορθωθεί επειδή δεν υπάρχει το Κατατακτήριές μέχρι στιγμής αλλά δεν υπήρξε διαφορά.

@epidrome

**Comment by NikosKar23** [comment]
Το πρόβλημα λύθηκε! 
Ύστερα από πάρα πολλές δοκιμές, βρήκα ότι έφταιγε η ονομασία του αρχείου, δεν ήταν στυλ ημερομηνίας και γι' αυτό δεν το εμφάνιζε.

link ιστοσελίδας: https://katataktiries.netlify.app/posts/2020/10/05/katataktiries/
link από το Github: https://github.com/NikosKar23/sitegr/blob/2018112/all_collections/_posts/2020-10-05-katataktiries.md

@epidrome @c15pati @provopoulos
