### ISSUE TITLE
Διόρθωση του typo στο courses.md και στα αντίστοιχα αρχεία στο collection courses

### ISSUE THREAD

**Issue by Rigas-A** [ioniodi/sitegr#133]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Παρατήρησα ότι ενώ στο minimal-ionio οι χαρακτήρες για τον ελέγχο του τύπου μαθήματος στο [table.html](https://github.com/ioniodi/minimal-ionio/blob/master/_includes/table.html) είναι σε λατινικούς χαρακτήρες (όπως θα ‘πρεπε) στο site και συγκεκριμένα στο [courses.md](https://github.com/ioniodi/sitegr/blob/master/_pages/courses.md) ο έλεγχος για το μάθημα επιλογής γίνεται με τον ελληνικό χαρακτήρα “Ο” (ενώ τα υπόλοιπα γίνονται σωστά με τους λατινικούς χαρακτήρες ). Αυτό ως αποτέλεσμα έχει το γεγονός ότι αν στο [collection courses](https://github.com/ioniodi/sitegr/tree/master/all_collections/_courses)  βάλουμε λατινικό χαρακτήρα (που είναι το σωστό) το μάθημα επιλογής δεν εμφανίζεται καθόλου και αν το βάλουμε με ελληνικό χαρακτήρα το μάθημα επιλογής εμφανίζεται αλλά στον πίνακα το πεδίο τύπος μένει κενό. Η αλλαγή που πρέπει να γίνει είναι να αλλάξει απο ελληνικό σε αγγλικό χαρακτηρά το "O" οπού χρειάζεται.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@Rigas-A nice catch!

αναρωτιέμαι μήπως πρέπει να το δούμε συνολικά ώστε να βάλουμε κάποια λέξη καλύτερα αντί για χαρακτήρα, ώστε να αποφύγουμε μελλοντικά μπαγκς

αν θες μπορείς να ανοίξεις ένα νέο ίσιου με την περιγραφή του προβλήματος και να καλέσεις όσους θεωρείς ότι μπορεί να βοηθήσουν;
