### ISSUE TITLE
Ανανέωση μαθημάτων με πολλαπλούς καθηγητές

### ISSUE THREAD

**Issue by chris4dim** [ioniodi/sitegr#14]
### Δήλωση Θέματος: Ανανέωση μαθημάτων με πολλαπλούς καθηγητές

- Σύντομη περιγραφή των επικείμενων αλλαγών:

Μάθημα Κρυπτογραφίας του Γ εξαμήνου, όπου οι διδάσκοντες είναι 3.
Μάθημα Αναπαράσταση Πληροφοριών και Γνώσης του Ζ εξαμήνου, όπου οι διδάσκοντες είναι 2.
Μάθημα Κοινωνικά και Νομικά Θέματα των ΤΠΕ του Ζ εξαμήνου, όπου υπάρχουν 2 διδάσκοντες.
Μάθημα Δίκτυα 2 του Ε εξαμήνου, όπου υπάρχουν 2 διδάσκοντες.

- Εκτιμώμενη δυσκολία: very easy

- Σχετικά θέματα:#131

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
για το 2ο αίτημα ενσωμάτωσης θέλουμε κάτι πιο δύσκολο, όχι απλά επεξεργασία δεδομένων, φυσικά το θέμα αυτό είναι δεκτό, αλλά συμβουλεύω να ασχοληθείς με κάποιο άλλο για να πάρεις τον αντίστοιχο βαθμό

**Comment by chris4dim** [comment]
ok, θα ψάξω και για κάτι πιο δύσκολο!
