### ISSUE TITLE
Προσωπικό: Οργάνωση της σελίδας σε κατηγορίες ανάλογα με την βαθμίδα (ΔΕΠ, ΕΔΙΠ, κτλ)

### ISSUE THREAD

**Issue by andreaspappoutas** [ioniodi/sitegr#15]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών 
-- Ανάλογα με τι αριθμό έχει ένας καθηγητής στο rank του να μπαίνει στη κατάλληλη κατηγορία.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @andreaspappoutas 
- Σχετικά θέματα: [#104](https://github.com/ioniodi/site-gr/issues/104)

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Έφτιαξα ήδη ένα τρόπο όπου αυτόματα ανάλογα με τι αριθμό έχει ο κάθε καθηγητής μπαίνει σε μια κατηγορία. Το πρόβλημα είναι ότι έβαλα το κώδικα στο αρχείο people.html απευθείας αφού δεν μπορούσα να τον αλλάξω στο minimal-ionio. 
Η κάθε βαθμίδα έχει δικό της grid όπου στη πρώτη σειρά είναι ο τίτλος και ακολουθούν οι καθηγητές. Ο κάθε καθηγητής είναι μέσα σε ένα div με id to reference του. Αν κάποια βαθμίδα δεν υπάρχει τότε ο δεν εμφανίζετε καθόλου .

[Αποτέλεσμα με τίτλους 1st rank, 2nd rank ...](https://andreaspappoutas-sitegr.netlify.app/people/)
[Κώδικας](https://github.com/andreaspappoutas/sitegr/blob/master/_pages/people.html)

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
μπράβο! αλλά ο κώδικας θα πρέπει να πάει στο θέμα,

θα πρέπει να υπάρχουν οδηγίες στο γουικι για την τοπική εκτέλεση αλλαγμένου θέματος
