### ISSUE TITLE
Προσθήκη ανακοίνωσης "" Εξέταση μαθημάτων εαρινού εξαμήνου για τους επί πτυχίω φοιτητές που χρωστούν έως 5 (πέντε) μαθήματα, στην εξεταστική Ιανουαρίου/Φεβρουαρίου 2021 ""

### ISSUE THREAD

**Issue by p14ntot** [ioniodi/sitegr#151]
### Δήλωση Θέματος
Θα προσθέσω την ανακοίνωση https://di.ionio.gr/gr/news/19967/ η οποία προστέθηκε στις 11-01-2021 και ώρα 13:20 
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p16pyla** [comment]
Στις υπενθυμίσεις στα [ ] αναμεσά μπορείς να βάλεις το Χ (κεφαλαίο λατινικό χωρίς κενα) για να εμφανίζεται σαν να έχει γίνει ✔
