### ISSUE TITLE
Οργάνωση των custom includes που αφορούν το minimal ionio

### ISSUE THREAD

**Issue by dimpram** [ioniodi/sitegr#152]
### Δήλωση Θέματος
[Από προηγούμενο pull request](https://github.com/ioniodi/minimal-ionio/pull/39#issuecomment-792298542), σε κάποια includes που κάνουν extend το functionality του minimal-mistakes και έχουνε προστεθεί από εμάς, παρατήρησα την εξής δομή:
```
.
├── _includes
│   ├── footer
│   │   ├── custom.html
...
│   ├── analytics-providers
│   │   ├── custom.html
...
│   ├── comments-providers
│   │   ├── custom.html
...
```

Αυτό που προτείνω λοιπόν είναι, για να συμβαδίζει ακόμα περισσότερο η δομή της SCSS που είχα προσθέσει στο αντίστοιχο προηγούμενο PR μου με το `_sass/minimal-ionio.scss`, να προσθέσω μια παρόμοια αρχιτεκτονική και στα includes ώστε να είναι να συμβαδίζουν τα includes με την CSS (δηλαδή να έχουν τους ίδιους κανόνες αρχιτεκτονικής). Οπότε το προηγούμενο structure των includes να γίνει κάπως έτσι:

```
.
├── _includes
│   ├── minimal-ionio
│   │   ├── footer.html
│   │   ├── fanalytics-providers
│   │   ├── comments-providers
│   │   ...
```
Με αυτήν την δομή θα εξασφαλίσουμε

1. το γεγονός οτι δεν θα έχουμε conflict με κάποιο μελλοντικό update του theme
2. "Συμβατή" δομή includes και CSS οπότε εύκολο scalability

Ενδεχομένως να βολεύει μελλοντικά να περαστούν όλα τα includes που αφορούν το minmal-ionio με αυτόν τον τρόπο για να είναι ακόμα πιο ξεκάθαρος **ο διαχωρισμός των προσθήκων που αφορούν το minimal-ionio και του default functionality του minimal-mistakes**

- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by dimpram** [comment]
Παρατήρησα οτι στο επίσημο θέμα [minimal mistakes](https://github.com/mmistakes/minimal-mistakes/tree/master/_includes), η δομή πχ `footer/custom` είναι επίτηδες έτσι με σκοπό το θέμα να παρέχει extensibility. Οπότε σκέφτηκα αντί να παρατήσω το issue, να αναλάβω να μεταφέρω όλα τα υπόλοιπα includes που αφορούν αποκλειστικά το minimal-ionio και δεν υπάρχουν στο minimal mistakes, στην δομή που περιέγραψα παραπάνω. Δηλαδή να κάνω αυτό που ανέφερα:

> Ενδεχομένως να βολεύει μελλοντικά να περαστούν όλα τα includes που αφορούν το minmal-ionio με αυτόν τον τρόπο για να είναι ακόμα πιο ξεκάθαρος ο διαχωρισμός των προσθήκων που αφορούν το minimal-ionio και του default functionality του minimal-mistakes

@epidrome γνώμη?

**Comment by epidrome** [comment]
εδώ και δύο χρόνια (ακριβώς!) παρακολουθώ αυτό:
https://github.com/jekyll/jekyll/pull/7554

είχε παγώσει, αλλά φαίνεται να ζεστάθηκε πάλι

το ερώτημα είναι κατά πόσο αξίζει να δουλεύουμε στο μινιμαλ-ιόνιο και να το ενημερώνουμε στο χέρι, αν τελικά μπορούμε να έχουμε κληρονομικότητα

επειδή δεν είναι σίγουρο ότι θα προχωρήσει η κληρονομικότητα είμαι θετικός για την καλύτερη οργάνωση που προσπαθείς

εναλλακτικά ένα ακόμη ενδιαφερον ανοιχτό θέμα που σχετίζεται με την οργάνωση του αποθετηρίου είναι αυτό
https://github.com/ioniodi/site-gr/issues/120

για εμένα φαίνεται αρκετά βατό, το έχω ήδη εφαρμόσει στο βιβλίο μου, οπότε μείωσα την επανάληψη των δεδομένων και παράγονται διαφορετικές οπτικές (σάητ, τυπωμένο βιβλίο, ηλεκτρονικό βιβλίο, κτλ) από διαφορετικά αποθετήρια που έχουν κοινά γκιτ σαμπμοντουλ.

**Comment by dimpram** [comment]
> εδώ και δύο χρόνια (ακριβώς!) παρακολουθώ αυτό:
> [jekyll/jekyll#7554](https://github.com/jekyll/jekyll/pull/7554)
> 
> είχε παγώσει, αλλά φαίνεται να ζεστάθηκε πάλι
> 
> το ερώτημα είναι κατά πόσο αξίζει να δουλεύουμε στο μινιμαλ-ιόνιο και να το ενημερώνουμε στο χέρι, αν τελικά μπορούμε να έχουμε κληρονομικότητα
> 
> επειδή δεν είναι σίγουρο ότι θα προχωρήσει η κληρονομικότητα είμαι θετικός για την καλύτερη οργάνωση που προσπαθείς
> 
> εναλλακτικά ένα ακόμη ενδιαφερον ανοιχτό θέμα που σχετίζεται με την οργάνωση του αποθετηρίου είναι αυτό
> [ioniodi/site-gr#120](https://github.com/ioniodi/site-gr/issues/120)
> 
> για εμένα φαίνεται αρκετά βατό, το έχω ήδη εφαρμόσει στο βιβλίο μου, οπότε μείωσα την επανάληψη των δεδομένων και παράγονται διαφορετικές οπτικές (σάητ, τυπωμένο βιβλίο, ηλεκτρονικό βιβλίο, κτλ) από διαφορετικά αποθετήρια που έχουν κοινά γκιτ σαμπμοντουλ.

Θυμάμαι το issue με τα submodules. Προσωπικά το έχω σκεφτεί λίγο στο μυαλό μου και δεν νομίζω πως θα είχε πολύ νόημα για κάθε collection να είχαμε ένα submodule. 

Όπως είχα πει μου φαίνεται πολύ engineered και αμά απλά ακολουθήσουμε καλύτερες πρακτικές οργάνωσης της πληροφορίας δεν νομίζω οτι θα έχουμε την ανάγκη καν να σκεφτόμαστε ένα τέτοιο σενάριο. 

Στο δικό σας πλαίσιο με το βιβλίο μου βγάζει περισσότερο νόημα γιατί εκεί χωρίζετε συγκεκρίμενο περιεχόμενο που απαιτεί συχνή αλλαγή και αποτελεί ένα μικρό μέρος του συνολικού έργου οπότε το να "κινείται" όλο το έργο γύρω από μικροπροσθήκες δεν είναι και τόσο κομψό.

Ωστόσο και εγώ κοιτούσα που και που το issue με το theme inheritance αλλά δεν βλέπω (σύντομα) φως. Πιστεύω οτι αξίζει να δουλεύουμε με τον καλύτερο δυνατό τρόπο μέχρι να αποκτήσουμε την δυνατότητα για αυτήν την εναλλακτική.

**Comment by epidrome** [comment]
όχι για κάθε συλλογή, αλλά για όλες μαζί, δλδ όλον τον φάκελο all_collections --> submodule
