### ISSUE TITLE
Mistyped character in a key value

### ISSUE THREAD

**Issue by provopoulos** [ioniodi/sitegr#162]
### Δήλωση Θέματος
- Στη δομή του αρχείου [courses.md](https://github.com/ioniodi/sitegr/blob/master/_pages/courses.md) έχει χρησιμοποιηθεί ο ελληνικός χαρακτήρας "Ο" στον τύπο μαθημάτων επιλογής:
```md
'courses' c_type = "Ο" <> Optional course, but this is the Greek "Ο" course
```
Αντικατάσταση με λατινικό χαρακτήρα "O". Με αυτήν την αλλαγή πρέπει να ενημερωθούν αναλόγως όλα τα μαθήματα που βρίσκονται στη συλλογή [/_courses](https://github.com/ioniodi/sitegr/tree/master/all_collections/_courses) ώστε να χρησιμοποιούν τον λατινικό χαρακτήρα.
- Εκτιμώμενη δυσκολία: Easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα: #92 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by dimpram** [comment]
Damn nice catch!!

**Comment by epidrome** [comment]
@provopoulos η λύση αλλαγής της γλώσσας για έναν μόνο χαρακτήρα που ενδέχεται να είναι παρόμοιος ανάλογα με την γραμματοσειρά, ίσως να μην είναι βέλτιστη. 

μήπως αντί για έναν χαρακτήρα να έχουμε μια συμβολοσειρά, "optional" "obligatory"?

**Comment by dimpram** [comment]
@epidrome αυτό είναι σίγουρα μια καλύτερη λύση αν όχι η καλύτερη
