### ISSUE TITLE
Προσθήκη ανακοίνωσης "Το Τμήμα Πληροφορικής του Ιονίου Πανεπιστημίου στη συνάντηση  του έργου OCTaNE"

### ISSUE THREAD

**Issue by johnalkmeg** [ioniodi/sitegr#168]
### Προσθήκη ανακοίνωσης "Το Τμήμα Πληροφορικής του Ιονίου Πανεπιστημίου στη συνάντηση  του έργου OCTaNE" https://di.ionio.gr/gr/news/13176/

- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p16pyla** [comment]
Καλο θα ήταν για λόγους κομψότητας να αφήσεις όπως είναι το "### Δήλωση Θέματος" για να εμφανίζεται όπως και στα υπόλοιπα issue και να προσθέσεις στην  "Σύντομη περιγραφή των επικείμενων αλλαγών" τον όνομα της προσθήκης σου μαζί με το λινκ δημοσίευσης.
