### ISSUE TITLE
Διόρθωση Σελίδας "Εργαστήρια"

### ISSUE THREAD

**Issue by p15anez** [ioniodi/sitegr#174]
### Δήλωση Θέματος

-  Έλεγχος και διόρθωση της σελίδας των Εργαστηρίων του Τμήματος (προβάλλονται εργαστήρια τα οποία δεν υπάρχουν πλέον, ενώ κάποια άλλα χρειάζονται ενημέρωση στις περιγραφές τους).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
το 2ο παραδοτέο θέλει μεγαλύτερη δυσκολία!
