### ISSUE TITLE
Μη-λειτουργικός σύνδεσμος προς τον οδηγό σπουδών

### ISSUE THREAD

**Issue by PaulosKal** [ioniodi/sitegr#175]
### Δήλωση Θέματος
- **Περιγραφή θέματος:** Διόρθωση κώδικα στο θέμα minimal-ionio για προσθήκη λειτουργικότητας στο κουμπί προς τον οδηγό σπουδών της αρχικής σελίδας. Το πρόβλημα βρίσκεται σε μια λάθος μεταβλητή liquid στο αρχείο video-background.html με αποτέλεσμα ο σύνδεσμος να είναι κενός.
- **Εκτιμώμενη δυσκολία:** easy
- **Σχετικά θέματα:** #32 (Εκεί άλλαξα το όνομα και το link αλλά εδώ διορθώνω το bug)

### Απορίες σχετικά με το θέμα
Για να επιτευχθεί ο στόχος, πρέπει να κάνω μια αλλαγή στο minimal-ionio. Αφού κάνω την αλλαγή (και τις δοκιμές):
- Θα χρειαστεί να κάνω pull request στο αποθετήριο minimal-ionio;
- Αν ναι, πρέπει να ανοίξω και σε εκείνο το αποθετήριο νέο issue;
- Αν όχι, να πειράξω το _config.yml του sitegr ώστε να δείχνει στο δικό μου θέμα;
- [x] Διάβασα τις [οδηγίες στο wiki](https://github.com/ioniodi/sitegr/wiki/Workflow) και δεν είναι ξεκάθαρες στο συγκεκριμένο ζήτημα.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
γράφεις για διόρθωση, αλλά δεν μας λες ποιο είναι το πρόβλημα! π.χ., γιατί δεν δουλεύει το λινκ που εσύ έβαλες σε προηγούμενο αίτημα?

**Comment by dimpram** [comment]
@PaulosKal  Αυτό που έκανα εγώ σε παρόμοια κατάσταση και δούλεψε ήταν να κάνω issue εδώ όπως έχεις κάνει και εσύ και μετά να κάνω το PR στο minimal-ionio έχοντας βάλει για closes 

```
closes [#175](https://github.com/ioniodi/sitegr/issues/175)
```

Έτσι όταν γίνει merge το PR σου στο minimal-ionio θα κλείσει αυτόματα το linked issue εδώ.

**Comment by PaulosKal** [comment]
Ευχαριστώ @dimpram!

@epidrome Έκανα ενημέρωση στο issue. Ελπίζω να είναι πιο ξεκάθαρο.

**Comment by provopoulos** [comment]
Not ready to be closed yet
