### ISSUE TITLE
Βελτιστοποίηση της SCSS του footer

### ISSUE THREAD

**Issue by p13brif** [ioniodi/sitegr#177]
### 
- Προτείνω την αλλαγή του κώδικα της SCSS για το footer προκειμένου η ιστοσελίδα να γίνει περισσότερο responsive όταν κάνουμε resize.
- Εκτιμώμενη δυσκολία: medium
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
duplicate or overlap or related? #109

**Comment by dimpram** [comment]
@p13brif ποιο είναι το πρόβλημα δηλαδη αυτήν την στιγμή στο footer;

**Comment by p13brif** [comment]
Μάλλον η περιγραφή του issue δεν ήταν αρκετά ακριβής. Παρατήρησα ότι το navigation bar όταν κάνουμε resize γίνεται dropdown list. Έτσι θεώρησα ότι και το footer θα έπρεπε να έχει μια ανάλογη λειτουργία. Δεν αναφέρομαι στο bug του overflow που πολύ σωστά είχε επισημάνει προηγουμένως και ο συνάδελφος. 
Ενδεικτικά μερικές εικόνες για την οπτικοποίηση της βελτιστοποιημένης πρότασης:

[![update.png](https://i.postimg.cc/zfFV19Jj/update.png)](https://postimg.cc/p9y2fc5h)

[![171963812-475152413832879-5306446104942249659-n.png](https://i.postimg.cc/VvQfrgL6/171963812-475152413832879-5306446104942249659-n.png)](https://postimg.cc/CB7T9j8T)

**Comment by dimpram** [comment]
> Μάλλον η περιγραφή του issue δεν ήταν αρκετά ακριβής. Παρατήρησα ότι το navigation bar όταν κάνουμε resize γίνεται dropdown list. Έτσι θεώρησα ότι και το footer θα έπρεπε να έχει μια ανάλογη λειτουργία. 

Προσωπικά θεωρώ οτι αυτή η αλλαγή δεν είναι πολύ καλή από άποψη User Experience. Το footer δεν είναι ένα είδος menu, είναι περισσότερο σαν ένας μικρός χάρτης της ιστοσελίδας.
 
Παρουσιαζείς στον χρήστη μέρη και προορισμούς που μπορεί να βρει πληροφορίες που ενδεχομένως να μην είχε βρει εως τώρα ή να θέλει να πλοηγηθεί γρήγορα σε αυτές. 

Σε τέτοιες περιπτώσεις το να προσθέσεις άλλο ένα μενού στον χρήστη το οποίο θα είναι παρόμοιο με το navigation bar, απλά προσθέτει ένα έξτρα επίπεδο πολυπλοκότητας χωρίς να είναι απαραίτητο.

Ξαναλέω, αυτή είναι η προσωπική μου άποψη μπορεί να έχω άδικο. Θα μου άρεσε να έλεγε και κάποιος άλλος την γνώμη του.

**Comment by p13brif** [comment]
> > Μάλλον η περιγραφή του issue δεν ήταν αρκετά ακριβής. Παρατήρησα ότι το navigation bar όταν κάνουμε resize γίνεται dropdown list. Έτσι θεώρησα ότι και το footer θα έπρεπε να έχει μια ανάλογη λειτουργία.
> 
> Προσωπικά θεωρώ οτι αυτή η αλλαγή δεν είναι πολύ καλή από άποψη User Experience. Το footer δεν είναι ένα είδος menu, είναι περισσότερο σαν ένας μικρός χάρτης της ιστοσελίδας.
> 
> Παρουσιαζείς στον χρήστη μέρη και προορισμούς που μπορεί να βρει πληροφορίες που ενδεχομένως να μην είχε βρει εως τώρα ή να θέλει να πλοηγηθεί γρήγορα σε αυτές.
> 
> Σε τέτοιες περιπτώσεις το να προσθέσεις άλλο ένα μενού στον χρήστη το οποίο θα είναι παρόμοιο με το navigation bar, απλά προσθέτει ένα έξτρα επίπεδο πολυπλοκότητας χωρίς να είναι απαραίτητο.
> 
> Ξαναλέω, αυτή είναι η προσωπική μου άποψη μπορεί να έχω άδικο. Θα μου άρεσε να έλεγε και κάποιος άλλος την γνώμη του.

Θα συμφωνήσω στο πρώτο κομμάτι της θέσης σου, ότι γενικά δεν είναι καλό practice να προσθέτουμε πολλά menus. Βέβαια στην προκειμένη περίπτωση το footer μετατρέπεται σε dropdown menu, όταν κάνουμε resize σε οθόνη μικρότερη απο 600 pixel, λειτουργία που εμένα προσωπικά μου φαίνεται περισσότερο ταιριαστή αισθητικά σε σχέση με ένα ατελείωτο σεντόνι επιλογών, ειδικά όταν έχουμε να κάνουμε με μικρές οθόνες. Αλλά ας πει και κάποιο άλλο άτομο τη γνώμη του.

**Comment by elias2500** [comment]
Θα μπορούσες να βάλεις κάποιο λινκ από κάποια υλοποίησή σου; Εμένα μου ακούγετε καλή ιδέα να μην είναι ένα ατελείωτο σεντόνι επιλογών, αλλά θα ήθελα να δώ και τηνυλοποίησή σου για να συγκρίνω καλύτερα το user experience.

**Comment by p13brif** [comment]
[Εδώ](https://site-gr.netlify.app/) μπορείτε να δείτε την πρόταση μου. Απλά επιλέξτε responsive design mode και κάντε scroll στο footer.

**Comment by elias2500** [comment]
> [Εδώ](https://site-gr.netlify.app/) μπορείτε να δείτε την πρόταση μου. Απλά επιλέξτε responsive design mode και κάντε scroll στο footer.

Προσωπικά, μου φαίνεται πως η υλοποίηση σου βελτιώνει την εμπειρία. 👍🏼

**Comment by epidrome** [comment]
το 1ο ποστ θα μπορούσε να βελτιωθεί με σχετικά λινκ-συνεργάτες

π.χ., από το γουηκι και τις σχετικές συζητήσεις
https://github.com/ioniodi/sitegr/wiki/Footer's-Shortcuts

με λίγο σκάψιμο (το οποίο όμως άλλοι συντελεστές δεν μπορούν να κάνουν με τόσο φτωχό 1ο ποστ)

προκύπτει αυτό ακριβώς που λέει ο @dimpram 

ο σκοπός είναι να έχουμε έναν "χάρτη πλοήγησης"

τι νόημα έχει ένας "κλειστός χάρτης"; 

πράγματι πιάνει λιγότερο χώρο, αλλά δεν βλέπουμε που παμε :)

σχετικά με την ευχρηστία @elias2500  αν και δεν το δοκίμασα σε κινητή συσκευή,

πως ακριβώς ξεδιπλώνει το μενού αφού δεν υπάρχει η έννοια-γεγονός του μαουζοβερ του δείκτη του ποντικιού;

πάντως, μπράβο για το ντέμο λινκ, το οποίο επίσης θα πρέπει να είναι στο 1ο ποστ για να μην ψάχνει ο κόσμος στο τσατ...

**Comment by elias2500** [comment]
> το 1ο ποστ θα μπορούσε να βελτιωθεί με σχετικά λινκ-συνεργάτες
> 
> π.χ., από το γουηκι και τις σχετικές συζητήσεις
> https://github.com/ioniodi/sitegr/wiki/Footer's-Shortcuts
> 
> με λίγο σκάψιμο (το οποίο όμως άλλοι συντελεστές δεν μπορούν να κάνουν με τόσο φτωχό 1ο ποστ)
> 
> προκύπτει αυτό ακριβώς που λέει ο @dimpram
> 
> ο σκοπός είναι να έχουμε έναν "χάρτη πλοήγησης"
> 
> τι νόημα έχει ένας "κλειστός χάρτης";
> 
> πράγματι πιάνει λιγότερο χώρο, αλλά δεν βλέπουμε που παμε :)
> 
> σχετικά με την ευχρηστία @elias2500 αν και δεν το δοκίμασα σε κινητή συσκευή,
> 
> πως ακριβώς ξεδιπλώνει το μενού αφού δεν υπάρχει η έννοια-γεγονός του μαουζοβερ του δείκτη του ποντικιού;
> 
> πάντως, μπράβο για το ντέμο λινκ, το οποίο επίσης θα πρέπει να είναι στο 1ο ποστ για να μην ψάχνει ο κόσμος στο τσατ...

Μου φαίνεται πιο εύκολο κάποιος να ανοίγει τον "χάρτη" μόνο για αυτό που τον ενδιαφέρει, όταν βέβαια έχουμε τον περιορισμό του χώρου οθόνης, παρά να πρέπει να ψάξει όλο τον χάρτη, ειδικά στην μορφή "πάπυρου" που παίρνει. 

Όσο για την ευχρηστία θα μπορούσε να προστεθεί ένα βελάλι με φορά προς τα κάτω ώστε να υπονοεί πως εκεί υπάρχει drop down menu. 

Το θέμα με τον "πάπυρο" είναι προγανώς προσωπική μου άποψη καθώς δεν μου φαίνεται το ίδιο κομψό, το υπερβολικό "σκρολάριμσα".
