### ISSUE TITLE
Προσθήκες στην Σελίδα Σπουδές

### ISSUE THREAD

**Issue by giouliker** [ioniodi/sitegr#178]
### Δήλωση Θέματος
- Θα  προσθέσω τις πληροφορίες που υπάρχουν στο site της σχολής στις [Προπτυχιακές Σπουδες](https://di.ionio.gr/gr/studies/undergraduate-studies/)  (όλες εκτός από τις κατηγορίες "Μαθήματα", "Ενδεικτικό Πρόγραμμα") )και θα τις βάλω στο [Σπουδές](https://epic-hamilton-da9ac8.netlify.app/courses/) κάνοντας αλλαγές και στα δύο αποθετήρια minimal-ionio,  sitegr . 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
1. αυτό φαίνεται ως απλή προσθήκη περιεχομένου
2. ακόμη και αν είμασταν στο 1ο παραδοτέο και πάλι δεν είναι καλή ιδέα να αντιγράφουμε μια (κακοσχεδιασμένη) ιστοσελίδα
3. για ποιο λόγο πρέπει να γίνουν αλλαγές στο μίνιμαλ-ιόνιο θέμα?
