### ISSUE TITLE
Δημιουργία δυνατότητας προσθήκης calendly link στα profile κάθε εκπαιδευτικού της σχολής

### ISSUE THREAD

**Issue by FaidonTsetsis** [ioniodi/sitegr#181]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη κώδικα στο αρχείο authors.yml στο αποθετήριο του sitegr και όπου αλλού κριθεί απαραίτητο, με σκοπό την προσθήκη calendly link για την δημιουργία εικονικών ραντεβού μεταξύ εκπαιδευτικών και φοιτητών.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
μερικές απορίες:

τι είναι ο ζουμ-λογαριασμός; για ζουμ-λινκ-μιτινγκ γνωρίζω,

που θα βρούμε αυτά τα λινκ, μήπως αλλάζουν συχνά;

έχει δει τις δυνατότητες του θέματος για λινκ σε προφιλ;
https://github.com/mmistakes/minimal-mistakes/issues/1529

αντί για ζουμ, μήπως είναι καλύτερα καλεντλι ώστε να γίνεται ραντεβού;

**Comment by dimpram** [comment]
More info here: https://mmistakes.github.io/minimal-mistakes/docs/authors/

**Comment by FaidonTsetsis** [comment]
> μερικές απορίες:
> 
> τι είναι ο ζουμ-λογαριασμός; για ζουμ-λινκ-μιτινγκ γνωρίζω,
> 
> που θα βρούμε αυτά τα λινκ, μήπως αλλάζουν συχνά;
> 
> έχει δει τις δυνατότητες του θέματος για λινκ σε προφιλ;
> [mmistakes/minimal-mistakes#1529](https://github.com/mmistakes/minimal-mistakes/issues/1529)
> 
> αντί για ζουμ, μήπως είναι καλύτερα καλεντλι ώστε να γίνεται ραντεβού;

Έχετε δίκιο οι σύνδεσμοι δεν παραμένουν σταθεροί για κάθε μάθημα ανά καθηγητή, επομένως η ιδέα αντικατάστασης του zoom link με αυτό ενός συνδέσμου calendly φαίνεται πιο σωστό και χρήσιμο. Θα προχωρήσω στις ανάλογες αλλαγές για το issue μου πραγματεύοντας την δημιουργία δυνατότητας calendly link.

**Comment by epidrome** [comment]
οκ, ενδιαφέρουσα προσθήκη, αν υποθέσουμε ότι οι καθηγητές έχουν σε μεγάλο ποσοστο κάλεντλι, έχουν?

μάλλον όμως η προσθήκη αυτή είναι περισσότερο για το 1ο παραδοτέο, αφού απλά θέλει ενημέρωση στα πεδία που υπάρχουν, δλδ για κάποιον νέο
