### ISSUE TITLE
Unselectable css

### ISSUE THREAD

**Issue by Haki-Malai** [ioniodi/sitegr#182]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αφαίρεση του κέρσορα εκεί που δεν χρειάζεται. Θα δημιουργήσω μια κλάση css για να κάνει όποια αντικείμενα θέλουμε unselectable. Για παράδειγμα: <br><img src="https://i.postimg.cc/fyCBg5rF/Screenshot-1.png" width=200>
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@Haki-Malai δεν καταλαβαίνω αν περιγράφεις κάποιο μπαγκ ή βελτίωση

στο σαφάρι-χρομ (μακ) δεν φαίνεται έτσι, επίσης ενημέρωσε με σχετικά λινκ-συντελεστές το ποστ σου

@provopoulos στο φαηρφοξ δεν φαίνεται καν το στρημ

**Comment by Haki-Malai** [comment]
@epidrome Από τι φαίνεται είναι όντως μια χαρά. Σε εμένα φαινόταν έτσι επειδή είναι feature του chrome το οποίο λέγεται caret navigation και απενεργοποιείται/ενεργοποιείται με το F7.
