### ISSUE TITLE
Δημιουργία νέας καρτέλας στο navigation bar “Ίδρυση”

### ISSUE THREAD

**Issue by KaterinaLaz** [ioniodi/sitegr#185]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : δημιουργία νέας καρτέλας στο navigation bar “Ίδρυση” στα πρότυπα του https://di.ionio.gr/gr/department/aim/ . Ουσιαστικά πρόκειται για μια νέα προσθήκη σε προ υπάρχον έργο.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @runtheorun-exe 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by KaterinaLaz** [comment]
Οι συνεργάτες που αναφέρω έχουν δουλέψει σε παλαιότερες προσθήκες στη navigation bar

**Comment by epidrome** [comment]
> Οι συνεργάτες που αναφέρω έχουν δουλέψει σε παλαιότερες προσθήκες στη navigation bar

πράγματι, αλλά μάλλον κανείς δεν θα είναι διαθέσιμος για να σχολιάσει πλέον, γιατί δεν κοιτάς λίγο στους συμφοιτητές σου;

επίσης, η ετικέτα που έβαλα σημαίνει ότι το θέμα είναι καλό μόνο για 1ο, όχι για 2ο παραδοτέο

**Comment by KaterinaLaz** [comment]
Εγώ δεν ήμουν συγκεκριμένη. Η προσθήκη “Ίδρυση” θα είναι διαδραστική δηλαδή με το κλικ θα παραπέμπει και σε καινούρια σελίδα όπως για παράδειγμα συμβαίνει με το “Σπουδές”. Θα πρέπει να γίνουν προσθήκες και στο minimal-ionio αλλά και στο sitegr.

Πρόσθεσα νέο συνεργάτη.

**Comment by epidrome** [comment]
η σελίδα που γράφεις είναι στατική:
https://di.ionio.gr/gr/department/aim/

δες σχετική συζήτηση
https://github.com/ioniodi/sitegr/discussions/191
