### ISSUE TITLE
Addition: Dark Theme Toggle

### ISSUE THREAD

**Issue by mariachlkt** [ioniodi/sitegr#186]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη λειτουργίας μαύρου θέματος 
- Εκτιμώμενη δυσκολία: medium/hard
- Σχετικοί συνεργατές: @provopoulos 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by mariachlkt** [comment]
Προσέθεσα συνεργάτη

**Comment by epidrome** [comment]
θα βοηθούσε να προσθέσεις και σχετικά λινκ π.χ
https://github.com/mmistakes/minimal-mistakes/discussions/2033

φαίνεται πως δουλεύει, αλλά δεν ξέρω τι επιπτώσεις θα έχει στο φορκ του θέματος
το οποίο το συντηρούμε στο χέρι το οποίο δεν είναι καλή πρακτική

ας μας πει την γνώμη του και ο @dimpram

**Comment by dimpram** [comment]
Σίγουρα γίνεται απλά διαβάζοντας τις παρακάτω πηγές μου φαίνεται αρκετά δύσκολο διότι στην πραγματικότητα όλα τα implementations που κοίταξα λειτουργούσαν με "hack" και οχι με κάποιον standard τρόπο. 

Στην πραγματικότητα όμως δεν υπάρχει standard τρόπος ούτε κάποιο specification οπότε είναι κυριολεκτικά μια custom πατέντα για το site που σε ενδιαφέρει.

Θα ήταν ενδιαφέρον να υπήρχε μια κομψή λύση που να υπολόγιζε τα παρακάτω:

1. Να μην επιρεάζει πολύ τα αρχεια του θέματος
2. Να μην υπάρχει τεράστιο code duplication
3. Το αποτέλεσμα να ταιριάζει με την αισθητική του minimal mistakes

Προσωπικά πιστεύω οτι θέλει λίγο ψάξιμο και συζήτηση οπότε δεν ξέρω αν είναι καλή ιδέα δεδομένου του χρονικού πλαισίου του μαθήματος.

Πηγές
- https://github.com/mmistakes/minimal-mistakes/discussions/2033
- https://medium.com/@derekkedziora/how-to-add-a-dark-mode-toggle-to-a-jekyll-site-a76dac00128d
- https://inclusive-components.design/a-theme-switcher/
