### ISSUE TITLE
Αφαίρεση καθηγητή κ. Χρήστου Αναγνωστόπουλου

### ISSUE THREAD

**Issue by p18mili1** [ioniodi/sitegr#187]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα αφαιρέσω από το πεδίο των επίκουρων καθηγητών της σελίδας των διδασκόντων τον κ. <a href="https://epic-hamilton-da9ac8.netlify.app/people/christos/">Χρήστο Αναγνωστόπουλο</a> ο οποίος δεν διδάσκει πλέον στο τμήμα και δεν αναφέρεται στη νέα σελίδα του τμήματος.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@c15pati @p18mili1 
φαίνεται πως ήδη έχει γίνει το εύκολο 1ο παραδοτέο
https://github.com/ioniodi/sitegr/issues?q=is%3Aissue+author%3Ap18mili1

έχετε διαβάσει τις οδηγίες για το 2ο παραδοτέο;

φυσικά είναι δεκτή μια συνεισφορά που βελτιώνει το έργο αλλά θα πρέπει να είναι σαφές (από τις οδηγίες) ότι δεν θα βαθμολογηθεί, σίγουρα πάντως θα εκτιμηθεί η προσπάθεια
