### ISSUE TITLE
Προσθήκη "Back to Top" Button

### ISSUE THREAD

**Issue by p17kots** [ioniodi/sitegr#188]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
  Θα προστεθεί πλήκτρο που σε πηγαίνει αυτόματα στην κορυφή της σελίδας.Θα προσπαθήσω να το προσθέσω σε όλες τις σελίδες,και αν αυτό δεν είναι εφικτό θα το προσθέσω σε όσες περισσότερες μπορώ.
- Εκτιμώμενη δυσκολία:  hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@p17kots το έχει δει αυτό;
https://github.com/mmistakes/minimal-mistakes/issues/1731

πράγματι φαίνεται δύσκολο και αναρωτιέμαι αν το θέλουμε την ώρα που υπάρχουν τόσα μπαγκ στον αέρα

**Comment by dimpram** [comment]
@p17kots Μου φαίνεται μια ενδιαφέρουσα προσθήκη. 

Ωστόσο δεν χρειάζεται να το προσθέσεις σε κάθε σελίδα αλλά αντιθέτως μπορείς να το βάλεις μόνο στο default layout (`_layouts/default.html`) ή στο custom footer include  (`_includes/footer/custom.html`) που υπάρχει διαθέσιμο από το θέμα και έτσι θα το 'παρουν' αυτόματα όλες οι ιστοσελίδες στο site :)

Πηγές:

- https://mmistakes.github.io/minimal-mistakes/docs/layouts/ 
- [mmistakes/minimal-mistakes#1731](https://github.com/mmistakes/minimal-mistakes/issues/1731) που ανέφερε ο @epidrome

**Comment by epidrome** [comment]
επίσης, αναρωτιέμαι κατά πόσο είναι σωστό-εφικτό να υλοποιούμε πράγματα που μπορούν να γίνουν αλλιώς

π.χ. για να πάμε στην κορυφή της σελίδας υπάρχουν κάποιοι τρόποι ήδη:
1. με το σκρολ μπαρ, δεν μου αρέσει, μάλιστα στο σαφάρι πλέον η απλ το έχει εξαφανίσει, υποθέτω γιατί οι περισσότεροι πλέον "χαιδεύουν" μια οθόνη ή ένα τρακπαντ, πάντως είναι καλός τρόπος για αρχάριους χρήστες
2. με το χομ στο πληκτρολόγιο
3. με κάποιο βιμ πλαγκιν, αυτό κάνω συνήθως, δλδ πατάω δύο φορές g

θα διαφωνήσω με τον @dimpram γενικά θέλει προσοχή να μην πέσουμε στις παγίδες που περιγράφει ο αλαν κεη στα βίντεο του (=πολλές γραμμές κώδικα για μικρό ή καθόλου κέρδος) αντίστοιχη συζήτηση γίνεται #186

**Comment by p17kots** [comment]
@epidrome @dimpram  
Σίγουρα δεν είναι μια προσθήκη που αποτελεί βασικό στοιχείο λειτουργικότητας ενός σαιτ.Το πρότεινα κυρίως γιατί είδα απο προσωπική χρήση ότι σε κάποιες σελίδες(π.χ σπουδές),είναι πολύ ενοχλητικό να πρέπει να σκλοράρεις μέχρι την αρχή της σελίδας για να συνεχίσεις την περιήγηση.Συμφωνώ πως υπάρχουν άλλα ζητήματα που πρέπει να λυθούν πρώτα,αλλά σίγουρα ο καθένας θα κοιτάξει να βελτιώσει τα προβλήματα που επηρεάζουν την προσωπική του χρήση(όπως #189) όπου ο συνεργάτης θα προσπαθήσει να βελτιώσει την χρήση από κινητές συσκευές.
Εν πάση περιπτώσει,συμφωνώ πως είναι καλύτερο να εστιάσουμε στα βασικά προβλήματα της ιστοσελίδας πριν προσθέσουμε παραπάνω λειτουργικότητα,γι'αυτό θα κοιτάξω να βελτιώσω κάποιο από αυτά.

@dimpram Εκτιμώ την συμβουλή που μου έδωσες!
