### ISSUE TITLE
Προσθήκη Responsiveness στην σελίδα του Προσωπικού

### ISSUE THREAD

**Issue by ntouloumtzis** [ioniodi/sitegr#189]
### Δήλωση Θέματος

- Η σελίδα του προσωπικού δεν συγχρονίζεται με το viewport μιας mobile οθόνης. Θα προσπαθήσω να κάνω την σελίδα responsive, ώστε να αναλογεί με τη κάθε κινητή συσκευή. Οπότε, οι αλλαγές θα γίνουν στο [minimal-ionio](https://github.com/ioniodi/minimal-ionio). 

![Screenshot_3](https://user-images.githubusercontent.com/36480343/114549310-831ac180-9c69-11eb-9189-0f31fb389430.png)

- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@ntouloumtzis 
μπράβο πολύ καλή ιδέα για θέμα

αλλά ενημέρωσε λίγο καλύτερα το ποστ σου, π.χ.,
https://github.com/ioniodi/minimal-ionio/blob/master/_includes/people-rank.html
καθώς και λινκ σε σχετικά θέματα-αιτήματα που είχε δουλευτεί αυτό για να μπορέσει ο κόσμος να σχολιάσει

υποθέτω θα βρεις και σχετικά θέματα-κώδικα στο μινιμαλ-μιστεηκς, μάλον η λύση είναι να γίνει καλύτερη χρήση των στυλ που ήδη έχει το θέμα
