### ISSUE TITLE
Προσθήκη Docker

### ISSUE THREAD

**Issue by Stavrospanakakis** [ioniodi/sitegr#192]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη Dockerfile και Docker Compose για εύκολο installation και execution του website. Μετά το configuration που θα προσθέσω, ο κάθε χρήστης θα μπορεί μόνο με ένα command να τρέχει το website χωρίς να χρειάζεται να έχει κατεβάσει όλα τα tools που χρειάζεται στον υπολογιστή του.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @sophia-ts @dimpram 
- Σχετικά θέματα: #5

Πρόσθεσα τους @sophia-ts  και @dimpram  σαν συνεργάτες σε περίπτωση που επιθυμούν να το δοκιμάσουν η να παραθέσουν βελτιώσεις και προτάσεις. Όσον αφορά τα σχετικά θέματα, πρόσθεσα το συγκεκριμένο διότι θεωρώ πως θα ήταν καλή ιδέα η προσθήκη documentation για όλους του τρόπους εγκατάστασης και εκτέλεσης του website.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@Stavrospanakakis @dimpram 
καταλαβαίνω την χρησιμότητα του ντόκερ σε πολύπλοκα έργα 
ειδικά σε επίπεδο συστήματος και πολλάπλών υπηρεσιών, 
π.χ., βάση δεδομένων-υπηρεσίες, όχι στις ρυθμίσεις χρήστη,
στην περίπτωση μας (που είναι σχετικά απλή) όπου
κάποιος μπορεί να κάνει απλά φόρκ εδώ και να βάλει νετλιφαη
ούτε καν χρειάζεται γραμμή εντολών για ενημέρωση στο περιεχόμενο

νομίζω πως με 2-3 αρχεία έχουμε έλεγχο, ακόμη και στο θέμα
https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
https://github.com/mmistakes/minimal-mistakes/blob/master/Rakefile
https://github.com/mmistakes/minimal-mistakes/blob/master/test/Gemfile

η απλότητα στην ανάπτυξη πολλές φορές σημαίνει ότι θέλει λίγο χέρι (=καλύτερη κατανόηση)
αντί για αυτοματισμούς που τελικά κρύβουν την λειτουργία που θέλουμε να ελέγχουμε:
https://wiki.archlinux.org/index.php/Arch_Linux#Simplicity

σίγουρα θα συμφωνήσω ότι η τεκμηρίωση θέλει βελτίωση
αλλά δεν είμαι σίγουρος ότι η λύση είναι να προσθέσουμε και άλλο λογισμικό
γιατί μετά θα θυμίζει λίγο την κατασκευή των πυραμίδων όλο αυτό ;-)
