### ISSUE TITLE
Προσθήκη διαδραστικού ωρολόγιου προγράμματος

### ISSUE THREAD

**Issue by runtheorun-exe** [ioniodi/sitegr#193]
### Δήλωση Θέματος
- ~~Προσθήκη σελίδας στην οποία θα εμφανίζεται το ωρολόγιο πρόγραμμα, όπως εμφανιζόταν κάποτε στην [ιστοσελίδα της σχολής](https://web.archive.org/web/20181112111916/http://di.ionio.gr/all-classes)~~ Αυτοματοποίηση ενημέρωσης της σελίδας [Timetables](https://epic-hamilton-da9ac8.netlify.app/timetables/)
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @Efthimis015 
- Σχετικά θέματα: https://epic-hamilton-da9ac8.netlify.app/timetables/

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@runtheorun-exe 
σχετικά θέματα?
πως σχετίζεται με αυτό: https://epic-hamilton-da9ac8.netlify.app/timetables/

**Comment by runtheorun-exe** [comment]
Έχει ενημερωθεί το issue για να συμπεριλάβει και το σχόλιό σας.
Εφόσον υπάρχει ήδη η δυνατότητα λοιπόν, ο στόχος είναι να τροποποιηθεί η σελίδα ώστε να ενημερώνει αυτόματα τα προγράμματα εξαμήνων (μέσω ίσως κάποιου pdf scraper? ακόμα είναι λίγο θολό)

**Comment by epidrome** [comment]
@runtheorun-exe το λινκ που έβαλες είναι λινκ! δεν είναι σχετικό θέμα-ισιου, υπάρχουν σχετικά αν ψάξεις..

σε παρακαλώ προσπάθησε λίγο πιο συστηματικά, γιατί όλο αυτό είναι μέρος της δουλειάς

αυτόματα δεν αξίζει, γιατί δεν είναι στάνταρ και ποτέ δεν είσαι σίγουρος τι θα σκεφτούν τα σαήνια του γκούη

όμως υπάρχουν λύσεις στο παλιό, αν ψάξεις..

**Comment by runtheorun-exe** [comment]
Με την πρώτη ευκαιρία θα παραθέσω το αντίστοιχο issue.
Θα ήθελα ωστόσο αν είναι εύκολο να μου εξηγήσετε το κομμάτι με τα σαήνια του γκούη; Αφορά το κομμάτι συλλογής δεδομένων ή προβολής αυτών στην δική σας σελίδα;

**Comment by epidrome** [comment]
επειδή ξεφεύγει λίγο από τον τίτλο του θέματος, το αφήνω ως άσκηση για συζήτηση ;) στην αντίστοιχη περιοχή π.χ., μεταφορά εκεί και συμμετοχή και άλλων

> Θα ήθελα ωστόσο αν είναι εύκολο να μου εξηγήσετε το κομμάτι με τα σαήνια του γκούη; Αφορά το κομμάτι συλλογής δεδομένων ή προβολής αυτών στην δική σας σελίδα;
