### ISSUE TITLE
Διόρθωση εμφάνισης των link "Learn More" στην βασική σελίδα μέσω οθόνης κινητού.

### ISSUE THREAD

**Issue by Haki-Malai** [ioniodi/sitegr#194]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Με μια γρήγορη ματιά μπορώ να πω πως το πρόβλημα είναι στο γεγονός ότι τα link είναι σε άλλο element. Προτείνω αυτό να αλλάξει και να τα συμπεριλάβω στο ίδιο element.
<img src="https://i.ibb.co/j4YLGvZ/172067907-557106621931776-2463247854436690397-n.jpg" width=200>   <img src="https://i.ibb.co/cTnhRKF/172216481-1363224817373333-5588512672764259385-n.jpg" width=200>
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @elias2500 @dimpram @provopoulos
- Σχετικά θέματα: [Displaced sidebar elements on mobile platforms #2822](https://github.com/mmistakes/minimal-mistakes/discussions/2822) [Bug: Τα κουμπιά "Learn More" στην αρχική σελίδα ανήκουν σε διαφορετικά div από τις αντίστοιχες στήλες](https://github.com/ioniodi/site-gr/issues/116)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
θέλουμε περισσότερες πληροφορίες στο 1ο ποστ
ποιο αρχείο έχει πρόβλημα; γιατί; σχετικά θέματα-αιτήματα, σχετικοί συνεργάτες για σχολιασμό
δεν είμαστε μόνοι μας!!

**Comment by Haki-Malai** [comment]
Περιμένω περαιτέρω οδηγίες, έκανα αυτά που μου ζητήσατε.

**Comment by epidrome** [comment]
έχεις δει την σχετική συζήτηση; 
https://github.com/ioniodi/site-gr/issues/116

το πρόβλημα δεν είναι μόνο αυτό που φαίνεται, 

αλλά έχει να κάνει με την συνολική υλοποίηση στις στήλες

ευχαρίστως να το δεις αλλά θα θέλαμε ένα λειτουργικό ντέμο λινκ πριν δώσουμε το πράσινο φως

γιατί είναι αρκετά δύσκολο για αρχάριους και δεν θέλουμε απλά να διορθώσουμε τα κουμπιά

**Comment by Haki-Malai** [comment]
@epidrome @dimpram @provopoulos Με την διαγραφή του περιεχομένου του αρχείου minimal-ionio/_includes/feature_row το αποτέλεσμα είναι το εξής:
<img src="https://i.ibb.co/7zSr8tf/Screenshot-1.png" alt="Screenshot-1" border="0">
  Δεν υπάρχουν άλλο τα κουμπιά "Learn More" ούτε αυτό το λευκό κενό το οποίο το θεωρώ άχρηστο και επομένως η σελίδα για mobile είναι μια χαρά. Οπότε προτείνω το εξής, να είναι έτσι η αρχική σελίδα και τα url των κουμπιών "Learn More" να είναι οι τίτλοι "Posts" και "Projects". Να σημειώσω ότι εγώ ως χρήστης τα κουμπιά "Learn More" νόμιζα ότι απευθυνόντουσαν στο περιεχόμενο του συγκεκριμένου Post/Project που εμφανίζοτανε και όχι γενικά.
  Τώρα στο άμα χρειάζεται κάπου αλλού το αρχείο του οποίου διέγραψα το περιεχόμενο δεν ξέρω. Απλά ήθελα να συζητήσουμε την συγγεκριμένη ιδέα.

**Comment by epidrome** [comment]
από το σκρινσοτ μόνο δεν μπορούμε να κάνουμε αξιολόγηση

καλύτερα να ανοίξεις ένα αίτημα με τα σχετικά λινκ-συνεργάτες

**Comment by dimpram** [comment]
> Δεν υπάρχουν άλλο τα κουμπιά "Learn More" ούτε αυτό το λευκό κενό το οποίο το θεωρώ άχρηστο και επομένως η σελίδα για mobile είναι μια χαρά. Οπότε προτείνω το εξής, να είναι έτσι η αρχική σελίδα και τα url των κουμπιών "Learn More" να είναι οι τίτλοι "Posts" και "Projects". Να σημειώσω ότι εγώ ως χρήστης τα κουμπιά "Learn More" νόμιζα ότι απευθυνόντουσαν στο περιεχόμενο του συγκεκριμένου Post/Project που εμφανίζοτανε και όχι γενικά.

Καλή ιδέα γενικά, απλά θα πρέπει μετά να μπεί το /projects στην μπάρα πλοήγησης διοτί διαφορετικά δεν υπάρχει τρόπος να πάει κάποιος εκεί.
