### ISSUE TITLE
Minify code in production

### ISSUE THREAD

**Issue by Stavrospanakakis** [ioniodi/sitegr#195]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα ήθελα να χρησιμοποιήσω το plugin jekyll-minifier με σκοπό να κάνει minify τον κώδικα στο production. Αυτό θα βοηθήσει στην ταχύτητα της σελίδας και στο SEO.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @sophia-ts 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
καλό θα ήταν να έχουμε σχετικά λινκ πχ στο πλαγκιν και στο κέρδος μας, 

έτσι όπως είναι τώρα ο καθένας μπορεί να βρει κάτι άλλο

μπορείς να περιγράψεις την δυσκολία σε αυτό το ζητούμενο;

από την τεκμηρίωση εγώ βλέπω 2-3 έντιτς στο κονφιγκ-τζεμφαηλ και έτοιμο;
