### ISSUE TITLE
Fix broken menu items

### ISSUE THREAD

**Issue by elias2500** [ioniodi/sitegr#196]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Χρησιμοποιώντας το Chrome και το build της σελίδας από το Netlify όταν χρησιμοποιώ το κουμπί "Τμήμα Πληροφορικής" στο header το menu "σπάει".
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by elias2500** [comment]
Το "σπασμένο " menu:
![Screenshot 2021-04-15 095134](https://user-images.githubusercontent.com/44614923/114826437-2f76b800-9dd0-11eb-9702-e37a1a6e6a9a.png)

**Comment by epidrome** [comment]
πράγματι ισχύει, αλλά γιατί δουλεύει αλλού; μήπως το πρόβλημα είναι το χρομ;

επίσης, το 1ο ποστ καλό είναι να έχει λινκ-συνεργάτες-κτλ

**Comment by elias2500** [comment]
> πράγματι ισχύει, αλλά γιατί δουλεύει αλλού; μήπως το πρόβλημα είναι το χρομ;
> 
> επίσης, το 1ο ποστ καλό είναι να έχει λινκ-συνεργάτες-κτλ

Φαντάζομαι πως είναι όντως το chrome για να δουλεύει καλά σε όλα τα υπόλοιπα. 
Η αλήθεια είναι πως χρειάζομαι βοήθεια γιατί δεν ξέρω καλά html/css/js κλπ παρόλα αυτά δεν έχω συναντήσει πολύ προθυμότητα και γιαυτό δεν έχω συμπληρώσει συνεργάτες.
Επίσης αν εννοείτε λινκ με προτεινόμενη υλοποίηση, δεν έχω ακόμα λόγω της έλλειψης γνώσεων και ικανοτήτων στις σχετικές γλώσσες.

**Comment by epidrome** [comment]
1. εντόπισε τα σχετικά αρχεία στο βασικό θέμα μινιμαλ μιστεηκς και δες εκεί σχετικά θέματα
2. έχουν γίνει κάποιες συζητήσεις σε άλλα θέματα είναι μερικοί (λίγοι αλήθεια) ενεργοί, ας μην είναι εντελώς σχετικοί
3. αν δεν μπορείς να εντοπίσεις το μπαγκ και να προτείνεις λύση μήπως πρέπει να βρεις άλλο θέμα;

**Comment by elias2500** [comment]
> 1. εντόπισε τα σχετικά αρχεία στο βασικό θέμα μινιμαλ μιστεηκς και δες εκεί σχετικά θέματα
> 2. έχουν γίνει κάποιες συζητήσεις σε άλλα θέματα είναι μερικοί (λίγοι αλήθεια) ενεργοί, ας μην είναι εντελώς σχετικοί
> 3. αν δεν μπορείς να εντοπίσεις το μπαγκ και να προτείνεις λύση μήπως πρέπει να βρεις άλλο θέμα;

Έχω εντοπίσει τα σχετικά αρχεία, αλλά όχι τι ακριβώς προκαλεί το bug.

Μια λύση που σκέφτηκα είναι να μετατρέπεται το μενού σε sliding menu είτε με slider είτε με κουμπιά όταν συμβαίνει αυτο το bug. Βέβαια δεν έχω καταφέρει να κάνω κάποια υλοποίησει που να την θεωρώ αρκετά καλή ακόμα.

Κατά πάσα πιθανότητα, δυστυχώς, θα χρειαστεί να αλλάξω θέμα :/ .
