### ISSUE TITLE
Προσθήκη Jekyll plugin (liquid filter) για email οbfuscation

### ISSUE THREAD

**Issue by p18myro** [ioniodi/sitegr#197]
### Δήλωση Θέματος
- Προσθήκη του Jekyll plugin [jekyll-email-protect](https://github.com/vwochnik/jekyll-email-protect) για απόκρυψη του email address από τα spam bots και ενεργοποίηση για  όλα τα emails του site.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @ p18mili1
- Σχετικά θέματα:
-![email](https://user-images.githubusercontent.com/56086094/114872205-c3fa0e00-9e02-11eb-9ee5-9945a85d4b8d.jpg)
![email-source-code](https://user-images.githubusercontent.com/56086094/115065867-64315f00-9ef7-11eb-931a-40c9ac2ab8d1.jpg)

Για να ενεργοποιηθεί θα πρέπει να γίνουν τροποποιήσεις σε δύο αρχεία στο minimal-ionio. Αρχικά στο config.yml προσθήκη στα plugins το jekyll-email protect και στο _includes/author-profile στο author.email προσθήκη | encode_email

σχετικό link με παράδειγμα : https://github.com/vwochnik/jekyll-email-protect#example

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
θέλουμε περισσότερες πληροφορίες στο 1ο ποστ!! π.χ., λινκ-συνερτάτες

π.χ., ποιο αρχείο στο μίνιμαλ-ιόνιο θα πρέπει να πειράξουμε για να ενεργοποιηθεί;

με τις λίγες πληροφορίες που δίνεις πράγματι είναι εύκολο με δύο έντιτ

ο προβληματισμός μου είναι ότι πειράζουμε αρχεία στο θέμα και δυσκολεύουμε την ενημέρωση του

καλό είναι να γίνει συζήτηση με σχετικούς συνεργάτες

**Comment by p18myro** [comment]
Για να ενεργοποιηθεί θα πρέπει να γίνουν τροποποιήσεις σε δύο αρχεία στο minimal-ionio. Αρχικά στο config.yml προσθήκη στα plugins το jekyll-email protect και στο _includes/author-profile στο author.email προσθήκη | encode_email

σχετικό link με παράδειγμα : https://github.com/vwochnik/jekyll-email-protect#example

**Comment by epidrome** [comment]
> θέλουμε περισσότερες πληροφορίες στο 1ο ποστ!! π.χ., λινκ-συνεργάτες

όχι μόνο τσάτ, χάνονται εδώ...

**Comment by p18myro** [comment]
οκ θα ανοίξω new discussion να ακούσουμε γνώμες σχετικά με τον προβληματισμό που υπάρχει και την πιθανή δυσκολία που μπορεί να προκληθεί κατά  την ενημέρωση του.
