### ISSUE TITLE
Read time σε posts και pages

### ISSUE THREAD

**Issue by p09apos** [ioniodi/sitegr#198]
### Δήλωση Θέματος
- Προσθήκη και ενεργοποίηση read-time για εμφάνιση του απαιτούμενου χρόνο διαβάσματος σε posts και pages
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
αυτό είναι απλά μια ρύθμιση στο θέμα που ήδη έχουμε
