### ISSUE TITLE
Προσθήκη κατάλληλου documentation

### ISSUE THREAD

**Issue by sophia-ts** [ioniodi/sitegr#199]
### Δήλωση Θέματος
- Προσθήκη κατάλληλου documentation / user manual για την διευκόλυνση των χρηστών στην εισαγωγή καινούριου περιεχομένου και στην τοπική εγκατάσταση της εφαρμογής
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @Stavrospanakakis 
- Σχετικά θέματα: - 

### Απορίες σχετικά με το θέμα (αν υπάρχουν) /  Σχολιασμός

Θεωρώ πως είναι καλή ιδέα να φτιάξω ένα manual όπου θα εξηγώ πολύ περιληπτικά το περιεχόμενο των folders και των files. Επίσης, το manual θα περιέχει εντολές για τοπική εγκατάσταση της εφαρμογής. Το manual αυτό μπορεί να βοηθήσει στην ταχύτερη κατανοήση του project και να βοηθήσει στην οργάνωση. Το έργο αυτό το σημείωσα ως hard γιατί χρειάζεται την άριστη γνώση του structure του project. Όπως καταλαβαίνεται είναι πολύ μεγάλο το φόρτο για ένα άτομο, οπότε είναι μια ευκαρία να συνεισφέρουν όσοι περισσότεροι συνάθελφοι μπορούν.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
είναι ανάγκη να εφεύρουμε τον τροχό;

τόσο κακή θεωρείς την τεκμηρίωση στα σημεία 1,2,3?
https://github.com/ioniodi/sitegr/wiki

ποια είναι τα προβλήματα της, μήπως να κάνουμε απλά βελτίωση?

μήπως υπάρχουν άλλα σημεία στην τεκμηρίωση όπου υπάρχει μεγαλύτερη ανάγκη;

**Comment by sophia-ts** [comment]
Σκεφτόμουν κάποιο πιο απλοϊκό user manual με λιγότερη πληροφορία για πιο αρχάριους χρήστες. Για παράδειγμα θυμάμαι πως στις διαλέξεις είχατε πει πως κάποιο άτομο που βλέπει πρώτη φορά την αρχιτεκτονική μπορεί να την χαρακτηρίσει χαοτική. Για αυτό πρότεινα και πρότεινα την δημιουργία manual για τους φοιτητές.

**Comment by epidrome** [comment]
> απλοϊκό user manual με λιγότερη πληροφορία για πιο αρχάριους χρήστες

ας μας πούνε κάποιοι "αρχάριοι χρήστες" την γνώμη τους γιατί για εμένα οι ενότητες που έχουμε στο γουήκι είναι ήδη πολύ απλές, 

εκτός και αν εννοείς να έχουμε επιπλέον περιεχόμενο-τεκμηρίωση από το τζεκιλ, το οποίο θα ήταν λάθος γιατί τότε στο μέλλον θα έχουμε την επιπλέον δουλειά να το κρατάμε συγχρονισμένο με εξωτερικές αλλαγές

κοιτάζοντας το γουήκι μια πιθανή βελτίωση θα ήταν η ροή εργασίας να μην μπερδεύει τους αρχάριους με το μινιμαλ-ιόνιο, αλλά αυτό απαιτεί ελάχιστες αλλαγές, απλά λίγο κοπι-πεηστ-εντιτ
https://github.com/ioniodi/sitegr/wiki/Workflow

αν εννοείς κάτι τέτοιο δεκτό, αλλά μάλλον κάπως λίγο για το 2ο αίτημα
