### ISSUE TITLE
Δημιουργία ects-calculator

### ISSUE THREAD

**Issue by andreaspappoutas** [ioniodi/sitegr#20]
### Δήλωση Θέματος
Δημιουργία εργαλείου όπου υπολογίζει τις μονάδες ects με κατάλληλες λειτουργίες έτσι ώστε να μην χρειάζονται πολλά clicks.
- Εκτιμώμενη δυσκολία: very hard
- Σχετικοί συνεργατές: @andreaspappoutas 

[live link](https://andreaspappoutas-sitegr.netlify.app/ects-calculator/)

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
πολύ καλό θέμα, αρκεί να γίνει με τρόπο συμβατό με τις βιβλιοθήκες του θέματος και με την τεχνολογία του jekyll.
