### ISSUE TITLE
Παραγωγή xml sitemap αρχείου για υποβολή της σελίδας στη μηχανή ανζήτησης google

### ISSUE THREAD

**Issue by p09apos** [ioniodi/sitegr#200]
### Δήλωση Θέματος
- Προσθήκη xml sitemap για υποβολή της σελίδας στη μηχανή ανζήτησης google. Η δημιουργία του αρχείου sitemap.xml θα γίνει τοπικά με ή χωρίς τη χρήση plugins.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
τι διαφορά έχει από αυτό που έχουμε ήδη;

https://github.com/ioniodi/sitegr/blob/master/Gemfile
https://github.com/jekyll/jekyll-sitemap
https://github.com/ioniodi/sitegr/blob/master/_config.yml

**Comment by p09apos** [comment]
Θα το έκανα χωρίς τη χρήση plugin. 
Point taken. 
Θα βρω κάτι άλλο. 
Ευχαριστώ
