### ISSUE TITLE
Προσθήκη drop-down list για το menu Item Προσωπικό στην αρχική σελίδα

### ISSUE THREAD

**Issue by p18mili1** [ioniodi/sitegr#203]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Δημιουργία drop-down list στην επιλογή Προσωπικό, η οποία θα περιέχει τις 7 κατηγορίες του προσωπικού. Κατάργηση της σελίδας <a href="https://epic-hamilton-da9ac8.netlify.app/people/">Προσωπικό</a> και κατ΄αντιστοιχία δημιουργία 7 νέων σελίδων. Τροποποίσηση των κατάλληλων αρχείων στο minimal-ionio και στο sitegr.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@p18mili1 

τι κέρδος έχει να προσθέτουμε κλικ στην πλοήγηση του χρήστη και σελίδες-αρχεία στο σύστημα αρχείων???

μήπως είναι καλύτερα να βάλουμε έναν πίνακα περιεχομένων στην σελίδα του προσωπικού;

θυμίζω ότι τα θέματα για το 2ο παραδοτέο πρέπει να έχουν σχετικούς συνεργάτες παλιούς και κυρίως νέους συμφοιτητές του έτους, το λένε οι οδηγίες και είναι βασικό κριτηρίο επιτυχίας, δεν μπορείτε να μιλάτε όλοι μόνο μαζί μου!!
