### ISSUE TITLE
Προσθήκη Νέου Topic "Πτυχιακή Εργασία" που περιέχει αναλυτικά την διαδικασία. 

### ISSUE THREAD

**Issue by Miltos9** [ioniodi/sitegr#204]
### Δήλωση Θέματος
- Θα δημιουργήσω ένα νέο Topic με όνομα Πτυχιακή Εργασία και θα περιέχει σαν κείμενο όλη την διαδικασία που πρέπει να ακολουθήσει ο φοιτητής.

- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: 
- Σχετικά θέματα: Από αυτή την δουλειά θα προκύψουν νέες ιδέες για προσθήκες σε άλλους φοιτητές (π.χ. προσθήκη του Pdf Κανονισμός πτυχιακής εργασία 2021 στο συγκεκριμένο Topic.)

###

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
θυμίζω ότι τα θέματα για το 2ο παραδοτέο πρέπει να έχουν:
1. αυξημένη δυσκολία, όπου νέα σελίδα είναι μια εναλλακτική οπτική πάνω στα δεδομένα και ότι απλά νέο περιεχόμενο κόπι-πεηστ
2.  σχετικούς συνεργάτες παλιούς και κυρίως νέους συμφοιτητές του έτους, το λένε οι οδηγίες και είναι βασικό κριτηρίο επιτυχίας, δεν μπορείτε να μιλάτε όλοι μόνο μαζί μου!!
