### ISSUE TITLE
Edited: Προσθήκη λογότυπου του τμήματος

### ISSUE THREAD

**Issue by cyclenikolaos** [ioniodi/sitegr#205]
### Edited issue:
- Θα κάνω upload στο δικό μου repository [sitegr/tree/master/assets/images](https://github.com/cyclenikolaos/sitegr/tree/master/assets/images) την εικόνα του λογότυπου που θα χρησιμοποιήσω:
![LOGOTYPO_IONIO](https://user-images.githubusercontent.com/56065092/115349953-249b9900-a1bd-11eb-9666-74a751b70939.png)
- Θα τροποποιήσω το αρχείο masterhead.html στο δικό μου repository [minimal-ionio/tree/master/_includes](https://github.com/cyclenikolaos/minimal-ionio/tree/master/_includes)
- Θα τροποποιήσω το αρχείο _config.yml στο δικό μου repository [minimal-ionio](https://github.com/cyclenikolaos/minimal-ionio/tree/master/_includes)
- Θα τροποποιήσω το αρχείο _config.yml στο δικό μου repository [sitegr](https://github.com/cyclenikolaos/sitegr)

- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
πως θα γίνει αυτό, το υποστηρίζει το κεντρικο μας θέμα, λινκ σε σχετικά άρχεια;

παρακαλώ να ενημερωθεί το αρχικό θέμα με τα σχετικά λινκ-περιγραφή και να μην γίνει τσατ-σεντόνι παρακάτω, τα λένε οι οδηγίες αυτά και είναι κριτήρια επιτυχίας!

**Comment by p19pasc** [comment]
@epidrome νομίζω αξίζει να προσθεθεί tag good first issue εδώ, απαιτείται απλά η προσθήκη της φωτογραφίας και μετά μία προσθήκη στο _config.yml αρχείο του sitegr. Επειδή ψάχνω για αίτημα ενσωμάτωσης 2 νόμιζα ότι θα χρειαζόταν αλλαγές στο minimal-ionio ώστε να το έχω ως σχετικό issue, το υλοποίησα αλλά απλά απαιτεί αυτό που ανέφερα.

![Screenshot from 2022-04-10 18-22-34](https://user-images.githubusercontent.com/72496151/162626871-38624cf3-4037-4ae6-9696-e0011bc3a7f6.png)

**Comment by p19pasc** [comment]
> @epidrome νομίζω αξίζει να προσθεθεί tag good first issue εδώ, απαιτείται απλά η προσθήκη της φωτογραφίας και μετά μία προσθήκη στο _config.yml αρχείο του sitegr. Επειδή ψάχνω για αίτημα ενσωμάτωσης 2 νόμιζα ότι θα χρειαζόταν αλλαγές στο minimal-ionio ώστε να το έχω ως σχετικό issue, το υλοποίησα αλλά απλά απαιτεί αυτό που ανέφερα.
> 
> ![Screenshot from 2022-04-10 18-22-34](https://user-images.githubusercontent.com/72496151/162626871-38624cf3-4037-4ae6-9696-e0011bc3a7f6.png)

μπορώ να τεκμηριώσω την προσθήκη μου με λινκς αλλά εφόσον δεν θα γίνει αποδεχτεί ως issue κάποιος άλλος που θα το αναλάβει θα έχει έτοιμη τη διαδικασία.
