### ISSUE TITLE
Fixed Main Menu

### ISSUE THREAD

**Issue by p16koub1** [ioniodi/sitegr#206]
### Δήλωση Θέματος
- Τροποποίηση του main menu έτσι ώστε να μένει στο πάνω μέρος της σελίδας όταν κάνεις scroll προς τα κάτω. Έτσι ώστε να μη χρειάζεται να κάνεις scroll προς τα πάνω κάθε φορά για να έχεις πρόσβαση στο main menu. 
- [Site Repository](https://github.com/p16koub1/sitegr) , [Theme Repository](https://github.com/p16koub1/minimal-ionio) , [Site Preview](https://eloquent-hermann-3a9305.netlify.app)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p17kots @Axel12321 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ενδέχεται να είναι κάπως δύσκολο και κυρίως να έχει επιπτώσεις
https://github.com/mmistakes/minimal-mistakes/issues/490

παρακαλώ για καλύτερη μελέτη της τεκμηρίωσης και εύρεση των αυτονόητων λινκ πριν το άνοιγμα θέματος!

αν βέβαια έχεις κάποιο λειτουργικό ντέμο μπράβο σου, και να το δούμε

**Comment by p16koub1** [comment]
Μπορείτε να δείτε την αλλαγή εδώ: https://eloquent-hermann-3a9305.netlify.app/people/
Οι αλλαγές γίναν με βάση το issue που κάνατε link.
Το repository του theme: https://github.com/p16koub1/minimal-ionio
Το repository του site: https://github.com/p16koub1/sitegr

**Comment by epidrome** [comment]
μπράβο, παρακαλώ για την ενημέρωση του 1ου ποστ με τα παραπάνω λινκ καθώς και με σχετικούς αξιολογητές για σχολιασμό
