### ISSUE TITLE
Προσθήκη νέου Topic "Μετά το πτυχίο".

### ISSUE THREAD

**Issue by p18vogd** [ioniodi/sitegr#207]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:    Στο συγκεκριμένο Topic που θα δημιουργήσω θα περιέχει πληροφορίες σχετικά με το τι μπορεί ο φοιτητής να ασχοληθεί μετά την ολοκλήρωση των σπουδών του. Όλες οι πληροφορίες θα προέρχονται από την επίσημη σελίδα του τμήματος ( συγκεκριμένα από εδώ : https://di.ionio.gr/gr/studies/undergraduate-studies/after-graduation/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα: 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
θυμίζω ότι τα θέματα για το 2ο παραδοτέο πρέπει να έχουν:

αυξημένη δυσκολία, όπου νέα σελίδα είναι μια εναλλακτική οπτική πάνω στα δεδομένα και ότι απλά νέο περιεχόμενο κόπι-πεηστ
σχετικούς συνεργάτες παλιούς και κυρίως νέους συμφοιτητές του έτους, το λένε οι οδηγίες και είναι βασικό κριτηρίο επιτυχίας, δεν μπορείτε να μιλάτε όλοι μόνο μαζί μου!!
