### ISSUE TITLE
Τροποποίηση των σελίδων των κατευθύνσεων

### ISSUE THREAD

**Issue by p17kots** [ioniodi/sitegr#208]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
  Θα διαχωρίσω τα μαθήματα των σελίδων των κατευθύνσεων[link](https://epic-hamilton-da9ac8.netlify.app/humanistic) [link](https://epic-hamilton-da9ac8.netlify.app/systems) ανά εξάμηνο.Νομίζω πως πρέπει να είναι πιο ξεκάθαρο το πως δομείται το πρόγραμμα σπουδών όσον αφορά τις κατευθύνσεις.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @Axel12321 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ποια η διαφορά με την κεντρική λίστα όπου υπάρχει διαχωρισμός ανά εξάμηνο/κατεύθυνση; π.χ.
https://epic-hamilton-da9ac8.netlify.app/courses/#μαθήματα-κατεύθυνσης-αε

**Comment by p17kots** [comment]
@epidrome 
Πρακτικά είναι το ίδιο πράγμα,απλός επειδή υπάρχουν ήδη υλοποιημένες και οι ξεχωριστές σελίδες θεωρώ πως θα πρέπει να υπάρξει και εκεί ένας διαχωρισμός για να είναι ευανάγνωστο.

**Comment by epidrome** [comment]
ας προσπαθήσουμε να δουλέψουμε σε κάτι παραγωγικό και όχι απλά να κάνουμε κάτι 

θυμίζω ότι η κατανόηση σε βάθος του έργου και ο έγκυρος εντοπισμός θεμάτων είναι το ζητούμενο, όχι απλά μια λύση για ένα πρόβλημα που δεν υπάρχει (στα ασύγχρονα βίντεο ο άλαν κέη περιγράφει το γιατί)
