### ISSUE TITLE
Δημιουργία νέας σελίδας για τις εγκαταστάσεις του πανεπιστημίου

### ISSUE THREAD

**Issue by p17kots** [ioniodi/sitegr#212]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
  Πίο συγκεκριμένα,μέσα στην στήλη "Χρήσιμοι σύνδεσμοι" θα προστεθεί ένα ακόμα λινκ που θα οδηγεί σε μία νέα σελίδα με  όνομα "facilities".Η σελίδα θα έχει ίδια μορφολογία με την σελίδα [contact](https://epic-hamilton-da9ac8.netlify.app/contact/),δηλαδή θα έχει τις τοποθεσίες των εγκαταστάσεων στον χαρτη,και σαν εγκαταστάσεις αναφέρομαι σε βιβλιοθήκη,πανεπιστημιακό κολυμβητήριο,πανεπιστημιακό γυμναστήριο,εστίες και τυχόν άλλα που θα προταθούν. 
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @Axel12321 @p16koub1
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
η σελίδα είναι για το τμήμα

μια τέτοια σελίδα θα ήταν χρήσιμη για την ιδρυματική σελίδα

επίσης αυτού του είδους η συνεισφορά είναι απλά δεδομένα και δεν είναι αρκετή για το 2ο παραδοτέο
