### ISSUE TITLE
ECTS calculator conflicts with PWA plugin

### ISSUE THREAD

**Issue by epidrome** [ioniodi/sitegr#22]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @andreaspappoutas @geocfu 
- Σχετικά θέματα:

**Comment by andreaspappoutas** [comment]
Άλλαξα το τρόπο που καλούμε το plugin στο Gemfile και έκανα pull request. Στο deploy preview είναι οκ.
Τώρα θα είναι έτσι:
```
Fetching https://github.com/lavas-project/jekyll-pwa
...
Using jekyll-pwa-plugin 5.1.4 from https://github.com/lavas-project/jekyll-pwa (at master@4d92e7b)
...

```

**Comment by epidrome** [comment]
αν θες ενημέρωσε το παραπάνω ποστ με μια γραμμή-λινκ γιατί δημιουργήθηκε πρόβλημα, όπως είναι τώρα μας λές μόνο την λύση, αλλά δεν καταλαβαίνουμε γιατί μας έβγαλε πρόβλημα ξαφνικά
