### ISSUE TITLE
Προσθήκη μαθήματος  "Μουσείο & Κοινωνικά Δίκτυα"

### ISSUE THREAD

**Issue by geopala** [ioniodi/sitegr#220]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη μαθήματος "Μουσείο & Κοινωνικά Δίκτυα". Αποτελεί μάθημα ελεύθερης επιλογής του τμήματος Αρχειονομίας, Βιβλιοθηκονομίας & Μουσειολογίας αλλά υπάρχει και στην καρτέλα του τμήματος Πληροφορικής. Αν δεν γίνει δεκτό, μπορώ να το αλλάξω.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα: Προσθήκη μαθήματος

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
όπως λένε οι οδηγίες το 2ο αίτημα θα πρέπει να είναι για κάτι πιο δύσκολο

**Comment by geopala** [comment]
> όπως λένε οι οδηγίες το 2ο αίτημα θα πρέπει να είναι για κάτι πιο δύσκολο

Καλησπέρα και πάλι, γνωρίζω για την αυξανόμενη δυσκολία που απαιτείται στο 2ο αίτημα, όμως κατάφερα μόνο να εντοπίσω ως πιθανές 2 προσθήκες το παραπάνω μάθημα και ένα ακόμη.
Παρόλο αυτά, δημιούργησα κανονικά το κατάλληλο .md και PR αυτού.

**Comment by geopala** [comment]
@epidrome @c15pati 
Χαίρετε για τρίτη φορά, κατάφερα να διορθώσω το πρόβλημα με το .md αρχείο μου και να περάσουν τα checks όπως πρέπει.
Είναι εύκολο να ρίξετε μια ματιά ξανά στο PR που έχω ανοίξει ή να το κλείσω εφόσον είναι ίδιας δυσκολίας με το 1ο? 
Τα αρχεία και η περιγραφή του παραδοτέου έχουν ανέβει κανονικά στην αναφορά μου. 
Παρακαλώ να το δείτε το συντομότερο ώστε να μπορέσω να ανοίξω και το τελικό PR για την αναφορά μου εντός της προθεσμίας.
Ευχαριστώ προκαταβολικά

**Comment by apostoloskp** [comment]
Link του παραπάνω PR: https://github.com/ioniodi/sitegr/pull/223
