### ISSUE TITLE
Προσθήκη Ανακοίνωσης "Εκδήλωση - Καλωσόρισμα πρωτοετών φοιτητών Τμήματος Πληροφορικής ακαδ. έτους 2021 - 2022" από site τμήματος

### ISSUE THREAD

**Issue by p14pall** [ioniodi/sitegr#225]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Ανάρτηση ανακοίνωσης "Εκδήλωση - Καλωσόρισμα πρωτοετών φοιτητών Τμήματος Πληροφορικής ακαδ. έτους 2021 - 2022" που δημοσιεύτηκε 21-10-2021
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p14pall** [comment]
@epidrome είναι εύκολο να μου δώσετε green light γιατι πρέπει να ανοίξω και δεύτερο issue;

**Comment by epidrome** [comment]
@c15pati ???

**Comment by p14pall** [comment]
@epidrome Καλησπέρα και πάλι και καλή χρονιά.
Είναι εύκολο να μου δώσετε το green light και να ρίξετε μια ματιά και στο δεύτερο αίτημά μου καθώς επιβάλλεται να ανοίξω το τελικό PR λόγω φόρτου εργασίας? Επίσης αν γίνεται να μου εξηγήσετε γιατί έλαβα **procrastinating** στο συγκεκριμένο αίτημα.

**Comment by diogenisAl** [comment]
Καλή συνέχεια @p14pall
