### ISSUE TITLE
Προσθήκη μαθήματος "Χωρικές Βάσεις Δεδομένων και Γεωγραφικά Πληροφοριακά Συστήματα"

### ISSUE THREAD

**Issue by p14pall** [ioniodi/sitegr#226]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p14pall** [comment]
@epidrome αν μπορείτε να δείτε και αυτό

**Comment by epidrome** [comment]
όπως λένε οι οδηγίες,

για την δεύτερη συνεισφορά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά, 

θα πρέπει να γίνει υλοποίηση για μια νέα λειτουργία, υπάρχουν αρκετά παραδείγματα στο ιστορικό
