### ISSUE TITLE
Προσθήκη ανακοίνωσης "Δράση STEM - Ρομποτικής του Τμήματος Πληροφορικής του Ιονίου Πανεπιστημίου και του Corfu Tech Lab (American Spaces) στην Δημόσια Κεντρική Ιστορική Βιβλιοθήκη Κέρκυρας"

### ISSUE THREAD

**Issue by Vagelis1993** [ioniodi/sitegr#228]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : προσθήκη ανακοίνωσης "Δράση STEM - Ρομποτικής του Τμήματος Πληροφορικής του Ιονίου Πανεπιστημίου και του Corfu Tech Lab (American Spaces) στην Δημόσια Κεντρική Ιστορική Βιβλιοθήκη Κέρκυρας"
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @initialelizah, @p18balt
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
OK @Vagelis1993, μπορείς να προχωρήσεις

**Comment by Vagelis1993** [comment]
Δεν το γνώριζα, θα διορθωθεί!
Σας ευχαριστώ

**Comment by epidrome** [comment]
@diogenisAl @Vagelis1993 
σύμφωνα με τις οδηγίες θα πρέπει να μπουν και δύο αξιολογητές στους σχετικούς συνεργάτες ώστε να αξιολογήσουν το αίτημα

την ετικέτα good first issue την βάζουμε σε ορφανά θέματα που είναι κατάλληλα για νέους
