### ISSUE TITLE
Αλλαγή βαθμίδας στον καθηγητή Παναγιώτη Κουρουθανάση

### ISSUE THREAD

**Issue by Alkissourvinos** [ioniodi/sitegr#232]
### Δήλωση Θέματος
- Αλλαγή βαθμίδας στον καθηγητή Παναγιώτης Κουρουθανάσης
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Tsimpliarakis @p19tzam
- Σχετικά θέματα: [di.ionio/staff](https://di.ionio.gr/gr/department/staff/professors/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@diogenisA @alkissourvinos
αρκεί να κάνετε μια μικρή αλλαγή, αφήστε κάτι και για τους άλλους!

αλλάξτε τον τίτλο-περιεχόμενο με έναν μόνο καθηγητή.

**Comment by Alkissourvinos** [comment]
@epidrome Η αλλαγή έγινε και περιμένω το green light για να στείλω το pull request

**Comment by epidrome** [comment]
https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2297217

σε ποια σελίδα του επίσημου τον βρήκες; ποιους θα καλέσεις να αξιολογήσουν την αλλαγή;

σας παρακαλώ να μην βιάζεστε και να συμπληρώνετε προσεκτικά όλα τα πεδία ώστε να διευκολύνετε την επεξεργασία των αιτημάτων

**Comment by Alkissourvinos** [comment]
@epidrome Οι αλλαγές έγιναν περιμένω τον σχολιασμό σας και των συναδέρφων

**Comment by Tsimpliarakis** [comment]
Σωστή παρατήρηση συνάδελφε.

Είσαι ο πιο κατάλληλος για μια τέτοια παρατήρηση άλλωστε.

**Comment by p19tzam** [comment]
Όπως έπρεπε έκανες τις αλλαγές και άφησες θέματα και για τους άλλους συναδέλφους θεωρώ τελευταίο βήμα που σου μένει το pull request.

**Comment by Alkissourvinos** [comment]
@epidrome @diogenisAl Το pull request είναι έτοιμο και περιμένω το green light!

**Comment by diogenisAl** [comment]
@Alkissourvinos τσάκω το green light
