### ISSUE TITLE
Διαγραφή καθηγητή Δημήτρης Τσουμάκος

### ISSUE THREAD

**Issue by p19tzam** [ioniodi/sitegr#233]
### Δήλωση Θέματος
- Διαγραφή καθηγητή Δημήτρης Τσουμάκος
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Tsimpliarakis @Alkissourvinos
- Σχετικά θέματα: https://di.ionio.gr/gr/department/staff/professors/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
https://github.com/ioniodi/sitegr/issues/232

**Comment by Alkissourvinos** [comment]
Πολύ καλό και απλό. Προχωράς κανονικά!

**Comment by Tsimpliarakis** [comment]
Έχεις δίκιο συνάδελφε, προχώρα κανονικά.

**Comment by epidrome** [comment]
ο σύνδεσμος closes είναι λάθος και δεν έκλεισε αυτόματα εδώ
