### ISSUE TITLE
 Προσθήκη Βιβλίων για το μάθημα "Εφαρμοσμένος προγραμματισμος με Python" 

### ISSUE THREAD

**Issue by p19pasc** [ioniodi/sitegr#234]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα προσθέσω στο αρχείο [sitegr/_bibliography/references.bib](https://github.com/ioniodi/sitegr/blob/master/_bibliography/references.bib) τα απαραίτητα βιβλία και  θα ενημερώσω το αρχείο [all_collections/_courses/ applied-programming-python.md](https://github.com/ioniodi/all_collections/blob/master/_courses/applied-programming-python.md)   
    - Επίσημη σελίδα του [Ιονίου Πανεπιστημίου στο μάθημα της python](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/733/)
    - Η τωρινή [ιστοσελίδα μας](https://epic-hamilton-da9ac8.netlify.app/courses/applied-programming-python/)
    - [Demo](https://p19pasc-sitegr.netlify.app/courses/applied-programming-python/) για το πως θα φαίνεται η ιστοσελίδα μας μετά την προσθήκη των βιβλιογραφιών μου με το pull request, εφόσον συνδέσετε κατάλληλα τα submodules.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @vasiliskampani @u2nmd
- Σχετικά θέματα: #176 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p19pasc θα πρέπει να προσθέσεις και σχετικούς συνεργάτες στο αρχικό post

**Comment by p19pasc** [comment]
@diogenisAl Η προσθήκη έγινε.

**Comment by diogenisAl** [comment]
@p19pasc ΟΚ! Πρόσθεσε και τον σύνδεσμο στη σελίδα με την αρχική πληροφορία.
Θα πρέπει να αξιολογήσουν την πρότασή σου οι σχετικοί συνεργάτες που αναφέρονται παραπάνω.

**Comment by vasiliskampani** [comment]
Πολύ καλή η προσθήκη βιβλιογραφιών για το μάθημα "Εφαρμοσμένος προγραμματισμός με Python" και αρκετά σημαντική για τους υπόλοιπους συμφοιτητές μας που θέλουν περισσότερες πηγές πληροφοριών.

**Comment by u2nmd** [comment]
Καλή η προσθήκη σου @p19pasc, είναι σημαντικό να υπάρχει αντιστοιχία μεταξύ των βιβλίων στον εύδοξο και αυτών που βρίσκονται στο μάθημα στην σελίδα του τμήματος.

**Comment by p19pasc** [comment]
@diogenisAl Πρόσθεσα την επίσημη ιστοσελίδα του Πανεπιστημίου όπως ανέφερες και το demo που αποδικνύουν τις αλλαγές που θα συμβανούν στην ιστοσελίδα μας ύστερα από την αποδοχή του pull request! Επίσης έλαβα άμεσα έγκριση από τους συνεργάτες.

**Comment by p19pasc** [comment]
Δυστυχώς κλείνω το [issue](https://github.com/ioniodi/sitegr/issues/234) μου καθώς και τα αντίστοιχα pull requests που έκανα στο [sitegr](https://github.com/ioniodi/sitegr/pull/299) και στο [all_collections](https://github.com/ioniodi/all_collections/pull/11) με σκοπό την διαμέριση της ιδέας που είχα με τη προσθήκη βιβλίων του μαθήματος της python και πραγματοποιώντας μόνο ένα απλό κομμάτι από τα δύο μέρη.
