### ISSUE TITLE
Ενημέρωση ωρολόγιου προγράμματος Β' Εξαμήνου

### ISSUE THREAD

**Issue by p17simt** [ioniodi/sitegr#235]
### Δήλωση Θέματος
- Ενημέρωση των πινάκων ωρολόγιου προγράμματος Β' Εξαμήνου
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p17papa @axilleasmandravelis
- Σχετικά θέματα: [Πρόγραμμα](https://epic-hamilton-da9ac8.netlify.app/timetables/sem_b/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p17simt** [comment]
Σε περίπτωση που χρειάζονται περαιτέρω λεπτομέρειες:
Σκοπός είναι να ενημερωθεί το ωρολόγιο πρόγραμμα κάθε έτους στην [αντίστοιχη σελίδα](https://epic-hamilton-da9ac8.netlify.app/timetables/)

**Comment by epidrome** [comment]
διάλεξε ένα μόνο εξάμηνο και ενημέρωσε τον τίτλο του θέματος σου

**Comment by p17simt** [comment]
Θα ενημερωθεί το ΩΠ Β' Εξαμήνου

**Comment by epidrome** [comment]
στα σχετικά θέματα βάλε τον σύνδεσμο προς την αντίστοιχη επίσημη σελίδα

πρόσθεςε κάποιους συναδέλφους που θα σχολιάσουν την συνεισφορά σου

**Comment by p17simt** [comment]
Ενημερώθηκε εκ νέου το issue. Αναμένω έγκριση για να ξεκινήσω!

**Comment by diogenisAl** [comment]
@p17simt θα πρέπει να πάρεις πρώτα την αξιολόγηση-έγκριση από τους @p17papa @axilleasmandravelis που αναφέρεις ως συνεργάτες

**Comment by axilleasmandravelis** [comment]
> * ωρολόγιου προγράμματος Β' Εξαμήνου
> * Εκτιμώμενη δυσκολία: easy

Μια χαρά μου μου φαίνεται η ιδέα.Απο εμένα υπάρχει έγκριση για να συνεχίσεις.

**Comment by p17papa** [comment]
Ειναι αρκετα ενδιαφερον κατα την γνωμη μου

**Comment by p17simt** [comment]
Επομένως @diogenisAl αναμένω green light απο εσάς ή το βάζω μόνη μου στο issue;
