### ISSUE TITLE
Προσθήκη "Πτυχιακής Εργασίας" στο Ζ' εξάμηνο.

### ISSUE THREAD

**Issue by p19kala** [ioniodi/sitegr#237]
### Δήλωση Θέματος
- Προσθήκη "πτυχιακής εργασίας" με όνομα αρχείου thesis.md στο υποχρεωτικό μάθημα του  Ζ' εξαμήνου. Οι αλλαγές θα γίνουν στο φάκελο [_courses](https://github.com/p19kala/all_collections/tree/2019017/_courses) και θα εμφανιστούν εδώ: [Ζ' εξαμηνο](https://p19kalasw.netlify.app/courses/#%CF%85%CF%80%CE%BF%CF%87%CF%81%CE%B5%CF%89%CF%84%CE%B9%CE%BA%CE%AC-%CE%BC%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%B1-6). Στο content, θα υπαρχει μια συντομη περιγραφή και ενα downloadable link όπως φαίνεται στο [live demo](https://p19kalasw.netlify.app/courses/thesis/), τα οποία πήρα από την επίσημη ιστοσελίδα [εδώ](https://di.ionio.gr/gr/studies/undergraduate-studies/undergaduate-thesis/). 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @KuhakuNeko
- Σχετικά θέματα: #204 #265

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
μερικές αλλαγές πριν γίνει δεκτό:

θα πρέπει να το ενημερώσεις με 
1. σχετικούς συνεργάτες που θα αξιολογήσουν το αίτημα σου, π.χ., κάποιον από την ομάδα σου
2. σχετικά θέματα-τεκμηρίωση-συνδέσμους, π.χ., πως είναι στην επίσημη;
3. τίτλο για ένα μόνο εξάμηνο, ώστε να κάνει κάποιος άλλο το άλλο εξάμηνο

**Comment by p19kala** [comment]
Πραγματοποιήθηκαν οι αλλαγές.

**Comment by diogenisAl** [comment]
@p19kala θα πρέπει ο @KuhakuNeko να γράψει τη γνώμη του

**Comment by KuhakuNeko** [comment]
@p19kala η πρόταση μια χαρά μου φαίνεται και το demo σου φαίνεται να δουλεύει. Βέβαια το κουμπί eclass με επιστρέφει στην σελίδα thesis ξανά. Αυτό μπορεί να είναι οκ διότι η πτυχιακή δεν είναι μάθημα στο eclass/open class, αλλά optimally μπορείς να το διορθώσεις ή να το αφαιρέσεις. Όλα οκ.

**Comment by p19kala** [comment]
Δεν μπορω να κανω αλλαγη στο κουμπι γιατι δεν μας αφηνει ο κ. Χωριανοπουλος να πειραξουμε το minimal-ionio στο 1ο pull request. Αν μπορουσα, θα το εβγαζα τελειως γιατι δεν εχει καποια σελιδα e-class να το συνδεσω.

**Comment by epidrome** [comment]
η προσθήκη της πτυχιακής ως μάθημα είναι προβληματική γιατί το σύστημα δεν υποστηρίζει μάθημα δύο εξαμήνων, επομένως θα πρέπει να μπει η ίδια πληροφορία δύο φορές, το οποίο είναι πολύ κακή πρακτική.

το ιδανικό θα ήταν το σύστημα να υποστήριζε μάθημα δύο εξαμήνων, αλλά αυτό είναι νέα λειτουργία και δεν ξέρω αν αξίζει να υλοποιηθεί στο 2ο παραδοτέο, για την περίπτωση της πτυχιακής μόνο.

όπως το καταλαβαίνω τώρα νομίζω πως η πτυχιακή θα πρέπει να προστεθεί είτε ως απλή σελίδα είτε μόνο στον οδηγό σπουδών και περισσότερο προτιμώ το τελευταίο

ποια είναι η γνώμη σας;

**Comment by p19kala** [comment]
> η προσθήκη της πτυχιακής ως μάθημα είναι προβληματική γιατί το σύστημα δεν υποστηρίζει μάθημα δύο εξαμήνων, επομένως θα πρέπει να μπει η ίδια πληροφορία δύο φορές, το οποίο είναι πολύ κακή πρακτική.
> 
> το ιδανικό θα ήταν το σύστημα να υποστήριζε μάθημα δύο εξαμήνων, αλλά αυτό είναι νέα λειτουργία και δεν ξέρω αν αξίζει να υλοποιηθεί στο 2ο παραδοτέο, για την περίπτωση της πτυχιακής μόνο.
> 
> όπως το καταλαβαίνω τώρα νομίζω πως η πτυχιακή θα πρέπει να προστεθεί είτε ως απλή σελίδα είτε μόνο στον οδηγό σπουδών και περισσότερο προτιμώ το τελευταίο
> 
> ποια είναι η γνώμη σας;

@epidrome 
Να σημειωσω οτι ησασταν ο πρωτος που το ειδε και μου ζητησατε να κανω καποιες σχετικες αλλαγες "πριν γινει δεκτο", τις οποιες εφαρμοσα. Εγιναν οι αξιολογησεις και προχωρησε σε green light. Αυτη η συζητηση επρεπε να γινει τοτε. Αυτο τωρα που γινεται για κατι τοσο μικρο (να υπαρχουν δυο πανομοιοτυπα αρχεια), **μετα** τη διορια ενω εχουμε και το 4ο παραδοτεο ειναι κακη οργανωση. 

Προχωροντας στο αιτημα, κι εγω πιστευω να δημιουργηθει μια απλη σελιδα μονο για τη πτυχιακη ειναι περιττο. Η πτυχιακη εργασια υπαρχει ηδη στον οδηγο σπουδων. Οποτε μου ζητατε να πεταξω τελειως το θεμα και να ψαξω κατι αλλο, μετα τη διορια και αφου εχουν σταλθει 70+ αιτηματα για αλλαγες το οποιο συνεπαγεται σε πολυ χρονο να βρω τι να αλλαξω. 

Η πτυχιακη θεωρειται "υποχρεωτικο μαθημα" βαση της επισημης ιστοσελιδας στο [προγραμμα σπουδων](https://di.ionio.gr/gr/studies/undergraduate-studies/curriculum/) για αυτο σκεφτηκα να τη βαλω στα αντιστοιχα εξαμηνα. Η προταση μου ειναι να μεινει οπως εχει στο Ζ' εξαμηνο. Αν καποια στιγμη βρεθει καποιος να δημιουργησει λειτουργια που θα δεχεται ενα μαθημα σε 2 εξαμηνα, θα λυθει και το προβλημα του Η' εξαμηνου.

**Comment by epidrome** [comment]
μην αγχώνεστε για την προθεσμία, αφού έχετε κάνει έγκαιρα αυτό το θέμα!

να αγχώνεστε μήπως χαλάσουμε αυτήν την ωραία συλλογική-διαχρονική δουλειά! για αυτό κάνουμε αυτήν την συζήτηση.

συνεχίζω να θεωρώ πως είναι κακή λύση, αλλά συμφωνώ μαζί σας ότι δεν είναι καταστροφική, ας  πούμε ότι είναι λίγο χακ, οπότε, ας το προχωρήσουμε όπως λέτε με αίτημα στο αποθετήριο των συλλογών

**Comment by CptMike** [comment]
> μην αγχώνεστε για την προθεσμία, αφού έχετε κάνει έγκαιρα αυτό το θέμα!
> 
> να αγχώνεστε μήπως χαλάσουμε αυτήν την ωραία συλλογική-διαχρονική δουλειά! για αυτό κάνουμε αυτήν την συζήτηση.
 
Σε αυτό έχετε δίκιο. Κρίμα να χαλάσει αυτή η διαδικασία. Καμία φορά εμπλέκεται και ο παράγοντας αγχος, καθώς έχουμε στο πίσω μέρος του κεφαλιού μας ότι όλο αυτό είναι μερος μαθήματος. 

Σας παρακαλώ δώστε και σε μένα ενα green light ώστε να προχωρήσω και εγώ #265
