### ISSUE TITLE
Αλλαγή καθηγητή του μαθήματος "Γραφικά με Υπολογιστές"

### ISSUE THREAD

**Issue by StavroulaAnatolaki** [ioniodi/sitegr#239]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Το μάθημα "Γραφικά με Υπολογιστές" τώρα δεν διδάσκεται από τον Φοίβο Μυλωνά, αλλά από τον Δημήτριο Ρίγγα.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: @DimitrisTzer
- Σχετικά θέματα:#242 #255 #256
- Γνώμη συνεργάτη: https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059802947

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2297217

**Comment by KuhakuNeko** [comment]
@StavroulaAnatolaki πιστεύω πως θα ήταν καλύτερο ο τίτλος να αλλάξει σε κάτι του τύπου "Αλλαγή του διδάκτορα του μαθήματος "Γραφικά με Υπολογιστές"" για να είναι πιο ξεκάθαρος με μία απλή ματιά. Επίσης πρέπει να κάνεις check και τα ανάλογα κουτάκια/tasks. Καλό θα ήταν, αν και δεν γνωρίζω κατά πόσο είναι υποχρεωτικό σε αυτό το παραδοτέο να προσθέσεις σχετικούς συνεργάτες και θέματα.

>Για τα θέματα ενδιάμεσης δυσκολίας στο 2ο-3ο αίτημα ενσωμάτωσης το ζητούμενο είναι μια συνεισφορά που δείχνει μεγαλύτερη κατανόηση του συστήματος, π.χ., βελτίωση της τεκμηρίωσης ή της διαδικασίας συνεισφοράς, προσθήκη νεών σελίδων με διάδραση-οπτική πάνω στα δεδομένα (π.χ., μαθήματα κατεύθυνσης), βελτιώσεις στον κώδικα λίκουηντ, κτλ.

Όσων αφορά την απορία σου οι οδηγίες λένε ότι πρέπει να κάνεις κάτι πιο δύσκολο από αυτό στο ανάλογο επόμενο παραδοτέο επομένως δεν νομίζω ότι θα ήταν καλή ιδέα να επιλέξεις πάλι παρόμοιο θέμα.

**Comment by StavroulaAnatolaki** [comment]
Καλημέρα.

Εχω εφαρμοσει τις αλλαγες που πρότεινες αλλα αναρωτιέμαι αν πρεπει να στειλω και το live demo, επειδή βλεπω πως εσυ δεν το εκανες αλλα καποια αλλα παιδια το εκαναν. Επισης δεν καταλαβαίνω αυτό με τους αξιολογητες τι είναι. Ο χρονος με πιεζει και δεν ξερω τι άλλο πρεπει να κανω για να παρω εγκριση. Εκανα ότι εκανες και εσυ και δεν φαινεται να του είναι αρκετο του καθηγητη.

**Comment by KuhakuNeko** [comment]
@StavroulaAnatolaki μπορεί απλά να μην το είδαν ακόμα.

Κάνεις λάθος ότι δεν έχω live demo. Το live demo μπαίνει στο pull request για να αποδείξεις ότι αυτά που έχεις κάνει δουλεύουν και αν πας στο [pull request μου](https://github.com/ioniodi/sitegr/pull/245) μπορείς να το δεις. Το netlify όμως κάνει από μόνο του ένα temporary deploy για το pull request σου έτσι και αλλιώς απλός ως "πολυτέλεια" μπορείς να βάλεις και ένα link προς το δικό σου site για να δείξεις ότι όλα είναι καλά με το pull request.

Επίσης δεν βλέπω να έχεις βάλει σχετικούς συνεργάτες που φαίνεται να είναι προϋπόθεση και για αυτό το παραδοτέο. Μου φάνηκε περίεργο διότι σε εμένα μου δόθηκε green light χωρίς να έχω συνεργάτες και κάπου είχε αναφερθεί ότι δεν είναι απολύτως απαραίτητο για το πρώτο παραδοτέο. Παρόλα αυτά καλύτερα να το κάνεις, κι εγώ το έκανα και ας είχα green light.

**Comment by diogenisAl** [comment]
@StavroulaAnatolaki θα πρέπει να γράψει τη γνώμη του και ο σχετικός συνεργάτης: @DimitrisTzer

**Comment by StavroulaAnatolaki** [comment]
Τη γνωμη του σχετικα με τι;

**Comment by diogenisAl** [comment]
@StavroulaAnatolaki τη γνώμη του σχετικά με τις αλλαγές που περιγράφεις στο παρόν issue

**Comment by DimitrisTzer** [comment]
Θεωρώ η @StavroulaAnatolaki έχει πραγματοποιήσει όλες τις απαραίτητες αλλαγές οι οποίες χρειαζόντουσαν και είναι ξεκάθαρη ποια θα είναι η συνεισφορά της. Επομένως θα μπορούσε να πάρει το green light για να προχωρήσει παρακάτω.

**Comment by StavroulaAnatolaki** [comment]
https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059799964
Μπορειτε τωρα να μου δωσετε το green light; Εκανα ολα τα απαραιτητα και βλεπω πως τα παιδια που πηραν ηδη το green light εκαναν λιγοτερα απο εμενα. Δεν θελω  να σας προσβάλω αλλα λιγο αδικος ειστε μαζι μου.

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό
2. σύνδεσμο προς την αντίστοιχη σελίδα στον επίσημο ιστότοπο
