### ISSUE TITLE
Εισαγωγή νέου μαθήματος επιλογής Β' εξαμήνου «Εφαρμοσμένος Προγραμματισμός με Python»

### ISSUE THREAD

**Issue by Haki-Malai** [ioniodi/sitegr#24]
### Δήλωση Θέματος
- Αλλαγές στο Πρόγραμμα Σπουδών
       - Εισαγωγή νέου μαθήματος επιλογής Β' εξαμήνου «Εφαρμοσμένος Προγραμματισμός με Python»
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
αρκεί να κάνεις ένα από αυτά, άσε και κάτι για τους άλλους!!
