### ISSUE TITLE
Προσθήκη της φωτογραφίας και του email του καθηγητή Σπυρίδωνος Δουκάκη 

### ISSUE THREAD

**Issue by voltmaister** [ioniodi/sitegr#240]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : προσθήκη της εικόνας doukakis.png και email παρμένα από την σελίδα του πανεπιστημίου, η αλλαγή έχει γίνει και για το doukakis αλλά και για το doukakis-en καθώς έγινε και ενημέρωση του bio στο αρχείο authors.yml .
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @KonstantinosTourtsakis @NickLitharis 
- Σχετικά θέματα: https://di.ionio.gr/gr/department/staff/577-doukakis/  email: sdoukakis@ionio.gr .παρόμοιο issue #243 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2297217

**Comment by voltmaister** [comment]
Παιδιά μπορεί κάποιος να μου πει πάνω κάτω τι έχω λάθος γιατί δεν μπορώ να καταλάβω.
Έχω βάλει πολλές αλλαγές; Έχω κάνει κάτι λάθος;

**Comment by KuhakuNeko** [comment]
- Ένα μικρό λάθος που δεν ξέρω αν είναι αυτό που σε κρατάει πίσω είναι ότι δεν έχεις κάνει check το τελευταίο box σχετικά με το green light.
- Θα μπορούσες να βάλεις και ως σχετικό θέμα το [243](https://github.com/ioniodi/sitegr/issues/243) που είναι παρόμοιο.
- Για μέγιστη αναγνωσιμότητα, αν και δεν το κρίνω αναγκαίο, ο τίτλος μπορεί να μικρύνει σε "Προσθήκη φωτογραφίας και email στον καθηγητή Σπυρίδωνα Δουκάκη".
- Δεν νομίζω ότι είναι πολλές οι αλλαγές, όπως το βλέπω 1 φώτο θα είναι και το authors.md. Ίσως και το _people.    ¯\\\_(ツ)_/¯

**Comment by NickLitharis** [comment]
Πρέπει να τσεκάρεις το τελευταίο κουτάκι και να δηλώσεις κάποια απο τα υπόλοιπα issues που είναι σχετικά με το δικό σου.

**Comment by diogenisAl** [comment]
@voltmaister πρόσθεσε και το link με την σελίδα-πρότυπο που έχει ήδη την φωτογραφία και το e-mai του Δουκάκη

**Comment by KonstantinosTourtsakis** [comment]
Ο συνάδελφος φαίνεται να έχει πραγματοποιήσει τις απαραίτητες αλλαγές που επισημάνθηκαν στα υπόλοιπα σχόλια και θεωρώ πως είναι έτοιμος για το green light.

**Comment by diogenisAl** [comment]
ο @NickLitharis εγκρίνει τις αλλαγές;

**Comment by NickLitharis** [comment]
Συνάδελφε είσαι έτοιμος να προχωρήσεις 👌

**Comment by epidrome** [comment]
πράγματι οι αλλαγές είναι δύο, γιατί όχι μόνο μία αφού αρκεί;

δεν επιμένω, αλλά με δύο αλλαγές αυξάνεται η πιθανότητα λάθους στο αίτημα ενσωμάτωσης με δικιά σας ευθύνη.
