### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα Λογικός Προγραμματισμός (logic-programming.md)

### ISSUE THREAD

**Issue by fireleaf22** [ioniodi/sitegr#242]
Αλλαγή καθηγητή στο μάθημα Λογικός Προγραμματισμός
- Αλλαγή στο παιδίο author, θα γίνει αλλαγή του καθηγητή Δημήτριος Ρίγγας με τον καθηγητή Αθανάσιος Τσίπης,στο μάθημα Λογικός Προγραμματισμός (logic-programming)
- Εκτιμώμενη δυσκολία:very easy
- Σχετικοί συνεργατές:  @KuhakuNeko @p19kala
- Σχετικά θέματα:  #https://github.com/ioniodi/sitegr/issues/239#issue-1159639853  #https://github.com/ioniodi/sitegr/issues/255#issue-1160293182  #https://github.com/ioniodi/sitegr/issues/256#issue-1160300240

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2297217

ποιος είναι ο νέος καθηγητής; σε ποια σελίδα του επίσημου τον βρήκες; ποιους θα καλέσεις να σχολιάσουν την αλλαγή;

**Comment by diogenisAl** [comment]
@fireleaf22 συνιστούμε να συμπληρωθεί και το πεδίο **Σχετικοί συνεργάτες**

**Comment by fireleaf22** [comment]
> [courses-ionio/sw#1042 (comment)](https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2297217)
> 
> ποιος είναι ο νέος καθηγητής; σε ποια σελίδα του επίσημου τον βρήκες; ποιους θα καλέσεις να σχολιάσουν την αλλαγή;

Από δικιά μου γνώση καθώς παρακολούθησα και έδωσα το συγγεκρημένο μάθημα το εξάμηνο που πέρασε καθώς και σύνφωνα με την σελίδα του μαθήματος στο [opencourses](https://opencourses.ionio.gr/courses/DDI206/) βλέπεται ότι το μάθημα πλέον το κάνει ο κύριος Τσίπης και όχι ο κύριος Ρίγγας.

**Comment by KuhakuNeko** [comment]
@fireleaf22 μια χαρά μου φαίνεται η πρότασή σου σε τίτλο και περιγραφή και φαντάζομαι πως το opencourses είναι επαρκής αποδεικτικό για την αλλαγή. Επομένως όλα οκ.

**Comment by p19kala** [comment]
Καλο φαινεται. Μην ξεχασεις να διαγραψεις την τελευταια υπενθυμιση στο post η οποια ειναι για το 2ο pull request.

**Comment by fireleaf22** [comment]
@diogenisAl Καλησπέρα, βλέπω ότι δεν μου έχει δοθεί ακόμα το green light, ενώ έχω κάνει ότι ζητήθηκε.

**Comment by epidrome** [comment]
υπάρχει ασυνέπεια ανάμεσα στον τίτλο και στις αλλαγές που είναι πολλές και διάφορες.

αν ο καθηγητής δεν υπάρχει θα πρέπει να προστεθεί αλλά αυτό είναι ένα νέο διακριτό θέμα.

αφού προστεθεί ο καθηγητής τότε μπορεί να ανοίξει το νέο θέμα για την αλλαγή των μαθημάτων, από κάποιον άλλο.
