### ISSUE TITLE
Αλλαγή της βαθμίδας της Κ.Πατέλη

### ISSUE THREAD

**Issue by Stavros16** [ioniodi/sitegr#247]
### Δήλωση Θέματος
Αλλαγή βαθμίδας της καθηγήτριας Πατέλη από αναπληρώτρια σε καθηγήτρια.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @ApoLaz @p17anto2
- Σχετικά θέματα: #243 

[Link στην επίσημη ιστοσελίδα](https://di.ionio.gr/gr/department/staff/professors/) όπου φαίνεται η ανάγκη για την αλλαγή.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by StavroulaAnatolaki** [comment]
Καλύτερα να αναφέρεις πως το #242 έχει το ίδιο θέμα με εσένα

**Comment by diogenisAl** [comment]
@Stavros16 επίσης να συμπληρώσεις το πεδίο "σχετικοί συνεργάτες"

**Comment by ApoLaz** [comment]
Ωραία παρατήρηση και εγώ μια παρόμοια παραμετροποίηση θα εκτελέσω

**Comment by epidrome** [comment]
πρέπει να δώσεις και σχετικό σύνδεσμο στην επίσημη ιστοσελίδα όπου τεκμηριώνεται η αλλαγή που προτείνεις

θέλουμε τουλάχιστον δύο αξιολογητές

παρατηρώ ότι αρκετοί βάζουν μόνον έναν, 

κάντε μια αναζήτηση θα βρείτε αρκετούς που δουλεύουν σχετικά θέματα και μπορούν να σας βοηθήσουν

έτσι ίσως προχωρήσουμε και πιο γρήγορα..

**Comment by Stavros16** [comment]
@epidrome Ευχαριστώ για τη διευκρίνηση. Έκανα τις απαραίτητες αλλαγές.

**Comment by p17anto2** [comment]
Καλή παρατήρηση, από εμένα όλα οκ
