### ISSUE TITLE
Προσθήκη Ανακοίνωσης "Μεταπτυχιακοί φοιτητές δικαιούχοι δωρεάν σίτισης ακαδ.έτους 2021-2022, τμημάτων με έδρα την Κέρκυρα"

### ISSUE THREAD

**Issue by AimiliosPavlidis2001** [ioniodi/sitegr#248]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Προσθήκη Ανακοίνωσης "Μεταπτυχιακοί φοιτητές δικαιούχοι δωρεάν σίτισης ακαδ.έτους 2021-2022, τμημάτων με έδρα την Κέρκυρα"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19pasc , @u2nmd
- Σχετικά θέματα: https://di.ionio.gr/gr/news/23404/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
στα σχετικά θέματα βάλε τον σύνδεσμο προς την αντίστοιχη επίσημη σελίδα

πρόσθεσε δύο συναδέλφους που θα σχολιάσουν την συνεισφορά σου

**Comment by AimiliosPavlidis2001** [comment]
> στα σχετικά θέματα βάλε τον σύνδεσμο προς την αντίστοιχη επίσημη σελίδα
> 
> πρόσθεσε δύο συναδέλφους που θα σχολιάσουν την συνεισφορά σου

@epidrome @diogenisAl οι αλλαγές υλοποιήθηκαν

**Comment by p19pasc** [comment]
Υπάρχει μεγάλη έλλειψη στις ανακοινώσεις, ειδικά σε σημαντικά θέματα όπως αυτό που αναμένεις να αναρτήσεις μόλις λάβεις green light. Πιστεύω δεν θα υπάρξει κανένα πρόβλημα στο pull request!

**Comment by u2nmd** [comment]
Ανακοινώσεις σαν αυτές άλλοτε χάνονται και άλλοτε δεν ανεβαίνουν στην σελίδα του πανεπιστημίου, επομένως η συνεισφορά σου θα είναι σημαντική!
