### ISSUE TITLE
Προσθήκη του Κ. Βόγκλη ως Ακαδημαϊκό Υπότροφο

### ISSUE THREAD

**Issue by p17anto2** [ioniodi/sitegr#249]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη του Κ. Βόγκλη ως Ακαδημαϊκό Υπότροφο στη σελίδα [Προσωπικό](https://epic-hamilton-da9ac8.netlify.app/people/).
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές:   @john7665 @ApoLaz
- Σχετικά θέματα: [di.ionio/academic-scholars](https://di.ionio.gr/gr/department/staff/academic-scholars/) #257  #253 #230 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p17anto2 θα πρέπει να συμπληρώσεις όλες τις πληροφορίες στο 1o post

**Comment by ApoLaz** [comment]
Πολύ σωστή η παρατήρηση σου. Εμένα μου είχε διαφύγει τελείως ότι λείπει ο κύριος Βόγλης από την λίστα με των Ακαδημαϊκών Υπότροφων. Από εμένα έχεις το οκ να προχωρήσεις .

**Comment by john7665** [comment]
Πολύ ωραια.Ναι από εμένα!

**Comment by p17anto2** [comment]
@diogenisAl έχω κάνει τις αλλαγές, αναμένω green light
