### ISSUE TITLE
Αφαίρεση εργαστηρίου "QUITLab"

### ISSUE THREAD

**Issue by john7665** [ioniodi/sitegr#250]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Αφαίρεση "Εργαστήριο Κβαντικών και μή Συμβατικών Υπολογισμών(QUITLab)" από την κατηγορία των εργαστηρίων  και από το footer της ιστοσελίδας. [page link](https://epic-hamilton-da9ac8.netlify.app/groups/) 
Συνδεσμος αρχικής πληροφορίας: [di.ionio.gr](https://di.ionio.gr/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p17anto2 @IonianIronist
- Σχετικά θέματα: #187 #183 #233

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@john7665 θα πρέπει να ακολουθήσεις τις οδηγίες προκειμένου να γίνει δεκτό το pull request

**Comment by p17anto2** [comment]
Από εμένα έχεις το οκ!

**Comment by diogenisAl** [comment]
@john7665 χρειάζεσαι [τουλάχιστον 2](https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059960377) συνεργάτες

**Comment by IonianIronist** [comment]
Και εμένα μια χαρά μου φαίνεται!
