### ISSUE TITLE
Προσθήκη Μαθήματος Επιλογής <<Κατανεμημένα Δικτυοκεντρικά Συστήματα>> στο ΣΤ' Εξάμηνο

### ISSUE THREAD

**Issue by p19pasa** [ioniodi/sitegr#251]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Παρατηρήσαμε ότι λείπει από το πρόγραμμα σπουδών ΣΤ' Εξαμήνου το μάθημα επιλογής  <<Κατανεμημένα Δικτυοκεντρικά Συστήματα>>, που διδάσκουν ο κ. Οικονόμου και η κ. Χριστοπούλου και θα θέλαμε να το προσθέσουμε. Η αλλαγή θα γίνει μέσω του [submodule](https://github.com/ioniodi/all_collections/tree/master/_courses).
-  Αντίστοιχη σελίδα στον επίσημο ιστότοπο: [Κατανεμημένα Δικτυοκεντρικά Συστήματα](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/620/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19verg @PetroulaStylianou
- Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/254

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p19pasa θα πρέπει να ενημερωθεί καλύτερα ο τίτλος και τα πεδία του 1ου post

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό
2. σύνδεσμο προς την αντίστοιχη σελίδα στην επίσημη σελίδα

**Comment by p19verg** [comment]
@p19pasa Ωραίο σαν θέμα, απλά να σιγουρευτουμε να βάλουμε τα κατάλληλα πεδία στο all_collections

**Comment by PetroulaStylianou** [comment]
@p19pasa Πολύ καλή παρατήρηση!!
