### ISSUE TITLE
Προσθήκη περιγραφής στο μάθημα Βιοπληροφορική ΣΤ' Εξαμήνου

### ISSUE THREAD

**Issue by u2nmd** [ioniodi/sitegr#252]
### Δήλωση Θέματος
- Το μάθημα της Βιοπληροφορικής δεν έχει περιγραφή για το ΣΤ' εξάμηνο αλλά για το μεταπτυχιακό έχει (είναι το ίδιο μάθημα τόσο στο ΣΤ΄ εξάμηνο όσο και στο μεταπτυχιακό). Επομένως, θέλω να προσθέσω την αντίστοιχη περιγραφή στο μάθημα.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19pasc @AimiliosPavlidis2001
- Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/71, [Βιοπληροφορική στον επίσημο ιστότοπο](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/750/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@u2nmd θα πρέπει να συμπληρωθούν όλα τα πεδία του 1ου post

**Comment by u2nmd** [comment]
> @u2nmd θα πρέπει να συμπληρωθούν όλα τα πεδία του 1ου post

Εκανα την συμπλήρωση και περιμένω green light.

**Comment by p19pasc** [comment]
Η περιγραφή του κάθε μαθήματος είναι σημαντική καθώς αναφέρει το περιέχομενο της διδασκαλίας κατά τη διάρκεια του εξαμήνου. Καλή επιλογή.

**Comment by AimiliosPavlidis2001** [comment]
Η προσθήκη που επιθυμείς να κάνεις στην ιστοσελίδα είναι ιδιαιτέρως σημαντική αφού οι προπτυχιακοί φοιτητές οφείλουν να γνωρίζουν το περιεχόμενο του μαθήματος.

**Comment by epidrome** [comment]
σύνδεσμο προς την αντίστοιχη σελίδα στον επίσημο ιστότοπο;
