### ISSUE TITLE
Προσθήκη καθηγητή Αθανάσιου Τσίπη στο προσωπικό

### ISSUE THREAD

**Issue by p19ntar** [ioniodi/sitegr#253]
### Δήλωση Θέματος
- Θα προσθέσω στους [Ακαδημαϊκούς Υπότροφους](https://epic-hamilton-da9ac8.netlify.app/people/) του τμήματος τον καθηγητή [Αθανάσιο Τσίπη](https://eliki.ionio.gr/~okon/?page_id=842) 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19biza @Mnlsvt
- Σχετικά θέματα: #230 , απ΄ ό,τι βλέπω ούτε στην επίσημη σελίδα είναι περασμένος μάλλον επειδή είναι νέος στο τμήμα και δεν έχουν γίνει ούτε εκεί οι αλλαγές, αλλά καθώς διδάσκει το μάθημα τεχνολογίες διαδικτύου του ΣΤ εξαμήνου και σύμφωνα με το [βιογραφικό](https://eliki.ionio.gr/~okon/?page_id=842) του είναι ακαδημαϊκός υπότροφος του τμήματος.
</br>

- [Η προσθήκη μου](https://github.com/p19ntar/all_collections/blob/f1e101bd8704a3d66f472be40a43400894809019/_people/atsipis.md)
- [Demo](https://p2019215.netlify.app/people/atsipis/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by StavroulaAnatolaki** [comment]
Θα ήταν καλή ιδέα να πεις πιο μάθημα διδάσκει αυτός ο καθηγητής

**Comment by diogenisAl** [comment]
@p19ntar και να συμπληρώσεις στο 1ο post τα αντίστοιχα πεδία (π.χ. Σχετικοί συνεργατές, Σχετικά θέματα) σύμφωνα με το αρχικό πρότυπο.

**Comment by p19ntar** [comment]
@diogenisAl οι αλλαγές έγιναν, πιστεύω πως δεν λείπει κάτι τώρα

**Comment by Mnlsvt** [comment]
Κι εγω πιστευω πως η παρατηση του @p19ntar ειναι σωστη

**Comment by p19biza** [comment]
Η προσθήκη του @p19ntar στο site του Ιονίου μου φαίνεται ορθή.

**Comment by p19ntar** [comment]
@epidrome @diogenisAl Έγιναν οι αλλαγές και οι αξιολογήσεις από τους συνεργάτες μου, πιστεύω πως είναι έτοιμο για green light

**Comment by p19ntar** [comment]
Το [pull request](https://github.com/ioniodi/all_collections/pull/8) στο all_collections
