### ISSUE TITLE
Αλλαγή του καθηγητή στο μάθημα "Λειτουργικά Συστήματα"

### ISSUE THREAD

**Issue by Geoter711** [ioniodi/sitegr#255]
### Δήλωση Θέματος
- Θα χρειαστεί να αλλάξω τον καθηγητή του μαθήματος. Οι αλλαγές θα γίνουν στο https://github.com/ioniodi/all_collections και οι πληροφορίες είναι από https://di.ionio.gr/gr/studies/undergraduate-studies/courses/604/
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @PeteSKK @xar1sgeovlacp2019059 
- Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/242 https://github.com/ioniodi/sitegr/issues/239 https://github.com/ioniodi/sitegr/issues/267 https://github.com/ioniodi/sitegr/issues/260

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@Geoter711 θα πρέπει να συμπληρωθεί και το πεδίο "Σχετικοί συνεργατές"

**Comment by Geoter711** [comment]
Πραγματοποιηθήκε η αλλαγή! @diogenisAl

**Comment by diogenisAl** [comment]
@diogenisAl τώρα περιμένεις την αξιολόγηση/έγκριση από τους @PeteSKK @xar1sgeovlacp2019059
Παράλληλα, πρόσθεσε και το link με την πληροφορία στην επίσημη ιστοσελίδα.

**Comment by PeteSKK** [comment]
Κανένα πρόβλημα από εμένα, συνέχισε έτσι

**Comment by xar1sgeovlacp2019059** [comment]
Δεν υπάρχει πρόβλημα .Μπορείς να συνεχίσεις

**Comment by Geoter711** [comment]
@diogenisAl Φαντάζομαι τώρα είναι μια χαρά

**Comment by epidrome** [comment]
@Geoter711 γιατί το έκλεισες; θα κλείσει μόνο του όταν/αν γίνει δεκτό το αίτημα σου.

**Comment by Geoter711** [comment]
@epidrome Όπως είχα αναφέρει και στην αναφορά μου, ανέβασα αυτό το issue αλλά ύστερα συνειδητοποίησα ότι δεν είναι εφικτό. Συγκεκριμένα, για την ολοκλήρωση του issue, ήταν αναγκαία η ολοκλήρωση άλλου issue πρώτα (https://github.com/ioniodi/sitegr/issues/257) το οποίο ακόμα δεν έχει γίνει δεκτό, άρα εγώ δεν μπορώ να προχωρήσω στις αλλαγές που ήθελα να πραγματοποιήσω. Οπότε αποφάσισα ότι θα ήταν καλύτερο να ανοίξω καινούριο issue παρά να περιμένω να γινεί δεκτό το παραπάνω, να γίνει και το pull request δεκτό και μετά να κάνω τις δικές μου αλλαγές.
