### ISSUE TITLE
Αλλαγή του καθηγητή στο μάθημα "Δομές Δεδομένων"

### ISSUE THREAD

**Issue by NickLitharis** [ioniodi/sitegr#256]
### Δήλωση Θέματος
- Προσθήκη της κ. Σωτηροπούλου ως καθηγήτριας στο μάθημα "Δομές Δεδομένων" 
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αλλαγή στο αρχείο **all_collections/_courses/data-stractures.md**. Οι διορθώσεις έγιναν σύμφωνα με τα δεδομένα που δίνονται στην επίσημη [ιστοσελίδα του τμήματος](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/584/).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @voltmaister,@KonstantinosTourtsakis
- Σχετικά θέματα: [Αλλαγή του καθηγητή στο μάθημα "Λειτουργικά Συστήματα" #255](https://github.com/ioniodi/sitegr/issues/242), [Αλλαγή του διδάκτορα του μαθήματος "Γραφικά με Υπολογιστές" #239](https://github.com/ioniodi/sitegr/issues/239), [Αλλαγή καθηγητή στο μάθημα Λογικός Προγραμματισμός (logic-programming.md) #242](https://github.com/ioniodi/sitegr/issues/242)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by StavroulaAnatolaki** [comment]
Μπορω να συνεργαστω μαζι σας;

**Comment by Geoter711** [comment]
Μερικά από τα link που έχεις βάλει δείχνουν σε λάθος σημεία! Νομίζω θες αυτά! https://github.com/ioniodi/sitegr/issues/255 https://github.com/ioniodi/sitegr/issues/239 https://github.com/ioniodi/sitegr/issues/242

**Comment by voltmaister** [comment]
το τελευταίο task νομίζω δεν χρειάζεται όπως έχει απαντηθεί απο τον ίδιο τον καθηγητή στο  #228 στο πρωτο comment νομίζω είναι.

**Comment by diogenisAl** [comment]
@NickLitharis θα χρειατούμε και τον σύνδεσμο της σελίδας με την αρχική πληροφορία.

**Comment by NickLitharis** [comment]
Οι αλλαγές ολοκληρώθηκαν

**Comment by epidrome** [comment]
> Οι αλλαγές ολοκληρώθηκαν

ο σύνδεσμος δεν οδηγεί στην επίσημη ιστοσελίδα αλλά στο δικό σου αντίγραφο

**Comment by NickLitharis** [comment]
Αλλαγή συνδέσμου στην σελίδα του τμήματος

**Comment by diogenisAl** [comment]
Στο αρχικό post παραπάνω, ο σύνδεσμος θα πρέπει να οδηγεί στην επίσημη ιστοσελίδα του τμήματος, όχι στο [https://epic-hamilton-da9ac8.netlify.app/](https://epic-hamilton-da9ac8.netlify.app/).

**Comment by diogenisAl** [comment]
στην επίσημη ιστοσελίδα του τμήματος **με την πληροφορία**

**Comment by NickLitharis** [comment]
Έτοιμη η αλλαγή.
