### ISSUE TITLE
Προσθήκη καθηγητή Άννα Σωτηροπούλου

### ISSUE THREAD

**Issue by perikarananou** [ioniodi/sitegr#257]
### Δήλωση Θέματος
- Θα προσθέσω στα members την καθηγήτρια Άννα Σωτηροπούλου
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές:  @Vivikara @fireleaf22
- Σχετικά θέματα:  https://github.com/ioniodi/sitegr/issues/249 , https://github.com/ioniodi/sitegr/issues/230 , https://github.com/ioniodi/sitegr/issues/272 [επίσημος ιστότοπος](https://di.ionio.gr/gr/department/staff/490-sotiropoulou/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@perikarananou θα πρέπει να συμπληρωθούν και το πεδίο **Σχετικοί συνεργατές** (που θα πρέπει να αξιολογήσουν την πρότασή σου) και το **Σχετικά θέματα**

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό
2. σύνδεσμο προς την αντίστοιχη σελίδα στον επίσημο ιστότοπο

**Comment by vivikara** [comment]
Φαίνεται ότι όλα είναι σύμφωνα με τις οδηγίες, δεν έχω να προσθέσω κάτι πολύ καλή η παρατήρηση σου! @perikarananou

**Comment by fireleaf22** [comment]
Πιστεύω πως είναι ολοκληρομένη η πρόταση σύμφωνα με τις οδηγίες.
