### ISSUE TITLE
Προσθήκη επιλογής στους χρήσιμους συνδέσμους για μεταφορά στο main site του πανεπιστημίου

### ISSUE THREAD

**Issue by gordthrow** [ioniodi/sitegr#258]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Προσθήκη στους χρήσιμους συνδέσμους μία επιλογή ώστε ο χρήστης να μεταφερθεί στο κύριο site του πανεπιστημίου
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @alexpoulis @xar1sgeovlacp2019059 @PeteSKK
- Σχετικά θέματα:https://github.com/ioniodi/sitegr/issues/261

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@gordthrow συνιστούμε να γίνει ο τίτλος πιο περιεκτικός και να συμπληρωθεί και το **Σχετικά θέματα**.
Επίσης, θα πρέπει ο @alexpoulis να αξιολογήσει το παρόν issue.

**Comment by gordthrow** [comment]
> @gordthrow συνιστούμε να γίνει ο τίτλος πιο περιεκτικός και να συμπληρωθεί και το **Σχετικά θέματα**. Επίσης, θα πρέπει ο @alexpoulis να αξιολογήσει το παρόν issue.

διόρθωσα αυτά που μου αναφέρατε και περιμένω την αξιολόγηση του συμφοιτητή μου.

**Comment by alexpoulis** [comment]
> > @gordthrow συνιστούμε να γίνει ο τίτλος πιο περιεκτικός και να συμπληρωθεί και το **Σχετικά θέματα**. Επίσης, θα πρέπει ο @alexpoulis να αξιολογήσει το παρόν issue.
> 
> διόρθωσα αυτά που μου αναφέρατε και περιμένω την αξιολόγηση του συμφοιτητή μου.

Μια χαρά φαίνεται το issue και πρόσθεσες και τα «Σχετικά θέματα» που έλειπαν οπότε δεν βλέπω κάποιο πρόβλημα.

**Comment by epidrome** [comment]
Το σχετικό θέμα δεν φαίνεται σχετικό..

**Comment by gordthrow** [comment]
@epidrome έβαλα ένα πιο σχετικό θέμα και πρόσθεσα δύο extra αξιολογιτές, τώρα περιμένω την αξιολόγησή τους

**Comment by xar1sgeovlacp2019059** [comment]
Απ'ότι βλέπω φαίνεται ένταξη. Συνέχισε

**Comment by PeteSKK** [comment]
Ούτε ένα θέμα, μια χαρά
