### ISSUE TITLE
Διόρθωση URL στο μάθημα Αλγόριθμοι 

### ISSUE THREAD

**Issue by p17siol** [ioniodi/sitegr#259]
### Δήλωση Θέματος
- Σκοπέυω να αλλάξω σε σωστό URL το λινκ του μαθήματος [Αλγόριθμοι](https://github.com/ioniodi/all_collections/blob/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_courses/algorithms.md), βλέπουμε οτι μας πάει στο πάλιο περιβάλλον e-class ενω θα έπρεπε να πηγαίνει στο καινούργιο περιβάλλον open-courses
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @[p17meli](https://github.com/p17meli)
- Σχετικά θέματα:  https://opencourses.ionio.gr/courses/DDI118/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p17siol θα πρέπει να συμπληρωθούν τουλάχιστον τα πεδία **Σχετικοί συνεργατές** και **Σχετικοί συνεργατές**

**Comment by p17siol** [comment]
@diogenisAl  Διόρθωσα την δήλωση !

**Comment by p17siol** [comment]
@diogenisAl  Επίσης για κάποιο λόγο δεν με αφήνει να αλλάξω label, δεν ξέρω αν κάνω κατι λάθος εγώ αλλα είναι σαν να μην έχω το δικαίωμα

**Comment by diogenisAl** [comment]
@p17siol κάνε τις απαραίτητες προσαρμογές σύμφωνα με αυτό το σχόλιο: [https://github.com/courses-ionio/help/discussions/292#discussioncomment-2301764](https://github.com/courses-ionio/help/discussions/292#discussioncomment-2301764)
