### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα προγραμματισμός υπολογιστών 

### ISSUE THREAD

**Issue by xar1sgeovlacp2019059** [ioniodi/sitegr#260]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Η αλλαγή αφορά την αντικατάσταση του καθηγητή Θεώδουρου Ανδρόνικου με τον καθηγητή Κωσταντίνο Βόγγλη, στο μάθημα Προγραμματισμός υπολογιστών του δεύτερου εξαμήνου. Οι αλλαγές θα γίνουν: https://github.com/ioniodi/all_collections , σύμφωνα με : https://di.ionio.gr/gr/studies/undergraduate-studies/courses/583/ .
- Εκτιμώμενη δυσκολία: easy 
- Σχετικοί συνεργατές: @Geoter711, @PeteSKK
- Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/239 https://github.com/ioniodi/sitegr/issues/267 https://github.com/ioniodi/sitegr/issues/300

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@xar1sgeovlacp2019059 θα πρέπει να γίνουν τουλάχιστον τα εξής:
* να γίνει ο τίτλος πιο αναλυτικός
* να συμπληρωθεί το πεδίο **Σχετικοί συνεργατές** (οι οποίοι θα γράψουν τη γνώμη τους για τις προτεινόμενες αλλαγές)
* να συμπληρωθεί το πεδίο **Σχετικά θέματα**

**Comment by Geoter711** [comment]
Ωραίος! Συνέχισε έτσι!

**Comment by xar1sgeovlacp2019059** [comment]
> @diogenisAl Πιστεύω έχω κάνει τις απαραίτητες αλλαγές.

**Comment by diogenisAl** [comment]
@xar1sgeovlacp2019059 θα χρειαστείς και 2ο συνεργάτη/αξιολογητή: [https://github.com/courses-ionio/help/discussions/292#discussioncomment-2297252](https://github.com/courses-ionio/help/discussions/292#discussioncomment-2297252)

**Comment by PeteSKK** [comment]
Τελειοτατα, έχεις το οκ μου

**Comment by xar1sgeovlacp2019059** [comment]
@diogenisAl Μήπως λείπει κάτι ακόμα ;
