### ISSUE TITLE
Αλλαγή Gram-Web σε Dias στην αρχική του Site

### ISSUE THREAD

**Issue by Tsimpliarakis** [ioniodi/sitegr#261]
### Δήλωση Θέματος
- Στην αρχική του Site στο footer λέει ακόμα gram-web ενώ το πανεπιστήμιο έχει μεταφερθεί στο dias.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19tzam @Alkissourvinos @makisgrammenos
- Σχετικά θέματα: https://dias.ionio.gr/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Tsimpliarakis θα πρέπει:
* να συμπληρωθεί το πεδίο **Σχετικά θέματα**
* να αξιολογήσουν την προτεινόμενη αλλαγή και οι σχετικοί συνεργάτες

**Comment by Alkissourvinos** [comment]
Πολύ καλή παρατήρηση @Tsimpliarakis. Δεν έχω να προσθέσω κάτι από εμένα προχωράς κανονικά

**Comment by p19tzam** [comment]
Κάτι απλό σαν αλλαγή και σωστό όπως χρειάζεται pull requests είναι το επόμενο βήμα.

**Comment by Tsimpliarakis** [comment]
> @Tsimpliarakis θα πρέπει:
> * να συμπληρωθεί το πεδίο **Σχετικά θέματα**
> * να αξιολογήσουν την προτεινόμενη αλλαγή και οι σχετικοί συνεργάτες

@diogenisAl Done ✅

**Comment by makisgrammenos** [comment]
Σωστή παρατήρηση συνάδελφε, προχώρα σε pull request
