### ISSUE TITLE
Αλλαγη Βαθμίδας  καθηγητή  Χρυσικόπουλου Βασίλειου

### ISSUE THREAD

**Issue by makisgrammenos** [ioniodi/sitegr#262]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:Αλλαγη Βαθμίδας καθήγητη "Χρυσικόπουλου Βασίλειου"
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @p19tzam @tsimpliarakis 
- Σχετικά θέματα: di.ionio.gr ,https://di.ionio.gr/gr/department/staff/111-chrissikopoulos/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by ApoLaz** [comment]
Στο "Σχετικοί συνεργάτες " καλό θα ήταν να κάνει mention κάποιον συνάδελφο που θα σχολιάσει την συνεισφορά σου

**Comment by Tsimpliarakis** [comment]
Συνάδελφε βάλε στο σχετικά θέματα το αντίστοιχο λινκ από το di.ionio.gr που φαίνεται η αλλαγή.

Επίσης αν μπορείς κλείσε το 2ο issue.

Κατά τα άλλα σωστή παρατήρηση!

**Comment by p19tzam** [comment]
Μόλις κλίσεις το άλλο issue θα πάρεις greenlight και είσαι έτοιμος με τα changes σου

**Comment by makisgrammenos** [comment]
Done

**Comment by makisgrammenos** [comment]
> Συνάδελφε βάλε στο σχετικά θέματα το αντίστοιχο λινκ από το di.ionio.gr που φαίνεται η αλλαγή.
> 
> Επίσης αν μπορείς κλείσε το 2ο issue.
> 
> Κατά τα άλλα σωστή παρατήρηση!

done

**Comment by makisgrammenos** [comment]
@diogenisAl Έκανα τις αλλαγές. Περιμένω green light
