### ISSUE TITLE
Αλλαγη Βαθμίδας  καθηγητή  Χρυσικόπουλου Βασίλειου

### ISSUE THREAD

**Issue by makisgrammenos** [ioniodi/sitegr#263]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:Αλλαγη Βαθμίδας καθήγητη "Χρυσικόπουλου Βασίλειου"
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [ Χ] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [ Χ] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [ Χ] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p19ntar** [comment]
Νομίζω έχεις ανοίξει καταλάθος δύο issues καθώς είναι ανοιχτό και το #262 που είναι ίδιο
