### ISSUE TITLE
Αλλαγή στο προφίλ καθηγητή Θεμιστοκλή Έξαρχου - πρόσθεση μαθήματος Αποθήκες Δεδομένων και Εξόρυξη Γνώσης

### ISSUE THREAD

**Issue by mariosconsta** [ioniodi/sitegr#264]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:
 Θα προσθέσω το μάθημα Αποθήκες Δεδομένων και Εξόρυξη Γνώσης. Η αλλαγή θα γίνει στο [_courses](https://github.com/mariosconsta/all_collections/tree/2015002/_courses). Το Live Demo είναι [εδώ](https://site-demo-2015002.netlify.app/people/exarchos/) και οι πληροφορίες πάρθηκαν από [εδώ](https://di.ionio.gr/en/department/staff/572-exarchos/).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @CptMike και @p17meli
- Σχετικά σύνδεσμοι: https://github.com/ioniodi/sitegr/issues/262

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by CptMike** [comment]
Σαν θέμα όντως χρήζει διόρθωσης και τα λινκς λειτουργούν αποτελεσματικά.

**Comment by mariosconsta** [comment]
> Σαν θέμα όντως χρήζει διόρθωσης και τα λινκς λειτουργούν αποτελεσματικά.

Ευχαριστώ! Μου έμειναν κάποιες λεπτομέρειες, αλλά μέχρι αύριο θα το έχω έτυμο και αν πάρω το πράσινο φως θα κάνω το pull request!

**Comment by epidrome** [comment]
θέλουμε τουλάχιστον δύο αξιολογητές

παρατηρώ ότι αρκετοί βάζουν μόνον έναν, 

κάντε μια αναζήτηση θα βρείτε αρκετούς που δουλεύουν σχετικά θέματα και μπορούν να σας βοηθήσουν

έτσι ίσως προχωρήσουμε και πιο γρήγορα..

**Comment by mariosconsta** [comment]
@p17meli σας έχω προσθέσει ως αξιολογητή όπως ορίζουν οι οδηγίες.

**Comment by epidrome** [comment]
ζητάς πολλές αλλαγές αρκεί να κάνεις μόνο μια, άσε και κάτι για τους άλλους! :)

**Comment by mariosconsta** [comment]
> ζητάς πολλές αλλαγές αρκεί να κάνεις μόνο μια, άσε και κάτι για τους άλλους! :)

Είπα αφού θα ασχοληθώ με αυτόν τον καθηγητή να τα κάνω όλα update χαχα. Ωραία, θα κάνω update το issue για μία αλλαγή και θα κάνω revert μερικές αλλαγές που έγιναν ήδη στα pull-request.

**Comment by mariosconsta** [comment]
> ζητάς πολλές αλλαγές αρκεί να κάνεις μόνο μια, άσε και κάτι για τους άλλους! :)

Έχω κάνει update το issue. Πλέον αναφέρω πως θα κάνω αλλαγές μόνο για τα μαθήματα που λείπουν από τον καθηγητή. Τα στοιχεία όπως Email και URL για το CV θα γίνουν revert back to the defaults και παράλληλα θα γίνουν revert οι αλλαγές που έκανα στο αρχείο bihe.md που βρίσκετε στο φάκελο _groups. Τέλως, θα κλείσω το pull request που έχω στο sitegr αφού όλες οι αλλαγές που θα κάνω, τελικά βρίσκονται στο submodule all_collections.

Μπορείτε να επιβεβαιώσετε πως το issue είναι εντάξει έτσι ώστε να προχωρήσω με τις αλλαγές στα pull request; @epidrome
