### ISSUE TITLE
Προσθήκη "Πτυχιακής Εργασίας" στο Η' Εξάμηνο

### ISSUE THREAD

**Issue by CptMike** [ioniodi/sitegr#265]
### Δήλωση Θέματος
Προσθήκη "Πτυχιακής Εργασίας" και στο Η' εξάμηνο, σύμφωνα με το [official πρόγραμμα σπουδών](https://di.ionio.gr/gr/studies/undergraduate-studies/curriculum/), με όνομα αρχείου thesis-extended.md στο υποχρεωτικό μάθημα του H' εξαμήνου. Οι αλλαγές θα γίνουν στο φάκελο [_courses](https://github.com/CptMike/all_collections/blob/2014010/_courses/) και θα εμφανιστούν εδώ: [Η' εξαμηνο](https://sitegr-cptmike.netlify.app/courses/#%CE%B7-%CE%B5%CE%BE%CE%B1%CE%BC%CE%B7%CE%BD%CE%BF). Το updated site φαίνεται [εδώ](https://sitegr-cptmike.netlify.app/courses/#%CF%85%CF%80%CE%BF%CF%87%CF%81%CE%B5%CF%89%CF%84%CE%B9%CE%BA%CE%AC-%CE%BC%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%B1-7)
Εκτιμώμενη δυσκολία: easy
Σχετικοί συνεργατές: [@mariosconsta](https://github.com/mariosconsta)
Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/204 https://github.com/ioniodi/sitegr/issues/237

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@CptMike αν δεν βάλεις το @ μπροστά από το [mariosconsta](https://github.com/mariosconsta), δεν είμαι σίγουρος ότι θα το δει

**Comment by CptMike** [comment]
Έγινε!

**Comment by mariosconsta** [comment]
Όλα δουλεύουν όπως όρισε ο συνάδελφος στο demo. Τα URL, text, download pdf. Μία χαρά!

**Comment by epidrome** [comment]
δείτε λίγο την συζήτηση στο αρχικό #237

γενικά στην πληροφορική είναι λάθος η επανάληψη της ίδιας πληροφορίας σε δύο σημεία

**Comment by CptMike** [comment]
@epidrome @diogenisAl Σύμφωνα με αυτό το [issue](https://github.com/ioniodi/sitegr/issues/237) μπορώ να προχωρήσω;
