### ISSUE TITLE
Προσθήκη ανακοίνωσης «Δωρεάν δοκιμαστική περίοδος στη βάση ProQuest Dissertations & Theses Global»

### ISSUE THREAD

**Issue by alexpoulis** [ioniodi/sitegr#266]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη ανακοίνωσης [«Δωρεάν δοκιμαστική περίοδος στη βάση ProQuest Dissertations & Theses Global»](https://di.ionio.gr/gr/news/23526/) και σημεία στα οποία θα γίνουν αλλαγές: [1. προσθήκη της ανακοίνωσης](https://github.com/ioniodi/all_collections/tree/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_posts),  [2. προσθήκη εικόνας της ανακοίνωσης](https://github.com/ioniodi/sitegr/tree/master/assets/images). 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @gordthrow @geoter711 
- Σχετικά σύνδεσμοι: https://github.com/ioniodi/sitegr/issues/248, https://github.com/ioniodi/sitegr/issues/241, https://github.com/ioniodi/sitegr/issues/228

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by gordthrow** [comment]
φαινεται μια χαρα συναδελφε, συνεχισε ετσι.

**Comment by alexpoulis** [comment]
Έβαλα και 2ο άτομο για αξιολόγηση, καθώς είδα ότι έγιναν παρατηρήσεις σε συναδέρφους.

**Comment by Geoter711** [comment]
Και από εμένα καλά φαινέται!
