### ISSUE TITLE
Αλλαγή του καθηγητή στο μάθημα Διαχείριση Μεγάλου Όγκου Δεδομένων 

### ISSUE THREAD

**Issue by DimitrisTzer** [ioniodi/sitegr#267]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αλλαγή καθηγητή του μαθήματος από τον κ.Τσουμάκο στον κ.Τσίπη
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @StavroulaAnatolaki, @Vasdekis
- Σχετικά θέματα: [Αλλαγή του καθηγητή στο μάθημα "Δομές Δεδομένων"](https://github.com/ioniodi/sitegr/issues/256), [Αλλαγή του διδάκτορα του μαθήματος "Γραφικά με Υπολογιστές"](https://github.com/ioniodi/sitegr/issues/239), [Link προς το μάθημα στο site του τμήματος](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/632/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by StavroulaAnatolaki** [comment]
Θεωρώ πως ο  Δημήτρης εχει πραγματοποιήσει τις απαραίτητες αλλαγές που χρειαζόταν αυτό το θέμα. Η συνεισφορά του είναι ξεκάθαρη και πιστεύω πως μπορείτε να του δώσετε την έγκριση σας για να προχωρήσει στο pull request

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό

**Comment by Vasdekis** [comment]
Έχουν γίνει  όλες οι αλλαγές,θεωρώ μπορεί να πάρει το green light για να συνεχίσει.
