### ISSUE TITLE
Ενημέρωση βιογραφικού στο προφίλ του καθηγητή Εμμανουήλ Μαραγκουδάκη

### ISSUE THREAD

**Issue by KonstantinosTourtsakis** [ioniodi/sitegr#268]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: διόρθωση του βιογραφικού του καθηγητή Εμμανουήλ Μαραγκουδάκη στο αρχείο `sitegr/_data/authors.yml`. Στο βιογραφικό έλειπαν τα μαθήματα "Ανάκτηση Πληροφορίας" και "Επιστήμη των Δεδομένων" και έπρεπε να αφαιρεθεί το μάθημα "Δομές Δεδομένων". [Ο σύνδεσμος προς την σελίδα με τις αλλαγές](https://zen-goldstine-c1847a.netlify.app/people/mmarag/). Οι διορθώσεις έγιναν σύμφωνα με τα δεδομένα που δίνονται στην επίσημη [ιστοσελίδα του τμήματος](https://di.ionio.gr/gr/department/staff/332-maragoudakis/).
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @voltmaister @NickLitharis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):  [Αλλαγές στο προφίλ καθηγητή Θεμιστοκλή Έξαρχου #264](https://github.com/ioniodi/sitegr/issues/264)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@KonstantinosTourtsakis χρειάζεται και ο σύνδεσμος στην επίσημη ιστοσελίδα

**Comment by NickLitharis** [comment]
Συνάδελφε οι αλλαγές σου είναι σύμφωνες με την περιγραφή που έχεις δώσει, απο εμένα έχεις το green light.

**Comment by voltmaister** [comment]
Φαίνεται ότι όλα είναι σύμφωνα με τις οδηγίες , νομίζω παίρνεις πράσινο φως. Green light!!!

**Comment by epidrome** [comment]
> Σύντομη περιγραφή των επικείμενων αλλαγών: διόρθωση του βιογραφικού του καθηγητή Εμμανουήλ Μαραγκουδάκη στο αρχείο sitegr/_data/authors.yml. 

από που προκύπτει ότι χρειάζεται αλλαγή γνωστικού αντικειμένου;

**Comment by KonstantinosTourtsakis** [comment]
> > Σύντομη περιγραφή των επικείμενων αλλαγών: διόρθωση του βιογραφικού του καθηγητή Εμμανουήλ Μαραγκουδάκη στο αρχείο sitegr/_data/authors.yml.
> 
> από που προκύπτει ότι χρειάζεται αλλαγή γνωστικού αντικειμένου;

Νομίζω κατάλαβα το λάθος. Να ανοίξω καινούριο issue με διαφορετικές αλλαγές στο site ή να τροποποιήσω το συγκεκριμένο αναφέροντας τις καινούριες αλλαγές?

**Comment by epidrome** [comment]
αν είναι μικρή παραλλαγή του θέματος π.χ., για το ίδιο καθηγητή καλύτερα εδώ, αλλιώς αν είναι κάτι εντελώς διαφορετικό π.χ., αλλαγή σε μάθημα, σε νέο θέμα
