### ISSUE TITLE
Update ECTS calculator

### ISSUE THREAD

**Issue by p17kots** [ioniodi/sitegr#27]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
   Προσθήκη των μαθημάτων που προστέθηκαν στο νέο πρόγραμμα σπουδών και διαγραφή των μαθημάτων που αφαιρέθηκαν.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [ x ] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [ x ] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ο υπολογιστής μονάδων είναι προχωρημένη λειτουργία που σίγουρα χρειάζεται βελτίωση, ΑΛΛΑ,

η ενημέρωση των μαθημάτων γίνεται αυτόματα, αν δεις τον σχετικό κώδικα, τραβάει προγραμματιστικά (λικουηντ) τα μαθήματα από τις σχετικές συλλογές, άρα δεν χρειάζεται ξεχωριστή ενημέρωση

**Comment by p17kots** [comment]
Δεν έχω δει τον κώδικα,απλός είδα ότι υπάρχουν αρκετά μαθήματα που έχουν αλλάξει και δεν έχει ανανεωθεί.

**Comment by epidrome** [comment]
καλό είναι να βλέπεις τον σχετικό κώδικα ώστε να μην πάρεις κάτι πέρα από τις δυνατότητες σου!

για την ώρα αρκεί να κάνεις κάτι απλό, π.χ. ανακοίνωση

δες και τα σχόλια στους άλλους όσα έχουν γίνει δεκτά-άκυρα
