### ISSUE TITLE
Προσθηκη ανακοινωσης ''Δελτίο Βιβλιοθήκης για τις ερευνητικές δημοσιεύσεις Φεβρουαρίου 2022''

### ISSUE THREAD

**Issue by p18kana** [ioniodi/sitegr#270]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αναρτηση της ανακοινωσης ''Δελτίο Βιβλιοθήκης για τις ερευνητικές δημοσιεύσεις Φεβρουαρίου 2022'' απο το επισημο σαιτ του τμηματος.Link δημοσιευσης:https://di.ionio.gr/gr/news/23549/.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p18kout, @p18balt
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://github.com/ioniodi/sitegr/issues/241

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p18kana βάλε και το link της ανακοίνωσης στην επίσημη ιστοσελίδα.
Επίσης, το
> Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

είναι για το 2ο παραδοτέο, ότι το 1ο.

**Comment by p18kout** [comment]
Έχεις την έγκριση μου !
