### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα κατεύθυνσης "Αναγνώριση Προτύπων" στο ΣΤ' εξάμηνο

### ISSUE THREAD

**Issue by PetroulaStylianou** [ioniodi/sitegr#271]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αλλαγή καθηγητή στο μάθημα κατεύθυνσης "Αναγνώριση Προτύπων" στο ΣΤ' εξάμηνο. Η αλλαγή θα γίνει μέσω του [submodule](https://github.com/ioniodi/all_collections).
- Επίσημη ιστοσελίδα: [Αναγνώριση Προτύπων.](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/618/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @AnastasiaMariaStefani, @p18anas, @eliastks09
- Σχετικά θέματα: 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@PetroulaStylianou βάλε και τον σύνδεσμο με την πληροφορία στην επίσημη ιστοσελίδα

**Comment by p18anas** [comment]
Πολύ καλή δουλεία!

**Comment by AnastasiaMariaStefani** [comment]
Έξυπνη επιλογή!
