### ISSUE TITLE
Προσθήκη του καθηγητή Κ. Σκιαδόπουλου

### ISSUE THREAD

**Issue by Vuxxs** [ioniodi/sitegr#272]
**Σημείωση:** Έχω αφήσει το θέμα επειδή δε μπορώ να εντοπίσω τη βαθμίδα του καθηγητή. Όποιος θέλει μπορεί να το ολοκληρώσει.

### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα προσθέσω το αρχείο ```/all_collections/_people/kskiad.md``` με όσες πληροφορίες μπορώ να βρω για τον καθηγητή ```Κωνσταντίνος Σκιαδόπουλος```.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @p19vrou, @combustiblemon
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #257 #249 

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Ποιό θα ήταν το rank του Κ. Σκιαδόπουλου; Δε μπορώ να το βρω πουθενά στις επίσημες ιστοσελίδες.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Vuxxs θα πρέπει να συμπεριλάβεις και τις πληροφορίες **Σχετικά θέματα:**

**Comment by p19vrou** [comment]
Σχολιασμός: Ο @vuxxs έκανε τις άλλαγες που του ζητήθηκαν και έχει καλή ιδέα στο θέμα

**Comment by Combustiblemon** [comment]
Καλές αλλαγές από το μέρος του @Vuxxs

**Comment by epidrome** [comment]
@Vuxxs @diogenisAl ακυρώθηκε με το #44

**Comment by Vuxxs** [comment]
Dropped, δε μπορώ να βρω τη βαθμίδα και δε θέλω να απασχολήσω τον διδάσκοντα για να μη γίνομαι στόχος στα μαθήματα του κλπ. Θα προσπαθήσω να κάνω κάτι άλλο.

**Comment by epidrome** [comment]
πράγματι έγιναν πολλά λάθη σε αυτό το θέμα, αλλά δεν έγιναν μόνο από εσένα, αλλά από όλους, και από εμένα, π.χ., που έδωσα πράσινο φως νωρίτερα, 

για αυτό έχουμε τους αξιολογητές και την διαδικασία για να προλάβουμε λάθη, οι αξιολογητές, όπως σε πολλές περιπτώσεις, δυστυχώς, ήταν απλά θεατές-οπαδοί

μάλιστα, με δεδομένη την λίγο μεγαλύτερη δυσκολία αυτού του αιτήματος θα έλεγα ότι την μεγαλύτερη ευθύνη την έχουν οι αξιολογητές και μετά εσύ, και τέλος εμείς, που είμαστε υπό την πίεση πολλών θεμάτων.

το θέμα παραμένει ανοιχτό, γιατί είναι χρήσιμο και υπάρχουν αρκετά σχόλια για να το ολοκληρώσει όποιος θέλει

**Comment by diogenisAl** [comment]
@p19vrou αν κάποιος αποσύρει το ενδιαφέρον υλοποίησης κάποιου θέματος, θα πρέπει πρώτα να κλείσει το issue που δημιούργησε πριν το αναλάβει ο επόμενος
