### ISSUE TITLE
Προσθήκη Ανακοίνωσης "Ανακοίνωση γραφείου Erasmus"

### ISSUE THREAD

**Issue by Sola1r3** [ioniodi/sitegr#273]
### Δήλωση Θέματος
- Προσθήκη ανακοίνωσης "Ανακοίνωση γραφείου Erasmus" από την ιστοσελίδα του τμήματος
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @p17matt, @CptMike
- Σχετικά σύνδεσμοι : [Ιστοσελίδα τμήματος](https://di.ionio.gr/gr/news/23346/), [live-demo](https://cheerful-dusk-58b6de.netlify.app/posts/2022/02/08/anakoinwsh-grafeiou-erasmus/), [sitegr](https://github.com/Sola1r3/sitegr/tree/demo-branch), [all_collections](https://github.com/Sola1r3/all_collections/tree/master), https://github.com/ioniodi/sitegr/issues/362, https://github.com/ioniodi/sitegr/issues/296

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Sola1r3 μέχρι να αξιολογήσουν οι σχετικοί συνεργάτες, προτείνουμε αν προσθέσεις και τον σύνδεσμο με την ανακοίνωση στην επίσημη ιστοσελίδα

**Comment by p17matt** [comment]
Καλη δουλεια, ολα λειτουργουν σωστα, απο εμενα εχεις το ΟΚ

**Comment by epidrome** [comment]
συντηρούμε την σελίδα του τμήματος, όχι του ιδρύματος

υπάρχουν πολλά σημεία για διόρθωση στο περιεχόμενο που υπάρχει ήδη

**Comment by Sola1r3** [comment]
Δεν καταλαβαίνω τι εννοείται, είναι μια ανακοίνωση απο το την σελίδα του τμήματος πληροφορικής.

**Comment by epidrome** [comment]
οκ, δεκτό, μπερδεύτηκα γιατί γράφεις "σχολή" αλλά εννοείς "τμήμα", αυτά τα δύο είναι διακριτά. 

επίσης, προβληματίζομαι, γιατί η ανακοίνωση αυτή, όπως και αρκετές άλλες, π.χ., της βιβλιοθήκης, δεν είναι του τμήματος, αλλά ιδρυματικές

το γεγονός ότι η επίσημη σελίδα κάνει αρκετά λάθη, δεν σημαίνει πως πρέπει να τα αναπαράγουμε, επειδή όμως μόλις τώρα το είδα ας το κάνουμε δεκτό κατ' εξαίρεση και μέχρι να ενημερωθούν οι οδηγίες.

**Comment by CptMike** [comment]
Προσθήκη μόνο ενος αρχείου το οποίο φαίνεται οτι λειτουργεί σωστα.
