### ISSUE TITLE
Προσθήκη της ανακοίνωσης "2η Ανασυγκρότηση Κοσμητείας Σχολής Επιστήμης της Πληροφορίας και Πληροφορικής του Ιονίου Πανεπιστημίου, ακαδημαϊκού έτους 2021-2022"

### ISSUE THREAD

**Issue by PeteSKK** [ioniodi/sitegr#274]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη της ανακοίνωσης "[2η Ανασυγκρότηση Κοσμητείας Σχολής Επιστήμης της Πληροφορίας και Πληροφορικής του Ιονίου Πανεπιστημίου, ακαδημαϊκού έτους 2021-2022](https://di.ionio.gr/gr/news/23482/)"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Geoter711 @alexpoulis
- Σχετικά σύνδεσμοι: https://github.com/ioniodi/sitegr/issues/266 https://github.com/ioniodi/sitegr/issues/270 https://github.com/ioniodi/sitegr/issues/269 https://github.com/ioniodi/sitegr/issues/248 https://github.com/ioniodi/sitegr/issues/241 https://github.com/ioniodi/sitegr/issues/228 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@PeteSKK πρόσθεσε και τον σύνδεσμο με την ανακοίνωση στην επίσημη ιστοσελίδα

**Comment by Geoter711** [comment]
Μια χαρά από εμένα! Συνέχισε έτσι!

**Comment by PeteSKK** [comment]
Το διόρθωσα @diogenisAl

**Comment by diogenisAl** [comment]
@PeteSKK θα συνιστούσα να βάλεις και 2ο αξιολογητή: [https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059960377](https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059960377)

**Comment by PeteSKK** [comment]
Προσθέθηκε ο δεύτερος συνεργάτης μου.

**Comment by alexpoulis** [comment]
Δεν βλέπω κάτι λάθος, και από μένα είσαι οκ
