### ISSUE TITLE
Προσθήκη Ανακοίνωσης " Ημερίδα Ενημέρωσης - "Έξυπνες ψηφιακές εφαρμογές και εργαλεία για την αποτελεσματική προώθηση και ανάδειξη της βιοποικοιλότητας των Ιονίων Νήσων - ΕΡΜΗΣ""

### ISSUE THREAD

**Issue by initialelizah** [ioniodi/sitegr#275]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Στις κατηγορία των ανακοινώσεων θα προσθέσω την ανακοίνωση "Ημερίδα Ενημέρωσης - "Έξυπνες ψηφιακές εφαρμογές και εργαλεία για την αποτελεσματική προώθηση και ανάδειξη της βιοποικοιλότητας των Ιονίων Νήσων - ΕΡΜΗΣ" από την επίσημη σελίδα του πανεπιστημίου. 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Vagelis1993 @rafael5gr2
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): το επίσημο λινκ https://di.ionio.gr/gr/news/23261/ και κάποια σχετικά θέματα https://github.com/ioniodi/sitegr/issues/228#issue-1157826117 https://github.com/ioniodi/sitegr/issues/248#issue-1160017185

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό

**Comment by initialelizah** [comment]
Διορθώθηκε!
