### ISSUE TITLE
Ενημέρωση πληροφοριών για το μάθημα "Κοινωνικά και Νομικά Θέματα των ΤΠΕ"

### ISSUE THREAD

**Issue by p19vrou** [ioniodi/sitegr#276]
### Δήλωση Θέματος
- Ενημέρωση πληροφοριών για το μάθημα "Κοινωνικά και Νομικά Θέματα των ΤΠΕ". Συγκεκριμένα αφαίρεση του κ. Μάγκου και προσθήκη των κ. Τσώχου Αγγελική και κ. Χριστοπούλου Ελένη. Οι αλλαγές θα γίνουν στο [/_courses/social-and-legal-issues-of-icts.md](https://github.com/ioniodi/all_collections/blob/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_courses/social-and-legal-issues-of-icts.md)
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @vuxxs , @Combustiblemon
- Σχετικά σύνδεσμοι (https://di.ionio.gr/gr/department/staff/93-magkos/):
- Σχετικά θέματα: (https://github.com/ioniodi/sitegr/issues/272) , (https://github.com/ioniodi/sitegr/issues/264) , (https://github.com/ioniodi/sitegr/issues/263)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@p19vrou θα πρέπει να συμπληρώσεις και το πεδίο **Σχετικά θέματα**

**Comment by p19vrou** [comment]
Fixed!

**Comment by diogenisAl** [comment]
@p19vrou ΟΚ! Περιμένουμε την αξιολόγηση των σχετικών συνεργατών @Vuxxs @Combustiblemon για να προχωρήσουμε

**Comment by p19vrou** [comment]
Updated

**Comment by Vuxxs** [comment]
Εμένα μου φαίνεται εντάξει, αλλά θα μπορούσες να συμπληρώσεις ```/_people/emagos.md``` αντί για απλό ```_people``` στο πρώτο σου bullet point.

**Comment by Combustiblemon** [comment]
Οι αλλαγές φαίνονται να είναι εντάξει, αλλα όπως πρόσθεσε και ο συναδελφος παραπάνω, θα μπορούσες να ενημερώσεις το `emagos.md`.

**Comment by p19vrou** [comment]
Υπήρξε αλλαγή στον τίτλο και την περιγραφή του issue, διότι είχα επιλέξει λάθος τρόπο να κάνω την αρχική αλλαγή( να αφαιρέσω  τον κ. Μάγκο από ένα μάθημα), μιας και έτσι θα έμενε το μάθημα χωρίς καθηγητή. Οπότε θα προσθέσω και τις δύο καθηγήτριες που το έχουν αναλάβει.
