### ISSUE TITLE
Αλλαγή στο ωρολόγιο μαθημάτων του ΣΤ’ Εξαμήνου

### ISSUE THREAD

**Issue by Genti-voka** [ioniodi/sitegr#278]
### Δήλωση Θέματος
- Διόρθωση των περισσότερων [ωρών και μαθημάτων](https://epic-hamilton-da9ac8.netlify.app/timetables/sem_f/) οπου είναι σε λάθος μέρα η ώρα στον [φάκελο](https://github.com/ioniodi/all_collections/tree/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_timetables)
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @chrislach1 και @p19ntar 
- Σχετικά σύνδεσμοι: [Σωστό πρόγραμμα](https://di.ionio.gr/gr/students/schedule/) και αυτο ειναι το [Λάθος πρόγραμμα](https://epic-hamilton-da9ac8.netlify.app/timetables/sem_f/)
  
<h3> Απορίες σχετικά με το θέμα:</h3>
<p>Δεν ξέρω αν θα πρέπει να αλλάξω όλες τις ωρες των μαθημάτων και μέρες η απλά μερικά απο αυτα.</p>

### Υπενθυμίσεις 
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω </br>
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό </br>
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light </br>
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

<p> Δεν λειτουργούσε το x ανάμεσα στις αγκύλες οπότε έβαλα έναν κωδικό που κάνει περίπου το ίδιο. </p>

**Comment by p19ntar** [comment]
Σωστή παρατήτηση απλά βάλε και ποια αρχεία θα αλλάξεις πχ οι ώρες μαθημάτων είναι στο φάκελο _timetables

**Comment by epidrome** [comment]
μπορείς να αλλάξεις όσα θες και να αφήσεις κάτι για τους άλλους

**Comment by chrislach1** [comment]
@Genti-voka πολύ σωστή και σημαντική παρατήρηση συνάδελφε!
