### ISSUE TITLE
Ενημέρωση Προγράμματος Του ΣΤ’ Εξαμήνου 

### ISSUE THREAD

**Issue by p19kavv1** [ioniodi/sitegr#279]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Ενημέρωση του ωρολόγιου προγράμματος ΣΤ’ εξαμήνου, καθώς και η πρόσθεση αναφορών που έλειπαν 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Vuxxs, @p19vrou
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #235 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p17simt** [comment]
Επειδή και εγώ αντιμετώπισα το ίδιο θέμα με τους καινούριους καθηγητές:
Όσοι είναι περασμένοι στη σελίδα έχουν ένα δικό τους όνομα (πχ ο κ. Αυλωνίτης είναι περασμένος ως avlon κλπ).
Αν δεν υπάρχει ο καθηγητής στην σελίδα, βάλε το ονοματεπώνυμο με εισαγωγικά και θα είναι οκ!
