### ISSUE TITLE
Το μάθημα μεταγλωττιστές βρίσκεται σε λάθος εξάμηνο

### ISSUE THREAD

**Issue by P2019SARAKATSANIS** [ioniodi/sitegr#281]
###  Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Αλλαγή θέσης του μαθήματος μεταγλωττιστές από τα μαθήματα επιλογής του ΣΤ' εξαμήνου στα μαθήματα επιλογής του Ή εξαμήνου
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @u2nmd, @vasiliskampani
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):

     [Το κομμάτι κώδικα που θα υποστεί αλλαγή](https://github.com/ioniodi/all_collections/blob/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_courses/compilers.md)

     [Η ιστοσελίδα του πανεπιστημίου](https://dreamy-sammet-294cd4.netlify.app/)

     Σχετικά θέματα: #254 
                                #251 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19kala** [comment]
Φιλε προσεχε με την sneaky τελευταια υπενθυμιση που ειναι για το 2ο pull request. Καποιες φορες το github νομιζει οτι παμε για το 2ο pull request και το πεταει μεσα. Ισως χρειαστει να το διαγραψεις για το green light, οπως αναφερθηκε με [αυτο το issue](https://github.com/ioniodi/sitegr/issues/270#issuecomment-1059821068).

**Comment by u2nmd** [comment]
Σωστή η παρατήρησή σου, όντως το μάθημα αυτό βρίσκεται σε λάθος εξάμηνο πλέον οπότε θα ήταν σημαντική η μετακίνησή του στο σωστό εξάμηνο.
