### ISSUE TITLE
Διόρθωση URL στο μάθημα Αλγόριθμοι

### ISSUE THREAD

**Issue by p17siol** [ioniodi/sitegr#286]
### Δήλωση Θέματος
- Σκοπέυω να αλλάξω σε σωστό URL το λινκ του μαθήματος [Αλγόριθμοι](https://github.com/ioniodi/all_collections/blob/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_courses/algorithms.md), βλέπουμε οτι μας πάει στο πάλιο περιβάλλον e-class ενω θα έπρεπε να πηγαίνει στο καινούργιο περιβάλλον open-courses
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @[p17meli](https://github.com/p17meli) @[p17gera](https://github.com/p17gera)
- Σχετικά θέματα:  https://opencourses.ionio.gr/courses/DDI118/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

Υ.Γ, έχω ξανα δημιουργήσει και άλλο issue αλλα στην προσπάθεια μου να αλλάξω το label δεν με άφηνε και κατά λάθος το έκλεισα , οπότε δημιουργώ άλλο ένα με την διορθωμένη δήλωση

**Comment by diogenisAl** [comment]
@p17siol κάνε τις απαραίτητες αλλαγές σύμφωνα με το σχόλιο: [https://github.com/ioniodi/sitegr/issues/259](https://github.com/ioniodi/sitegr/issues/259)

**Comment by epidrome** [comment]
θέλουμε τουλάχιστον δύο αξιολογητές

παρατηρώ ότι αρκετοί βάζουν μόνον έναν, 

κάντε μια αναζήτηση θα βρείτε αρκετούς που δουλεύουν σχετικά θέματα και μπορούν να σας βοηθήσουν

έτσι ίσως προχωρήσουμε και πιο γρήγορα..

**Comment by p17meli** [comment]
Σωστή παρατήρηση, προχώρησε στην αλλαγή

**Comment by p17gera** [comment]
Η αλλαγή εγκρίνεται, προχώρησε στο επόμενο βήμα.
