### ISSUE TITLE
Εισαγωγή μαθήματος επιλογής στο Ή εξάμηνο  Έξυπνα περιβάλλοντα και Εφαρμογές 

### ISSUE THREAD

**Issue by vivikara** [ioniodi/sitegr#287]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Παρατήρησα ότι από το πρόγραμμα σπουδών στο Ή εξάμηνο λείπει το μάθημα επιλογής ¨Έξυπνα περιβάλλοντα και Εφαρμογές ". Οι αλλαγές θα γίνουν στο φάκελο _courses και θα εμφανιστούν : Η' εξαμηνo.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργάτες: @Cptmike @perikarananou 
- Σχετικά σύνδεσμοι  : [di.ionio.gr](https://di.ionio.gr/gr/), [link πρόγραμμα σπουδών με την αλλαγή](https://di.ionio.gr/gr/studies/undergraduate-studies/curriculum/), [link τρέχοντος προγράμματος σπουδών](https://nostalgic-kilby-4ee79b.netlify.app/courses/#%CE%B7-%CE%B5%CE%BE%CE%B1%CE%BC%CE%B7%CE%BD%CE%BF)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@vivikara θα πρέπει να γίνουν οι αλλαγές σύμφωνα με το σχόλιο [https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059960377](https://github.com/ioniodi/sitegr/issues/239#issuecomment-1059960377) (2 αξιολογητές, url με την πληροφορία)

**Comment by perikarananou** [comment]
Σωστή παρατήρησή σου, προχώρησε στην αλλαγή!!
