### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα "Βάσεις Δεδομένων 1"

### ISSUE THREAD

**Issue by p17meli** [ioniodi/sitegr#288]
### Δήλωση Θέματος
- Στο μάθημα "Βάσεις Δεδομένων 1" φαίνεται σαν καθηγητής ο κ. Σιούτας ενώ πλέον είναι ο κ. Μαραγκουδάκης και η κ. Σωτηροπούλου.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @p17gera, @p17siol
- Σχετικός σύνδεσμος στην επίσημη ιστοσελίδα : https://di.ionio.gr/gr/studies/undergraduate-studies/courses/596/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@p17meli θα πρέπει να δώσουν την αξιολόγησή τους οι σχετικοί συνεργάτες @p17gera, @p17siol

**Comment by p17gera** [comment]
Σωστή παρατήρηση, προχώρησε στην αλλαγή

**Comment by p17siol** [comment]
Η αλλαγη εγκρινεται
