### ISSUE TITLE
Διορθώσεις Προγράμματος Η΄ Εξαμήνου: "Τρόπος διδασκαλίας" , "εξ αποστάσεως σε δια ζώσης"

### ISSUE THREAD

**Issue by Vasdekis** [ioniodi/sitegr#289]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:Οι αλλαγές θα γίνουν ως εξής: εξ αποστάσεως σε δια ζώσης .
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @konstantina3 , @p18kavv
- Σχετικά σύνδεσμοι :[Ωρολόγιο Προγράμματος Η΄ Εξαμήνου](https://ionio.gr/download.php?f=01000-01999/IU-pf-01180-69159-gr.pdf) , [Σχετικό issue](https://github.com/ioniodi/sitegr/issues/291) , [Σχετικό issue](https://github.com/ioniodi/sitegr/issues/333)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Vasdekis θα πρέπει να έχεις τουλάχιστον 2 σχετικούς συνεργάτες. Επίσης, συνιστούμε να συμπεριλάβεις στο post και τυχόν σχετικά θέματα.

**Comment by Konstantina3** [comment]
Καλή η παρατήρησή σου Σωτήρη. Συνέχισε τη διαδικασία.

**Comment by p18kavv** [comment]
Καλή η παρατήρησή σου Σωτήρη. Συνέχισε τη διαδικασία.
