### ISSUE TITLE
Βιοπληροφορική - Προσθήκη Καθηγητή 

### ISSUE THREAD

**Issue by p17gera** [ioniodi/sitegr#290]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Στο μάθημα Βιοπληροφορική χρειάζεται προσθήκη καθηγητή (Αριστείδης Βραχάτης)
- Εκτιμώμενη δυσκολία: Easy
- Σχετικοί συνεργατές: @p17meli , @p17siol
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Επίσημη Σελίδα Ιονίου](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/750/) , [Sitegr](https://epic-hamilton-da9ac8.netlify.app/courses/bioinformatics/), [Αριστείδης Βραχάτης](https://di.ionio.gr/gr/department/staff/737-vrahatis/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@p17gera αναμένουμε την ανατροφοδότηση από @p17meli & @p17siol
Παράλληλα, συνιστούμε να βάλεις στο post και τυχόν σχετικά issue

**Comment by p17meli** [comment]
Σωστή παρατήρηση, προχώρησε στην αλλαγή
