### ISSUE TITLE
Αλλαγές στις ώρες και στις μέρες για το μάθημα "Διοίκηση Ασφάλειας Π.Σ" του Η' Εξαμήνου

### ISSUE THREAD

**Issue by Konstantina3** [ioniodi/sitegr#291]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Οι αλλαγές θα γίνουν ως εξής: αντί για 9-11 τις Τρίτες και Πέμπτες θα τροποποιηθούν σε 3-5 τις Πέμπτες και 1-3, 5-7 τις Παρασκευές.   
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Vasdekis, @p18kavv
- Σχετικά σύνδεσμοι: [Ωρολόγιο Πρόγραμμα Η' Εξαμήνου](https://ionio.gr/download.php?f=01000-01999/IU-pf-01180-69159-gr.pdf), [Σχετικό issue 1](https://github.com/ioniodi/sitegr/issues/289), [Σχετικό  issue 2](https://github.com/ioniodi/sitegr/issues/333)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Konstantina3 θα πρέπει να έχεις τουλάχιστον 2 σχετικούς συνεργάτες. Επίσης, θα πρέπει να συμπεριλάβεις στο 1ο post και τυχόν σχετικά issue

**Comment by Vasdekis** [comment]
Καλή η παρατήρησή σου Κωνσταντίνα. Συνέχισε τη διαδικασία.

**Comment by p18kavv** [comment]
Καλή η παρατήρησή σου Κωνσταντίνα. Συνέχισε τη διαδικασία.
