### ISSUE TITLE
Ενημέρωση ωρολογίου προγράμματος Δ' Εαρινού Εξαμήνου.

### ISSUE THREAD

**Issue by rafael5gr2** [ioniodi/sitegr#292]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Ενημέρωση του ωρολογίου προγράμματος Δ' Εαρινού Εξαμήνου. Επίσης παρατήρησα ότι το πρόγραμμα του Δ' Εαρινού Εξαμήνου στην ιστοσελίδα είναι ένα παλιό πρόγραμμα του Β' Εαρινού Εξαμήνου.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @initialelizah, @p18balt
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Προγράμματα από την επίσημη ιστοσελίδα του τμήματος](https://di.ionio.gr/gr/students/schedule/), [σχετικό issue 1](https://github.com/ioniodi/sitegr/issues/235), [σχετικό issue 2](https://github.com/ioniodi/sitegr/issues/279)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@rafael5gr2 θα πρέπει να δηλώσεις τουλάχιστον 2 σχετικούς συνεργάτες

**Comment by rafael5gr2** [comment]
@diogenisAl έκανα την διόρθωση που μου είπατε στο αρχικό comment μου.
