### ISSUE TITLE
Ενημέρωση ωρολογίου προγράμματος ΣΤ' Εαρινού Εξαμήνου

### ISSUE THREAD

**Issue by TheodoreZ-107** [ioniodi/sitegr#294]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Παρατήρησα ότι στο πρόγραμμα του ΣΤ' Εαρινού Εξαμήνου στην ιστοσελίδα αναγράφετε πως όλα τα μαθήματα θα γίνουν Εξ αποστάσεως
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @vasiliskampani ,@P2019SARAKATSANIS
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):[Σχετικό Issue 1](https://github.com/ioniodi/sitegr/issues/292) [Σχετικό Issue 2](https://github.com/ioniodi/sitegr/issues/279) [Επίσημη Ιστοσελίδα](https://di.ionio.gr/gr/students/schedule/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@TheodoreZ-107 δεν έχεις βάλει τον σύνδεσμο με την επίσημη ιστοσελίδα που έχει την πληροφορία & δεν έχεις επιλέξει τα checkboxes

**Comment by diogenisAl** [comment]
εκκρεμεί η έγκριση από @vasiliskampani & @P2019SARAKATSANIS

**Comment by vasiliskampani** [comment]
Θα ήταν καλό να δούμε ένα demo πρώτα με τις αλλαγές σου για να αξιολογήσουμε πιο εύστοχα.
