### ISSUE TITLE
[Γραφικά] Ανακοίνωση αποτελεσμάτων εξέτασης Ιανουαρίου 2022

### ISSUE THREAD

**Issue by p19zing** [ioniodi/sitegr#298]
### Δήλωση Θέματος
- Στα έγγραφα του opencourses έχουν ανέβει τα αποτελέσματα της πρόσφατης εξέτασης στο μάθημα "Γραφικά με Υπολογιστές"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Vuxxs , @p19vrou
- Σχετικός σύνδεσμος: [Ανακοίνωση Καθηγητή](https://opencourses.ionio.gr/modules/document/file.php/DDI123/%CE%91%CF%80%CE%BF%CF%84%CE%B5%CE%BB%CE%B5%CC%81%CF%83%CE%BC%CE%B1%CF%84%CE%B1%20%CE%B5%CE%BE%CE%B5%CC%81%CF%84%CE%B1%CF%83%CE%B7%CF%82%20%C2%AB%CE%93%CF%81%CE%B1%CF%86%CE%B9%CE%BA%CE%B1%CC%81%20%CE%BC%CE%B5%20%CE%A5%CF%80%CE%BF%CE%BB%CE%BF%CE%B3%CE%B9%CF%83%CF%84%CE%B5%CC%81%CF%82%C2%BB%20-%20%CE%99%CE%B1%CE%BD.2022.pdf)
- Σχετικά Θέματα: [Προσθήκη Ανακοίνωσης](https://github.com/ioniodi/sitegr/issues/276)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Vuxxs** [comment]
Θα μπορούσες να συμπεριλάβεις σχετικά issues;

**Comment by p19vrou** [comment]
Όπως ανέφερε και ο συνάδελφος από πάνώ, πιστεύω πρέπει να προσθέσεις κάποια σχετικά issues;

**Comment by epidrome** [comment]
η ιστοσελίδα μας είναι δημόσια
δεν είναι καλή ιδέα να κάνουμε ανάρτηση πράγματα που ο συγγραφέας του τα έχει ιδιωτικά
