### ISSUE TITLE
Προσθήκη περιεχομένου διοικητικού προσωπικού Έυα Κρανιώτη

### ISSUE THREAD

**Issue by sophia-ts** [ioniodi/sitegr#30]
### Διόρθωση στοιχείων διοικητικού προσωπικού
- Προσθήκη νέων μελών διοικητικού προσωπικού Έυα Κρανιώτη
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Θα πρέπει να αποκρύψω τα μέλη που δεν υπάρχουν στην official σελίδα ή απλά να διαγράψω το αντίστοιχο content;

### Υπενθυμίσεις
- [X] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
αρκεί να κάνεις μια αλλαγή σε ένα αρχείο, το οποίο  να είναι ξεκάθαρο στον τίτλο-περιεχόμενο του ίσιου εδώ, άσε και κάτι για τους άλλους!
