### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα "Ανάλυση και Σχεδιασμός Π.Σ."

### ISSUE THREAD

**Issue by Geoter711** [ioniodi/sitegr#300]
### Δήλωση Θέματος
- Αλλαγή του καθηγητή από την Αδαμαντία Πατέλη στον Βασίλειο Καρυώτη. Οι αλλαγές θα γίνουν στο  https://github.com/ioniodi/all_collections και οι πληροφορίες βρίσκονται στο https://di.ionio.gr/gr/studies/undergraduate-studies/courses/605/ 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @gordthrow @xar1sgeovlacp2019059
- Σχετικοί σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):  https://github.com/ioniodi/all_collections https://github.com/ioniodi/sitegr/issues/242 https://github.com/ioniodi/sitegr/issues/239 https://github.com/ioniodi/sitegr/issues/267 https://github.com/ioniodi/sitegr/issues/260

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by xar1sgeovlacp2019059** [comment]
Πολύ καλό. Συνέχισε.

**Comment by gordthrow** [comment]
Από αυτά που βλέπω δεν φαίνεται να σου λείπει κάτι. Νομίζω πως μπορείς να συνεχίσεις.
