### ISSUE TITLE
Προσθήκη μαθήματος  python στο Β΄Εξάμηνο.

### ISSUE THREAD

**Issue by Chris-Livas** [ioniodi/sitegr#305]
### Δήλωση Θέματος
- Θα ήθελα να προσθέσω το μάθημα του εφαρμοσμένου προγραμματισμού με python με διδάσκοντα τον κύριο Καρύδη και κύριο Πανάρετο στο Β΄ εξάμηνο.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες : @chrislach1 @u2nmd
- Σχετικά σύνδεσμοι (παλιό πρόγραμμα-νέο πρόγραμμα): https://epic-hamilton-da9ac8.netlify.app/timetables/sem_b/  https://di.ionio.gr/gr/students/schedule/

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by chrislach1** [comment]
Πολύ καλή παρατήρηση συνάδελφε! Η προσθήκη των σωστών μαθημάτων στα σωστά εξάμηνα είναι ιδιαίτερα σημαντική για την ενημέρωση των φοιτητών.
