### ISSUE TITLE
 Προσθήκη Θεωρίας Γραφημάτων και Εφαρμογών στο ΣΤ εξάμηνο

### ISSUE THREAD

**Issue by p2019044** [ioniodi/sitegr#306]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα προσθέσω το μάθημα επιλογής "Θεωρία Γραφημάτων και εφαρμογών".
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές:  @TaniaStoupi, @p19loli
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):<a href="https://di.ionio.gr/gr/studies/undergraduate-studies/courses/748/"> Θεωρία Γραφημάτων και εφαρμογών</a> <br> <a href="https://github.com/ioniodi/sitegr/issues/305">Αναφορά σε παρόμοιο issue</a>

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by TaniaStoupi** [comment]
Πολύ καλή η παρατήρηση σου, όντως το μάθημα μεταγλωτιστές βρίσκεται σε λάθος εξάμηνο και θεωρώ πολύ καλή την πρόταση σου να προσθέσεις ένα καινούργιο υπάρχων μάθημα στην θέση του.

**Comment by epidrome** [comment]
γιατί να αφαιρέσεις ένα μάθημα που άλλαξε εξάμηνο;

γιατί δεν εστιάζεις σε μία μόνο αλλαγή ή προσθήκη;
