### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα Αναγνώριση Προτύπων 

### ISSUE THREAD

**Issue by TaniaStoupi** [ioniodi/sitegr#307]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα κάνω αλλαγή του καθηγητή στο μάθημα αναγνώριση προτύπων του ΣΤ εξαμήνου, κάθως ο καθηγητής που διδάσκει το μάθημα είναι ο κ.Βραχάτης και όχι ο κ.Αυλωνίτης.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p2019044, @p19loli
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):<a href="https://di.ionio.gr/gr/studies/undergraduate-studies/courses/618/">Αναγνώριση Προτύπων</a> <br> <a href="https://github.com/ioniodi/sitegr/issues/300">Αναφορά σε άλλο issue</a>

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p2019044** [comment]
Σωστή η παρατήρηση σου για το ότι έχει αλλάξει ο καθηγητής του μαθήματος θέλω να το δω να το υλοποιείται.
