### ISSUE TITLE
Προσθήκη δεύτερης Navigation Bar με βασικές πληροφορίες του τμήματος πληροφορικής

### ISSUE THREAD

**Issue by Stavrospanakakis** [ioniodi/sitegr#31]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα ήθελα να προσθέσω μια δεύτερη μπάρα πάνω από την κανονική μπάρα με τις πληροφορίες που έχει στο κανονικό site του τμήματος πληροφορικής. (Links για opencourses, gramweb etc).
- Εκτιμώμενη δυσκολία: easy

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Για να το κάνω αυτό, θα πρέπει να κάνω extend το θέμα minimal-ionio. Γι' αυτόν τον λόγο θα πρέπει να κάνω extend τα layouts του θέματος σε αυτό το repository. Υπάρχει κάποιο πρόβλημα με αυτό;
### Υπενθυμίσεις
- [X] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
1. τα λινκ αυτά είναι ήδη στο κάτω μέρος της σελίδας, 
2. γενικά δεν αντιγράφουμε το στυλ κεντρικής, μόνο το περιεχόμενο και σε αυτό το ζητούμενο απλά κάνουμε ένα έντιτ-αντ-κτλ
3. αν θες να προτείνεις νέο/αλλαγή θέμα-στυλ αυτό είναι στα προχωρημένα ζητούμενα αυτής της εργασίας
