### ISSUE TITLE
Διόρθωση συνδέσμου οδηγού σπουδών

### ISSUE THREAD

**Issue by PaulosKal** [ioniodi/sitegr#32]
### Δήλωση Θέματος
- Ενημέρωση του συνδέσμου της αρχικής σελίδας προς το pdf του νέου οδηγού σπουδών (ο παλιός δεν δουλεύει και αναφέρεται σε προηγούμενο ακαδημαϊκό έτος)
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες:
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
αρκεί να κάνεις μια αλλαγή, άσε να κάνουν κάτι  και οι άλλοι!

**Comment by PaulosKal** [comment]
Άρα μόνο αλλαγή συνδέσμου.

**Comment by PaulosKal** [comment]
Ήταν τοπικό merge, μη δίνετε σημασία. Έρχεται το κανονικό..
