### ISSUE TITLE
Προσθήκη του hackathon του SB IEEE

### ISSUE THREAD

**Issue by Angeloth1** [ioniodi/sitegr#320]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: **_Θα προσθέσω ανακοινώση σχετικά με το hackathon του SB IEEE του πανεπηστιμίου._**
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @KonstantinosTourtsakis, @NickLitharis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
- https://github.com/Angeloth1/all_collections/blob/master/_posts/2022-3-8%20IEEE%20HACKATHON%20part2.md
https://github.com/ioniodi/sitegr/issues/276#issue-1160416014
https://github.com/ioniodi/sitegr/issues/298#issue-1160642920

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω

- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό

- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Angeloth1 έτσι όπως έχεις αναφέρει τους @KonstantinosTourtsakis, @NickLitharis δεν νομίζω ότι θα τους πάει κάποια ειδοποίηση

**Comment by Angeloth1** [comment]
> @Angeloth1 έτσι όπως έχεις αναφέρει τους @KonstantinosTourtsakis, @NickLitharis δεν νομίζω ότι θα τους πάει κάποια ειδοποίηση

Πολύ πιθανό αλλά τους έχω ιδιοποίηση και ιδιαίτερος μέσο social βέβαια, θα το διορθώσω από αύριο για να τους έρθει και ιδιοποίηση να ήμαστε τυπική.

**Comment by NickLitharis** [comment]
1. Άγγελε το τελευταίο checkbox δεν χρειάζεται προς το παρόν οπότε καλύτερα θα ήταν να το αφήσεις κενό.
2. Άλλαξε τον τίτλο του issue σου σε κάτι πιο σύντομο (π.χ. Προσθήκη του hackathon του SB IEEE) ή κάτι παραπλήσιο.
3. Πρόσθεσε τον σύνδεσμο που έχεις κάνει τις αλλαγές για να μπορέσουμε να κάνουμε την αξιολόγηση.
4. Βάλε και τα ονοματά μας σωστά και είσαι έτοιμος.

**Comment by KonstantinosTourtsakis** [comment]
Σχετικά με τον σύνδεσμο με τις αλλαγές που έχεις πραγματοποιήσει:
- Θέλουμε ο σύνδεσμος να δείχνει προς την δική σου σελίδα στο Netlify όπου μπορούμε να δούμε τις αλλαγές.
- Προτείνω να βάλεις τον σύνδεσμο στο **_Σύντομη περιγραφή των επικείμενων αλλαγών_** επειδή ταιριάζει περισσότερο σε εκείνη την κατηγορία.

Επίσης αν θες διόρθωσε και τα tags των συνεργατών. Για να το κάνεις αυτό απλά γράφεις "@" και στην συνέχεια το user id. Στην δική μου περίπτωση είναι @KonstantinosTourtsakis . Δεν χρειάζεται να σου εμφανίσει το όνομα μου στο dropdown που θα εμφανιστεί. Απλά γράψε σωστά το id. 

Τα υπόλοιπα νομίζω είναι εντάξει για το green light.

**Comment by Angeloth1** [comment]
Δυστυχώς δεν μπορώ να κάνω δουλέψει το netlify και δεν γνωρίζω τον λόγο και καθώς έχω μείνει είδη πίσω στις εργασίες των επόμενων εβδομάδων θα παραβλέψω την δημιουργία αυτής
