### ISSUE TITLE
Αλλαγές στο προφίλ του καθηγητή Αλέξανδρου Πανάρετου.

### ISSUE THREAD

**Issue by p19loli** [ioniodi/sitegr#321]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θέλω να προσθέσω στο προφίλ του κ. Πανάρετου τα διδασκόμενα μαθήματά του, καθώς λείπουν όλα, και τα εργαστήρια μαζί με τα μαθήματα, όπως φαίνονται στην επίσημη σελίδα.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p2019044, @TaniaStoupi
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): <a href="https://di.ionio.gr/gr/department/staff/72-panaretos/">Προφίλ Αλέξανδρος Πανάρετος</a>
<a href="https://github.com/ioniodi/sitegr/issues/280">Σχετικό Θέμα</a>

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by TaniaStoupi** [comment]
Πολύ καλή η παρατήρηση σου! Συμφωνώ ότι είναι πολύ σημαντικό να υπάρχουν τα διδασκόμενα μαθήματα στον διδάσκοντα για την καλύτερη ενημέρωση των φοιτητών.

**Comment by p2019044** [comment]
Εξαιρετική η παρατήρηση σου. Είναι μια πολύ καλή ιδέα για την ενημέρωση των φοιτητών και περιμένω να την δω να υλοποιείται.
