### ISSUE TITLE
Προσθήκη Ρομποτικής, Διαστημικού Ιντερνετ, και Drone στα μαθηματα του τμήματος Πληροφορικής

### ISSUE THREAD

**Issue by harikoulouri** [ioniodi/sitegr#322]
### Δήλωση Θέματος
- Προσθήκη μαθημάτων Ρομποτικής, Διαστημικού Ιντερνετ, ΙοΤ και Drone στα μαθηματα του τμήματος Πληροφορικής
- Εκτιμώμενη δυσκολία: very easy, easy, hard, very hard
- Σχετικοί συνεργατές: @
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):

### Υπενθυμίσεις
- [ ] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [ ] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [ ] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
1. δύο τουλάχιστον συνεργάτες για σχολιασμό
2. σύνδεσμο στο μάθημα στην επίσημη ιστοσελίδα

από όσο ξέρω αυτό το μάθημα δεν υπάρχει, οπότε δεν μπορούμε να το προσθέσουμε

**Comment by harikoulouri** [comment]
Καλησπερα,

οταν λες συνεργατες? τι εννοεις? απο την ομαδα στο webring?
Υποθετικα δεν μπαινουν ολα αυτα?  ΡΟμποτ και δορυφορικο ιντερνετ ειναι πραγματικοτητα, δεν ξερω τι εχει αποφασισει το υπουργειο, ρομποτικη φετος βαλανε στα λυκεια

**Comment by harikoulouri** [comment]
Ευχαριστω για τα κομμεντ

**Comment by epidrome** [comment]
δες λίγο τα θέματα που έχουν ανοίξει οι άλλοι και θα καταλάβεις

**Comment by harikoulouri** [comment]
Καλημερα,


δεν εχω βρει κατι αλο για αλλαγη. παντως ετρεξα κατι στο netlify:

https://confident-ardinghelli-7cb661.netlify.app/

Ευχαριστω

**Comment by epidrome** [comment]
> οταν λεte συνεργατες? απο την ομαδα στο webring?
> 

δες σχετικά θέματα issues, έχει απαντήσεις σε αυτά τα ερωτήματα και σε πολλά ακόμη

> Υποθετικα δεν μπαινουν ολα αυτα τα μαθηματα? 

καθόλου υποθετικά
