### ISSUE TITLE
Συμφωνία ΣΕΑΒ με De Gruyter για την κάλυψη δημοσιεύσεων σε καθεστώς Ανοικτής Πρόσβασης

### ISSUE THREAD

**Issue by p19zing** [ioniodi/sitegr#323]
### Δήλωση Θέματος
- Ανακοίνωση με θέμα "Συμφωνία ΣΕΑΒ με De Gruyter για την κάλυψη δημοσιεύσεων σε καθεστώς Ανοικτής Πρόσβασης"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Vuxxs , @p19vrou
- Σχετικός σύνδεσμος: [Ανακοίνωση Τμήματος Πληροφορικής](https://di.ionio.gr/gr/news/23556/)

- Σχετικά Θέματα: #298 

- Σύνδεσμος στο [post του all_collections](https://github.com/p19zing/all_collections/blob/aaaf3483c1f60f502d03837d98a1ac294e33b3ef/_posts/2022-03-04-De-Gruyter.md)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19vrou** [comment]
Δεν παρατηρώ κάποια σημαντική αλλαγή που χρειάζεται να γίνει.  Θεωρώ πως μπορείς να συνεχίσεις.

**Comment by Vuxxs** [comment]
Και εγώ πιστεύω εφόσον τα σχετικά θέματα είναι πλέον σωστά μπορείς να προχωρήσεις.
