### ISSUE TITLE
Αλλαγή επισκέπτη καθηγητή Bernd Wegner σε επίτιμο διδάκτορα 

### ISSUE THREAD

**Issue by Mariadar97** [ioniodi/sitegr#331]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα αλλάξω τον κύριο Bernd Wegner απο επισκέπτη καθηγητή σε επίτιμο διδάκτορα στη σελίδα προσωπικό 
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: @p17anto2 @ApoLaz
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #233 #187 [di.ionio](https://di.ionio.gr/gr/department/staff/visiting/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by ApoLaz** [comment]
καλή η παρατήρηση σου απο εμένα έχεις το οκ.

**Comment by p17anto2** [comment]
Και από μενα οκ!

**Comment by epidrome** [comment]
νομίζω πως αυτός ο καθηγητής είναι επίτιμος διδάκτορας του τμήματος

μήπως το σωστό είναι να αλλάξουμε την κατηγορία του;

**Comment by p17anto2** [comment]
Απ' ότι βλέπω στη σελίδα προσωπικό στο di.ionio δεν υπάρχει. Παρ' όλ' αυτά, με αναζήτηση βρήκα [αυτήν την ανακοίνωση-άρθρο](https://di.ionio.gr/gr/news/9081/) από το 2016 όπου όντως γίνεται επίτιμος διδάκτορας.

**Comment by diogenisAl** [comment]
@p17anto2 κάνε την απαραίτητη αναπροσαρμογή στον τίτλο και το περιεχόμενο του 1ου post

**Comment by epidrome** [comment]
θα πρέπει να δημιουργήσουμε μια νέα κατηγορία, μάλιστα υπάρχουν αρκετοί που ανήκουν εκεί και θα πρέπει να προστεθούν

ο διαθέσιμος αριθμός για αυτή την κατηγορία είναι το 10

https://github.com/ioniodi/minimal-ionio/blob/master/_includes/people-rank.html
