### ISSUE TITLE
Αλλαγές στις ώρες και στις μέρες στο μάθημα "Επεξεργασία Ομιλίας και Ήχου" του Η' Εξαμήνου

### ISSUE THREAD

**Issue by p18kavv** [ioniodi/sitegr#333]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Οι αλλαγές θα γίνουν ως εξής: αντί για 3-5 τις Τρίτες και Πέμπτες θα τροποποιηθούν σε 7-9 τις Τετάρτες και τις Παρασκευές.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @konstantina3, @Vasdekis
- Σχετικά σύνδεσμοι: [Ωρολόγιο Προγράμματος Η΄ Εξαμήνου](https://ionio.gr/download.php?f=01000-01999/IU-pf-01180-69159-gr.pdf) , [Σχετικό issue](https://github.com/ioniodi/sitegr/issues/291) , [Σχετικό issue](https://github.com/ioniodi/sitegr/issues/289)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Konstantina3** [comment]
Καλή η παρατήρησή σου Κωνσταντίνα. Συνέχισε τη διαδικασία.

**Comment by Vasdekis** [comment]
Καλή η παρατήρησή σου Κωνσταντίνα. Συνέχισε τη διαδικασία.
