### ISSUE TITLE
Προσθήκη Βιβλίων για το μάθημα "Εφαρμοσμένος προγραμματισμος με Python" στην συλλογή των βιβλίων

### ISSUE THREAD

**Issue by p19pasc** [ioniodi/sitegr#334]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:  Θα προσθέσω στο αρχείο [sitegr/_bibliography/references.bib](https://github.com/ioniodi/sitegr/blob/master/_bibliography/references.bib) τα απαραίτητα βιβλία για το μάθημα της python επειδή λείπουν. Τα έχω ήδη κάνει εδώ [γραμμές 1788-τέλος](https://github.com/p19pasc/sitegr/blob/b76e8b0aa0670c7d19b3bca68ab56aa9e1ec25fb/_bibliography/references.bib#L1788)(αλλά θα δημιουργήσω ένα νέο branch)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @vasiliskampani @u2nmd @AimiliosPavlidis2001 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): 
  * Επίσημη σελίδα του [Ιονίου Πανεπιστημίου στο μάθημα της python](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/733/) από το οποίο παίρνω τα στοιχεία των βιβλίων (isbn, συγγραφείς, αριθμός σελίδων).
  *  Σχετικά θέματα: #234 
                                 #176 
  
Δεν υπάρχει κάποιος τρόπος να δείξω ένα demo με αυτήν την προσθήκη που θα κάνω, αλλά [δείχνω ένα demo](https://demo-p2019110.netlify.app/courses/applied-programming-python/) από το παρακάτω issue που είχα ανοίξει(το οποίο και επαληθεύει αν έχω βάλει σωστά τα στοιχεία του κάθε βιβλίου). Στην ουσία αφού προσθέσω τα βιβλία στο bibliography, ύστερα οποιοσδήποτε αναλάβει σε άλλο αίτημα ενσωμάτωσης να κάνει προσθήκη αυτών των βιβλίων στο μάθημα της [python](https://github.com/ioniodi/all_collections/blob/master/_courses/applied-programming-python.md) στο all_collections, θα μπορεί να δει τα βιβλία στην ιστοσελίδα 
   
**_Να αναφέρω ότι αυτό το issue δημιουργήθηκε με αφορμή να σπάσω την ιδέα μου του issue #234 εφόσον το συζήτησα με τον καθηγητή διαζώσης σε απλούστερα κομμάτια λόγο της αδυναμίας μου να κάνω pull request και στο sitegr και στο all_collections όπως αναγράφονται στις [οδηγίες](https://github.com/courses-ionio/sw/discussions/1042#discussioncomment-2311233) εξαιτίας του θέματος με τα submodules._**
### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by u2nmd** [comment]
Μπράβο @p19pasc πιστεύω θα καταφέρεις να υλοποιήσεις την πρότασή σου γιατί έχεις ήδη μία βάση από το προηγούμενο issue σου αλλά και άλλου συμφοιτητή!

**Comment by p19pasc** [comment]
Προσωρινό κλείσιμο
