### ISSUE TITLE
Προσθήκη καθηγητή στο μάθημα "Οργάνωση και διοίκηση επιχειρήσεων" του Β' Εξαμήνου.

### ISSUE THREAD

**Issue by AnastasiaMariaStefani** [ioniodi/sitegr#336]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών. Προσθήκη καθηγητή στο μάθημα "Οργάνωση και διοίκηση επιχειρήσεων" του Β' Εξαμήνου.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @PetroulaStylianou @p18anas @eliastks09
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://di.ionio.gr/gr/studies/undergraduate-studies/courses/587/  ,   https://epic-hamilton-da9ac8.netlify.app/courses/ba/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by PetroulaStylianou** [comment]
Πολύ καλή επιλογή!
