### ISSUE TITLE
Αφαίρεση Διοικητικού Υπαλλήλου Σωτηρία-Σοφία Αρωνιάδα

### ISSUE THREAD

**Issue by panosath** [ioniodi/sitegr#339]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: [Αφαίρεση του αρχείου .md](https://github.com/panosath/all_collections/commit/5a07e09eb015487603d77b288cdd0e8c62c5f814) που εμπεριείχε τα στοιχεία του διοικητικού υπαλλήλου Σωτηρία-Σοφία Αρωνιάδα από την σελίδα του Προσωπικού.
Εδώ βρίσκεται το [link](https://inspiring-swirles-989127.netlify.app/people/) στη σελίδα του demo μου και εδώ είναι η [επίσημη σελίδα](https://di.ionio.gr/gr/department/staff/administrative-staff/) του Πανεπιστημίου που επιβεβαιώνει την αλλαγή.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: @p17anto2 @Mariadar97
- Σχετικοί σύνδεσμοι με παρόμοια θέματα: #331 #249 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@panosath πρόσθεσε το link με την επίσημη ιστοσελίδα (που τεκμηριώνει την προτεινόμενη αλλαγή)

**Comment by panosath** [comment]
Updated 👍

**Comment by p17anto2** [comment]
Καλή παρατήρηση, μου φαίνεται μια χαρά
