### ISSUE TITLE
Αλλαγή Βαθμίδας καθηγητή Μιχαήλ Στεφανιδάκη από επίκουρο σε Αναπληρωτή καθηγητή

### ISSUE THREAD

**Issue by p19poly1** [ioniodi/sitegr#340]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Στο tab προσωπικό της [σελίδας](https://epic-hamilton-da9ac8.netlify.app/people/) θα διαγραφεί ο Μιχαήλ Στεφανιδάκης από τη λίστα Επίκουροι Καθηγητές και θα προστεθεί στη λίστα Αναπληρωτές Καθηγητές όπως είναι και στην επίσημη ιστοσελίδα του τμήματος [site](https://di.ionio.gr/gr/department/staff/professors/).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @john7665 @p17anto2 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #307 #271 #247

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by john7665** [comment]
Από ότι είδα δεν έχει προλάβει άλλος το θέμα και είναι σωστό. Συνεχίζεις από εμένα.

**Comment by p17anto2** [comment]
Πρόσθεσε και το link για την επίσημη ιστοσελίδα που φαίνεται η αλλαγή και έχεις και οκ κι από μένα
