### ISSUE TITLE
Προσθήκη των μαθημάτων που διδάσκει ο κύριος Πανάρετος

### ISSUE THREAD

**Issue by Mnlsvt** [ioniodi/sitegr#344]
### Δήλωση Θέματος
Προσθήκη των εξής μαθημάτων στον κατάλογο του κυρίου Αλέξανδρου Πανάρετου: 
Πιθανότητες, Εφαρμοσμένος Προγραμματισμός με Python, Στατιστική, Στοχαστική Ανάλυση Δεδομένων, Προσομοίωση και Μοντελοποίηση, Τεχνολογία Ψυχαγωγικού Λογισμικού & Εικονικοί Κόσμοι

- Σχετικοί συνεργατές: @p19biza @p19ntar

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@Mnlsvt δεν έχεις βάλει τον σύνδεσμο με την επίσημη ιστοσελίδα της πληροφορίας, ούτε και σχετικά issues

**Comment by diogenisAl** [comment]
@Mnlsvt Το πιο σημαντικό όμως είναι: [https://github.com/ioniodi/sitegr/issues/321](https://github.com/ioniodi/sitegr/issues/321)
