### ISSUE TITLE
Προσθήκη ερευνητικού ενδιαφέροντος στον κύριο Βλάμο.

### ISSUE THREAD

**Issue by alexl14** [ioniodi/sitegr#345]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών Προσθήκη ενός ακόμα ερευνητικού ενδιαφέροντος που έλειπε στον κύριο Βλάμο.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @p19biza @Mnlsvt
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://di.ionio.gr/gr/department/staff/90-vlamos/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@alexl14 υπάρχουν σχετικά issues άλλων συναδέλφων;

**Comment by alexl14** [comment]
@diogenisAl απότι έχω δεί στα issues όχι δεν υπάρχει κάτι σχετικό.

**Comment by diogenisAl** [comment]
OK. Οπότε περιμένουμε ανατροφοδότηση από τους @p19biza @Mnlsvt
Παράλληλα, μπορείς να εμπλουτίσεις το 1ο post με link σε αρχεία ή φακέλους που αλλάζουν

**Comment by Mnlsvt** [comment]
Συμφωνώ με την παρατήρηση του @alexl14.

**Comment by p19biza** [comment]
Πιστεύω ότι η προσθήκη του @alexl14 είναι σωστή
