### ISSUE TITLE
Αλλαγή καθηγητή στο μάθημα "Προσομοίωση και Μοντελοποίηση" του εξαμήνου Ζ'

### ISSUE THREAD

**Issue by p18anas** [ioniodi/sitegr#346]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα γίνει αντικατάσταση του καθηγητή Παναγιώτη Βλάμου με τον καθηγητή Αυλωνίτης Μάρκος στο μάθημα "Προσομοίωση και Μοντελοποίηση". Οι αλλαγές θα γίνουν στο [submodule](https://github.com/ioniodi/all_collections).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @AnastasiaMariaStefani @PetroulaStylianou @p19pasa
- Σχετικά σύνδεσμοι: [Επίσημη ιστοσελίδα](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/641/) , [Demo](https://inspiring-swirles-989127.netlify.app/courses/smart-technologies-and-applications/)
- Σχετικά θέματα: [Αλλαγή καθηγητή στο μάθημα κατεύθυνσης "Αναγνώριση Προτύπων" στο ΣΤ' εξάμηνο](https://github.com/ioniodi/sitegr/issues/271) , [Αλλαγή καθηγητή στο μάθημα προγραμματισμός υπολογιστών](https://github.com/ioniodi/sitegr/issues/260)
### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@p18anas συνιστούμε να συμπεριλάβεις και σχετικά issues

**Comment by diogenisAl** [comment]
Τι λένε οι @AnastasiaMariaStefani @PetroulaStylianou @p19pasa;

**Comment by AnastasiaMariaStefani** [comment]
Καλή επιλογή θέματος!

**Comment by PetroulaStylianou** [comment]
Πολύ καλή η παρατήρηση σου!

**Comment by p19pasa** [comment]
Πιστεύω ότι τα έχεις βάλει όλα σύμφωνα με τις οδηγίες μπράβο!

**Comment by epidrome** [comment]
ποιον καθηγητή θα προσθέσεις; επιτρέπει η ιστοσελίδα 2ο καθηγητή;
