### ISSUE TITLE
Προσθήκη του μαθήματος <<Προγραμματισμός Υπολογιστών >> του καθηγητή Κωνσταντίνου Βόγκλη στο προφίλ του,στην κατηγορία "Προσωπικό"

### ISSUE THREAD

**Issue by p19verg** [ioniodi/sitegr#349]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:Προσθήκη του μαθήματος <<Προγραμματισμός Υπολογιστών >>  του καθηγητή Κωνσταντίνου Βόγκλη στο προφίλ του ,στην κατηγορία "Προσωπικό".Οι αλλαγές θα γίνουν στο submodule [all_collections](https://github.com/ioniodi/all_collections). Το προφίλ του στην ανεπίσημη σελίδα είναι το ακόλουθο [link](https://epic-hamilton-da9ac8.netlify.app/people/voglis/)
- Εκτιμώμενη δυσκολία: easy,
- Σχετικοί συνεργατές: @p19pasa @anastasia-rizou
- Αντίστοιχη σελίδα στον επίσημο ιστότοπο: [Κωνσταντίνος Βόγκλης](https://di.ionio.gr/gr/department/staff/691-vogklis/)
- Σχετικά θέματα: [Προσθήκη Μαθήματος Επιλογής <<Κατανεμημένα Δικτυοκεντρικά Συστήματα>> στο ΣΤ' Εξάμηνο #251](https://github.com/ioniodi/sitegr/issues/251)
### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
σύνδεσμος στην αντίστοιχη επίσημη ιστοσελίδα και στην δικιά μας που δείχνει την ανάγκη των αλλαγών;

**Comment by epidrome** [comment]
σύνδεσμος στην αντίστοιχη επίσημη ιστοσελίδα και στην δικιά μας που δείχνει την ανάγκη των αλλαγών;

**Comment by Anastasia-Rizou** [comment]
Αν είσαι σίγουρος για τα μαθήματα που διδάσκει ο κ.Κωνσταντίνος Βόγκλης αυτό το εξάμηνο, τότε προχώρα.

**Comment by p19pasa** [comment]
Η αντίστοιχη επίσημη ιστοσελίδα είναι στο κανονικό site του Πανεπιστημίου και η άλλη ιστοσελίδα που ζητείται είναι αυτή που βρέθηκε το λάθος δηλαδή στο sitegr

**Comment by epidrome** [comment]
> Η αντίστοιχη επίσημη ιστοσελίδα είναι στο κανονικό site του Πανεπιστημίου και η άλλη ιστοσελίδα που ζητείται είναι αυτή που βρέθηκε το λάθος δηλαδή στο sitegr

οι σύνδεσμοι τους θα πρέπει να βρίσκονται στο 1ο ποστ

**Comment by p19verg** [comment]
@epidrome ενημέρωσα το issue  προσθέτοντας την αυθεντική σελίδα και τη σελίδα από το netily.

**Comment by epidrome** [comment]
έχετε εξετάσει μήπως ήδη έγινε αυτή η προσθήκη;
https://epic-hamilton-da9ac8.netlify.app/people/voglis/

**Comment by p19verg** [comment]
@epidrome βεβαίως, στο προφίλ αυτό δεν αναγράφονται τα μαθήματα του διδάσκοντα. Αυτό θέλω να προσθέσω

**Comment by epidrome** [comment]
τότε ενημερώστε το 1ο ποστ με τα μαθήματα και την τρέχουσα κατάσταση

**Comment by p19verg** [comment]
@epidrome ενημέρωσα το 1ο ποστ και τον τίτλο όπως ζητήσατε
