### ISSUE TITLE
Διόρθωση URL μαθήματος Δίκτυα ΙΙ

### ISSUE THREAD

**Issue by Anastasia-Rizou** [ioniodi/sitegr#350]
### Δήλωση Θέματος
- Σκοπέυω να αλλάξω τα urls του μαθήματος [Δίκτυα ΙΙ](https://github.com/Anastasia-Rizou/all_collections/blob/69aa69103dec23e4af42a28cf7b1c7438c38af7d/_courses/networks2.md) αφού μας πάνε στην παλιά πλατφόρμα eclass.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @p19pasa, @p19verg
- Σχετικά σύνδεσμοι  (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Δίκτυα ΙΙ](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/602/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
1. αρκεί να κάνεις μια αλλαγή, όχι δύο
2. σύνδεσμος στην αντίστοιχη επίσημη ιστοσελίδα;
3. για να καλέσεις αξιολογητές δεν χρειάζεται σύνδεσμος

**Comment by Anastasia-Rizou** [comment]
Σας ευχαριστώ για τις παρατηρήσεις. Έκανα τις αλλάγες, που ελπίζω ότι είναι σωστές.

**Comment by p19pasa** [comment]
Καλή επιλογή θέματος!

**Comment by p19verg** [comment]
Μπράβο,καλή παρατήρηση!

**Comment by diogenisAl** [comment]
@Anastasia-Rizou στο 1ο post συνιστούμε να μπει και ο σύνδεσμος με την επίσημη ιστοσελίδα της πληροφορίες (π.χ. **di.ionio.gr/........**)

**Comment by Anastasia-Rizou** [comment]
Ευχαριστώ, έκανα την αλλαγή.
