### ISSUE TITLE
Ενημέρωση διδάσκοντα για το μάθημα "Στρατηγική και Διοίκηση Πληροφοριακών Συστημάτων"

### ISSUE THREAD

**Issue by axilleasmandravelis** [ioniodi/sitegr#351]
### Δήλωση Θέματος
- Ενημέρωση διδάσκοντα για το μάθημα "Στρατηγική και Διοίκηση Πληροφοριακών Συστημάτων"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p17simt @nikosbout
- Σχετικά σύνδεσμοι : [Ο σύνδεσμος στην σελίδα](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/634/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p17simt** [comment]
εφοσον το μαθημα διδάσκεται φετος απο τον κ.κουρουθαναση, καλή σκεψη να το αλλαξεις.

**Comment by nikosbout** [comment]
Βλεπω πως δεν το έχει επιλέξει κάποιος αλλος πριν απο εσενα και ειναι σωστό το θεμα.. μπορείς να συνεχίσεις απο εμενα.

**Comment by epidrome** [comment]
1. θα πρέπει να τσεκάρεις με λατινικό χ τα κουτάκια
2. που είναι ο σύνδεσμος στην επίσημη σελίδα;
3. τα παραπάνω συνηθισμένα λάθη θα έπρεπε να τα είχαν είχαν εντοπίσει οι σχολιαστές, που για αυτόν τον σκοπό καλό είναι να είναι ανεξάρτητοι και όχι φίλοι

**Comment by diogenisAl** [comment]
@axilleasmandravelis αυτός ο σύνδεσμος ([Ο σύνδεσμος στην σελίδα](https://opencourses.ionio.gr/courses/DDI152/)) παραπέμπτει στο opencourses, όχι στην επίσημη ιστοσελίδα [di.ionio.gr](https://di.ionio.gr/gr/).

**Comment by axilleasmandravelis** [comment]
Ευχαριστώ.Έκανα την αλλαγή.

**Comment by epidrome** [comment]
στο μεταξύ φαίνεται πως η κανονική διδάσκουσα επέστρεψε οπότε αυτή η αλλαγή είναι περιττή, και μάλλον ήταν περιττή από την αρχή αφού ήταν μια προσωρινή αλλαγή.
