### ISSUE TITLE
Προσθήκη ανακοίνωσης "Διατμηματική ενημερωτική συνάντηση για την Πρακτική Άσκηση"

### ISSUE THREAD

**Issue by p17gera1** [ioniodi/sitegr#353]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Πρόκειται να προσθέσω την νέα ανακοίνωση που έχω βρει από την επίσημη ιστοσελίδα του πανεπιστημίου μας
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @vivikara και @alexpoulis
- Σχετικοί σύνδεσμοι: [Η ανακοίνωση ](https://ionio.gr/gr/news/23631/) 
[1ο προηγούμενο σχετικό θέμα ](https://github.com/ioniodi/sitegr/issues/266) 
[2ο προηγούμενο σχετικό θέμα ](https://github.com/ioniodi/sitegr/issues/269)
[3ο προηγούμενο σχετικό θέμα ](https://github.com/ioniodi/sitegr/issues/270)  

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by vivikara** [comment]
Σωστή η παρατήρηση σου συνέχισε!

**Comment by epidrome** [comment]
δεν φτιάχνουμε (ακόμη) την ιστοσελίδα του ιδρύματος
