### ISSUE TITLE
Προσθήκη ανακοίνωσης "Το Ιόνιο Πανεπιστήμιο συλλέγει ανθρωπιστική βοήθεια για την Ουκρανία"

### ISSUE THREAD

**Issue by p17gera1** [ioniodi/sitegr#355]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Πρόκειται να προσθέσω την νέα ανακοίνωση που δημοσιεύθηκε στην επίσημη ιστοσελίδα του τμήματος μας 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @vivikara και @alexpoulis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Η ανακοίνωση](https://di.ionio.gr/gr/news/23639/)
[1ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/266)
[2ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/269)
[3ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/270)

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by alexpoulis** [comment]
@p17gera1 Σαν θέμα μία χαρά φαίνεται, αλλά καθώς μου είχε γινεί η παρατήρηση εφόσον είχα και εγώ εικόνα στην ανακοίνωση θα πρότεινα να μην βάλεις την εικόνα καθώς μπορεί να κάνει την διαδικασία των pull request πιο περίπλοκή αλλά και να κάνει την εικόνα να μην φαίνεται σε περίπτωση που αφαιρεθεί στο μέλλον  όπως φαίνεται και στο [pull  request]( https://github.com/ioniodi/all_collections/pull/26) μου.
![image](https://user-images.githubusercontent.com/72515420/159133698-c42082d6-6198-4020-9138-132b322c5b0c.png)

**Comment by p17gera1** [comment]
Εντάξει, σε ευχαριστώ πολύ για την τοποθέτηση σου. Αν είναι δεν θα προσθέσω την εικόνα όπως έκανες και εσύ στην δικιά σου ανακοίνωση.

**Comment by vivikara** [comment]
Πολύ ωραία η παρατήρηση σου.
