### ISSUE TITLE
Προσθήκη νέου χρήσιμου συνδέσμου

### ISSUE THREAD

**Issue by p17papa** [ioniodi/sitegr#357]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Πρόκειται να προσθέσω στο footer της σελίδας (Χρήσιμοι σύνδεσμοι) τη σελίδα της φοιτητικής μέριμνας.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p17simt @axilleasmandravelis 
- Σχετικοί σύνδεσμοι (https://care.ionio.gr/):

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά.

**Comment by p17simt** [comment]
Πολύ καλή η προσθήκη σου. Όντως κάτι που απουσιάζει από τη σελίδα

**Comment by axilleasmandravelis** [comment]
Βάλε στον τίτλο τι σύνδεσμο θα προσθέσεις και απο εμένα είναι μια χαρά για να συνεχίσεις.

**Comment by epidrome** [comment]
νομίζω πως δεν είναι καλή ιδέα να αναπαράγουμε όλους τους συνδέσμους του κεντρικού εδώ

γνωρίζω ότι ήδη το έχουμε κάνει σε έναν βαθμό, με το σκεπτικό ότι αυτοί οι σύνδεσμοι χρειάζονται πολύ συχνά, π.χ., γραμματεία-λογισμικό

αν δεχτούμε αυτήν την προσθήκη τότε θα πρέπει να δεχθούμε και άλλη μια για τον αθλητισμό και την βιβλιοθήκη και τα δίκτυα οπότε στο τέλος θα φτιάξουμε το κεντρικό

σίγουρα θα βρείτε, με λίγο προσοχή, εκτός από πιθανές προσθήκες, και πολλά λάθη που χρειάζονται διόρθωση στην ανεπίσημη σελίδα
