### ISSUE TITLE
Προσθήκη ανακοίνωσης "Ενημέρωση φοιτητών για το Πρόγραμμα Πρακτικής Άσκησης, την Πέμπτη 24/03 και ώρα 17.00"

### ISSUE THREAD

**Issue by p19papa4** [ioniodi/sitegr#360]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Θα ήθελα να προσθέσω μία νέα ανακοίνωση από την επίσημη ιστοσελίδα του τμήματος 
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @Mnlsvt και @p19biza
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [η ανακοίνωση](https://di.ionio.gr/gr/news/23693/), [σχετικός σύνδεσμος](https://github.com/ioniodi/sitegr/issues/355)

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by Mnlsvt** [comment]
Συμφωνω με την προσθηκη.

**Comment by p19biza** [comment]
Η προσθήκη του @p19papa4 μου φαίνεται σωστή.

**Comment by diogenisAl** [comment]
@p19papa4 ρίξε μια ματιά σε αυτό το σχόλιο: [https://github.com/ioniodi/sitegr/issues/364#issuecomment-1079893172](https://github.com/ioniodi/sitegr/issues/364#issuecomment-1079893172)

**Comment by p19papa4** [comment]
Το ειδα το σχολιο και νομιζω οτι η ανακοινωση που θελω να προσθεσω δεν ειναι απλα μια γενικη ανακοινωση που σχετιζεται με το τμημα αλλα ειναι αναγκαια να υπαρχει αφου η πρακτικη ασκηση θεωρειται σαν μαθημα επιλογης που εχουν επιλεξει οι φοιτητες του τμηματος και θα ηθελαν να ασχοληθουν με αυτη.

**Comment by diogenisAl** [comment]
@p19papa4 δεν έχω κάποια αντίρρηση ως προς την αξία της ανακοίνωσης, αλλά ως προς το κριτήριο ενσωμάτωσής της.
Ακόμα και αν πάρεις τώρα το green light, εκτιμώ ότι αργότερα δεν θα περάσει το pull request λόγω της ανωτέρω ενημερωμένης οδηγίας.

**Comment by p19papa4** [comment]
Να περιμενω και τα σχολια του @epidrome ή να το κλεισω αυτο το θεμα και να βρω να κανω μια αλλη προσθηκη;

**Comment by diogenisAl** [comment]
@p19papa4 αν έχεις έτοιμη μια πιο σίγουρη εναλλακτική, θα πρότεινα να προχωρήσεις σε αυτήν.
Σε κάθε περίπτωση, μπορείς να περιμένεις απάντηση από τον @epidrome
