### ISSUE TITLE
Update ερευνητικών ενδιαφερόντων στον κύριο Κωνσταντίνο Οικονόμου.

### ISSUE THREAD

**Issue by odysseasp2019060** [ioniodi/sitegr#361]
### Δήλωση Θέματος
- Προσθήκη 4 ερευνητικών ενδιαφερόντων αλλά και αφαίρεση ενός το οποίο δεν υπάρχει στην επίσημη σελιδα.
- Εκτιμώμενη δυσκολία: very easy.
- Σχετικοί συνεργατές: @P2019030 @Angeloth1
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): επίσημη: https://di.ionio.gr/gr/department/staff/334-oikonomou/ ανεπίσημη: https://epic-hamilton-da9ac8.netlify.app/people/okon/

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Angeloth1** [comment]
Μου φαίνεται μια χάρα, περίμενε όμως και ένα δεύτερο review είτε από τον @P2019030 ή ακόμη και από κάποιον διδάσκοντα
