### ISSUE TITLE
Προσθήκη ανακοίνωσης "Στις πρώτες θέσεις του ενδιαφέροντος των φοιτητών το ΜΠΣ στη Βιοπληροφορική και Νευροπληροφορική"

### ISSUE THREAD

**Issue by p17matt** [ioniodi/sitegr#362]
### Δήλωση Θέματος
- Προσθήκη ανακοίνωσης "Στις πρώτες θέσεις του ενδιαφέροντος των φοιτητών το ΜΠΣ στη Βιοπληροφορική και Νευροπληροφορική" απο την ιστοσελίδα 
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @Sola1r3
- Σχετικά σύνδεσμοι: [επίσημη ιστοσελίδα](https://di.ionio.gr/gr/news/23690/), προηγούμενα σχετικά θέματα [1](https://github.com/ioniodi/sitegr/issues/273):

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p17matt** [comment]
[Demo](https://boisterous-travesseiro-993758.netlify.app/posts/2022/03/22/viopliroforiki-kai-neuropliroforiki/)

**Comment by Sola1r3** [comment]
Μπράβο σου φαίνεται πως όλα λειτουργούνε σωστά.

**Comment by diogenisAl** [comment]
@p17matt χρειάζεσαι 2 σχετικούς συνεργάτες
