### ISSUE TITLE
Ενημέρωση βιογραφικού του καθηγητή Δημήτριου Ρίγγα

### ISSUE THREAD

**Issue by P2019030** [ioniodi/sitegr#363]
### Δήλωση Θέματος
- Σκοπεύω να προσθέσω τα μαθήματα Εισαγωγή στον Προγραμματισμό ,Τεχνολογία Λογισμικού, Ανάκτηση Πληροφορίας, Έξυπνα Περιβάλλοντα και Εφαρμογές, Γραφικά με Υπολογιστές και Τεχνητή Νοημοσύνη στο βιογραφικό του [Δ.Ρίγγα](https://epic-hamilton-da9ac8.netlify.app/people/riggas/).Η πληροφορία πάρθηκε απο την επίσημη [ιστοσελίδα](https://di.ionio.gr/gr/department/staff/576-ringas/) του ιονίου πανεπιστημίου. Η αλλαγή θα γίνει στο [_courses](https://github.com/mariosconsta/all_collections/tree/2015002/_courses)
- Εκτιμώμενη δυσκολία:  very easy
- Σχετικοί συνεργατές: @odysseasp2019060 @voltmaister 
- Σχετικά σύνδεσμοι : [Ενημέρωση στο προφίλ του κ.Ανδρόνικου #366](https://github.com/ioniodi/sitegr/issues/366),
       [Ενημέρωση βιογραφικού στο προφίλ του καθηγητή Εμμανουήλ Μαραγκουδάκη #268](https://github.com/ioniodi/sitegr/issues/268)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [ ] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@P2019030 στον σχετικό σύνδεσμο θα πρέπει να βάλεις την επίσημη ιστοσελίδα με την πληροφορία. Επίσης, θα πρέπει να εμπλουτίσεις το 1o post με άλλα σχετικά issues
