### ISSUE TITLE
Προσθήκη ανακοίνωσης "Το Ιόνιο Πανεπιστήμιο ανοίγει δρόμους στα Ηνωμένα Αραβικα Εμιράτα, με τη συμμετοχή του στην έκθεση «Dubai Expo 2020»"

### ISSUE THREAD

**Issue by P17mits1** [ioniodi/sitegr#364]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα ήθελα να προσθέσω μία νέα ανακοίνωση απο το site τμήματος
- Εκτιμώμενη δυσκολία:  easy, 
- Σχετικοί συνεργατές: @
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): Η ανακοίνωση: (https://di.ionio.gr/gr/news/23689/) , σχετικό θέμα: (https://github.com/ioniodi/sitegr/issues/151)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@P17mits1 δεν έχεις προτείνει σχετικούς συνεργάτες

**Comment by epidrome** [comment]
σύμφωνα με τις ενημερωμένες οδηγίες και σχετικό σχόλιο https://github.com/ioniodi/sitegr/issues/273#issuecomment-1079068353 οι γενικές ανακοινώσεις που σχετίζονται με το ίδρυμα-σχολή δεν γίνονται δεκτές

η ιστοσελίδα είναι γεμάτη μικρά λάθη-προβλήματα που μπορείτε να συνεισφέρετε
