### ISSUE TITLE
Προσθήκη του καθηγητή Μυλωνά Ναούμ στο προσωπικό.

### ISSUE THREAD

**Issue by Mnlsvt** [ioniodi/sitegr#365]
### Δήλωση Θέματος
- Σύντομη περιγραφή: Προσθήκη του κυρίου Ναούμ Μυλωνά ως διδάσκοντα στο μάθημα καινοτομία και επιχειρηματικότητα.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19papa4 @p19biza

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p19papa4** [comment]
Συμφώνω με την προσθήκη

**Comment by diogenisAl** [comment]
@Mnlsvt 
1. πρόσθεσε τον κ. Μυλωνά στον τίτλο του issue.
2. Συμπλήρωσε το 1o post με συνδέσμους: της επίσημης ιστοσελίδας που φαίνεται η πληροφορία, αρχεία που αλλάζουν, σχετικά issues κ.λπ. (παραπάνω έχεις τσεκάρει ότι το έκανες ήδη)

**Comment by Mnlsvt** [comment]
Κλείνω αυτό το issue διότι ο κ.Μυλωνάς δεν υπάρχει στο επίσημο site του πανεπιστημίου και δεν μπορώ να κάνω την αλλαγή.
