### ISSUE TITLE
Ενημέρωση στο προφίλ του κ.Ανδρόνικου

### ISSUE THREAD

**Issue by sosukesama** [ioniodi/sitegr#366]
### Δήλωση Θέματος
- Προσθήκη email του κ.Ανδρόνικου. Η αλλαγή θα γίνει [εδω](https://github.com/sosukesama/all_collections/blob/master/_people/andronikos.md).
 Επίσης παραθέτω το [Live Demo](https://iridescent-meerkat-2da523.netlify.app/people/andronikos/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @CptMike @Sola1r3
- Σχετικά σύνδεσμοι : #268 #363 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Sola1r3** [comment]
Όλα φαίνεται πως λειτουργούνε σωστά. Μπράβο σου καλή δουλειά.

**Comment by CptMike** [comment]
Okay και απο εμένα. Καλή αρχή.
