### ISSUE TITLE
Προσθήκη φωτογραφίας στον καθηγητή Αθανάσιο Τσίπη

### ISSUE THREAD

**Issue by p19papa4** [ioniodi/sitegr#369]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Η δικιά μου προσθήκη θα γίνει επειδή δεν έχει φωτογραφία ο κ. Αθανάσιος Τσίπης.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @mnlsvt και @p19biza
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/240) 
[βιογραφικό κ. Τσίπη](https://eliki.ionio.gr/~okon/?page_id=842) 
[link ανεπίσημης ιστοσελίδας](https://epic-hamilton-da9ac8.netlify.app/people/atsipis/) 
[το αρχείο που θα τροποποιήσω](https://github.com/ioniodi/sitegr/tree/master/assets/images)
### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@p19papa4 πρόσθεσε στο 1ο post τα links:
1. της επίσημης ιστοσελίδας του τμήματος που έχει την πληροφορία (φωτογραφία)
2. της ανεπίσημης ιστοσελίδας που λείπει η φωτογραφία
3. το αρχείο που θα τροποποιήσεις

**Comment by p19papa4** [comment]
Προσθέσα τα links που θέλατε αλλά επειδή δεν υπάρχει ο κ. Τσίπης στην επίσημη ιστοσελίδα, έχω βάλει το βιογραφικό του απο το οποίο θα πάρω την φωτογραφία.

**Comment by diogenisAl** [comment]
@p19papa4 περιμένουμε την ανταπόκριση από @Mnlsvt και @p19biza

**Comment by Mnlsvt** [comment]
Συμφωνω κι εγω με την προσθηκη.

**Comment by p19biza** [comment]
Η προσθήκη μου φαίνεται σωστή
