### ISSUE TITLE
Ορισμός του κ. Χριστόφορου Νταντογιάν ως υπευθύνου πρακτικής άσκησης του τμήματος πληροφορικής.

### ISSUE THREAD

**Issue by Mnlsvt** [ioniodi/sitegr#370]
### Δήλωση Θέματος
- Θα αλλάξω τον υπεύθυνο πρακτικής άσκησης του τμήματος  από τον κ. Θεόδωρο Ανδρόνικο στον κ. Χριστόφορο Νταντογίαν (η αλλαγή θα γίνει στο μάθημα "Πρακτική άσκηση" του ΣΤ εξαμήνου).
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19papa4 @p19biza
- Σχετικοί σύνδεσμοι: 
      -Στο [official site](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/666/) του Ιονίου πανεπιστημίου δεν έχει ανανεωθεί ο υπεύθυνος πρακτικής άσκησης ακόμη αλλά στον [επίσημο οδηγό](https://di.ionio.gr/gr/studies/undergraduate-studies/internship/) φαίνεται πως είναι ο κ.Χριστόφορος Νταντογιάν (στην πέμπτη διαφάνεια του σχετικού pdf).

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by diogenisAl** [comment]
@Mnlsvt τα checkboxes δεν είναι σωστά συμπληρωμένα σε markdown, με αποτέλεσμα να φαίνονται πειραγμένα

**Comment by Mnlsvt** [comment]
Διορθώθηκαν τα checkboxes.

**Comment by diogenisAl** [comment]
@Mnlsvt περιμένουμε την ανατροφοδότηση από @p19papa4 και @p19biza

**Comment by p19papa4** [comment]
Συμφωνώ με την προσθήκη

**Comment by p19biza** [comment]
Η προσθήκη του @Mnlsvt είναι σωστή
