### ISSUE TITLE
Τροποποίηση της σελίδας καθηγητών στο pibook

### ISSUE THREAD

**Issue by CptMike** [ioniodi/sitegr#375]
### Δήλωση Θέματος

Βλέποντας τη σελίδα των καθηγητών [εδω](https://epic-hamilton-da9ac8.netlify.app/people/), μου φαίνεται πως θα μπορούσε να τροποποιηθεί και να γίνει πολύ καλύτερη στο θέμα της παρουσίασης. Κατά τη γνώμη μου, είναι μια μεγάλη σελίδα και χρειάζεται μια καλύτερη οργάνωση. Αντί ο χρήστης να κάνει scroll down, θα μπορούσαν να υπάρχουν κατηγορίες (π.χ. καθηγητές, αναπληρωτές καθηγητές κ.ο.κ). 

Έτσι όπως το σκέφτομαι, θα έβαζα αρχικά τις κατηγορίες έτσι ώστε όταν ο χρήστης κλικάρει μια κατηγορία προσωπικού, τότε να εμφανίζονται οι καθηγητές. 
 
- Εκτιμώμενη δυσκολία: medium
- Σχετικοί συνεργατές: @mariosconsta @solair3

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
πράγματι, η σελίδα αυτή μπορεί να βελτιωθεί, τα προβλήματα τα οφείλονται σε προηγούμενη υλοποίηση που έχει γίνει στο αρχικό site-gr από συναδέλφους αλλά δεν μας δίνει τους αντίστοιχους συνδέσμους για να δούμε το ιστορικό και να αξιολογήσουμε τεκμηριωμένα την πρόταση σου

επίσης, η πρόταση σου είναι πολύ ασαφής αναφορικά με την υλοποίηση αφού δεν δίνεις κάποιο σύνδεσμο προς τους μηχανισμούς που θα χρησιμοποιήσεις, θα είναι μια από τις υπάρχουσες βιβλιοθήκες του θέματος ή κάτι νέο;

**Comment by CptMike** [comment]
> τα προβλήματα τα οφείλονται σε προηγούμενη υλοποίηση που έχει γίνει στο αρχικό site-gr από συναδέλφους αλλά δεν μας δίνει τους αντίστοιχους συνδέσμους για να δούμε το ιστορικό και να αξιολογήσουμε τεκμηριωμένα την πρόταση σου
 
Επιτρέψτε μου να διαφωνήσω. Εφόσον αυτή η σελίδα χρειάζεται βελτίωση, δε βρίσκω το νόημα στο να ψάξω 186 closed issues, για να βρώ μια ημιτελή / λάθος δουλειά που έγινε στο παρελθόν. Εγω είδα και θέλω να αντιμετωπίσω τη σελίδα σαν ένα κομμάτι που χρειάζεται βελτίωση.


> επίσης, η πρόταση σου είναι πολύ ασαφής αναφορικά με την υλοποίηση αφού δεν δίνεις κάποιο σύνδεσμο προς τους μηχανισμούς που θα χρησιμοποιήσεις, θα είναι μια από τις υπάρχουσες βιβλιοθήκες του θέματος ή κάτι νέο;

Αν δε κάνω λάθος, στο issue αναφέρεται η ιδέα. Επίσης, όπως έχετε πει και εσείς, υπάρχουν πολλοί τρόποι για να υλοποιηθεί μια ιδεα. Εγω έχω κάποιους τρόπους στο μυαλό μου, οι οποίοι μπορεί να δουλέψουν, αλλά μπορεί και όχι. Οπότε δε μπορώ να ξέρω απο τώρα τι βιβλιοθήκες θα χρησιμοποιήσω. Αυτό δεν είναι και το νόημα του μαθήματος; Ιδέα --> προσπάθεια για υλοποίηση.

Εφόσον δε θα δουλέψω κατευθείαν πάνω στο master, δε βρίσκω το λόγο να μη με αφήσετε να κάνω μια προσπάθεια. Εξάλλου, αν κρίνετε μετά ότι θέλει βελτίωση, συζητάμε πάλι για αλλαγές.

**Comment by epidrome** [comment]
συγνώμη κάπου χάθηκε αυτό γιατί νόμιζα το έβλεπε ο @diogenisAl που είχε την ανάθεση

θέλουμε περισσότερες πληροφορίες και ντέμο όχι τόσο για το πράσινο φως αλλά για να μην κάνουμε νέα συζήτηση τύπου "αφού μου δώσατε πράσινο φως τώρα πρέπει να δεχτείτε την δουλειά"

δεν το ζητάμε αυτό προσωπικά από εσένα είναι μέρος των κανόνων του έργου και όσοι έχουν προχωρήσει αυτό το παραδοτέο το έχουν κάνει με συνέπεια στους κανόνες του έργου

αν δεν σου αρέσουν οι κανόνες αυτού του έργου λογισμικού μπορείς να το αφήσεις εδώ ή να ανοίξεις μια συζήτηση όπου θα συζητήσουμε με την κοινότητα τους νέους κανόνες
