### ISSUE TITLE
Προσθήκη σελίδας "ακαδημαϊκό ημερολόγιο"

### ISSUE THREAD

**Issue by KuhakuNeko** [ioniodi/sitegr#376]
### Δήλωση Θέματος
- Θα προσθέσω μία νέα σελίδα που θα αφορά το ακαδημαϊκό ημερολόγιο του τμήματος, παρόμοια με αυτή που έχει η επίσημη ιστοσελίδα [εδώ](https://di.ionio.gr/gr/news/academic-calendar/). Η σελίδα αυτή θα έχει πληροφορίες για την περίοδο της αντίστοιχης εξεταστικής, τις αργίες και ίσως ημερομηνίες για άλλα σημαντικά events του πανεπιστημίου.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργάτες: @Orfeaslambrou @fireleaf22
- Σχετικοί σύνδεσμοι: [link στην επίσημη ιστοσελίδα](https://di.ionio.gr/gr/news/academic-calendar)

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [X] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
γιατί θεωρείς πως είναι δύσκολο αφού είναι μια σελίδα με στατική πληροφορία, χωρίς κώδικα;

για τον εντοπισμό θέματος 2ου παραδοτέου θα πρέπει να μελετηθούν αναλυτικά τα αντίστοιχα παλιότερα αιτήματα που βρίσκονται κυρίως στο site-gr

υπάρχουν αρκετά που έχουν μείνει στην μέση, ή δεν έγιναν, ενώ υπάρχουν και αρκετά bugs

γενικά η προσθήκη κάτι νέου είναι δύσκολη ή περιττή, οπότε αξίζει να κοιτάξουμε σε βάθος τι βελτιώσεις μπορούν να γίνουν.

**Comment by KuhakuNeko** [comment]
@epidrome 
> γιατί θεωρείς πως είναι δύσκολο αφού είναι μια σελίδα με στατική πληροφορία, χωρίς κώδικα;

Αρχικά να σας πω πως η ιδέα είναι να έχει κώδικα, αλλά ακόμα το δουλεύω. Έβαλα ότι είναι δύσκολο ακριβώς γι' αυτό τον λόγο, επειδή jekyll άρχισα να μαθαίνω στα πλαίσια αυτού του μαθήματος πρώτη φορά. Τώρα, μέσα από tutorials, ψάχνοντας online, και παρακολουθώντας το αποθετήριο μαθαίνω περισσότερα για το jekyll, το yaml, και για τον κώδικα liquid. Εφόσον δεν το θεωρώ easy έβαλα hard (θεώρησα πως οι δυσκολίες είναι fixed).

Με αυτό το σκεπτικό στατική σελίδα μπορεί να θεωρηθεί και αυτή με τα προγράμματα εξαμήνων που υπάρχει στο site και συνεχίζει να διατηρείται και να ενημερώνεται. Στο μυαλό μου είχα, και έχω ήδη ξεκινήσει την υλοποίηση, πως ο κώδικας θα ήταν παρόμοιος με αυτής της σελίδας με τα προγράμματα απλώς σε ένα μικρότερο scale. Δεν θα ήταν copy paste html κώδικας, ακολουθώ την πρακτική του αποθετηρίου, και τα δεδομένα του ημερολογίου δεν είναι στάσιμα κάθε χρόνο. Ακόμα, από τις οδηγίες καταλαβαίνω ότι νέες σελίδες είναι εντός του 2ου παραδοτέου. Οπότε πώς είναι δυνατόν να θεωρείται εκτός, και να πρέπει οπωσδήποτε να "εντοπίσω" ένα θέμα;

> υπάρχουν αρκετά που έχουν μείνει στην μέση, ή δεν έγιναν, ενώ υπάρχουν και αρκετά bugs

Δηλαδή πρέπει όλοι μας να επαναλάβουμε ότι άφησαν οι παλιοί πίσω και δεν τελείωσαν ή είναι σε κατάσταση χάους; Μόνο επανάληψη παλαιών ιδεών; Δεν μπορεί κάποιος να σκεφτεί κάτι δικό του και να προσπαθήσει να το κάνει; Γιατί, καταλαβαίνω ότι οι οδηγίες λένε ότι υπάρχουν πολλά θέματα που δεν κατέληξαν να υλοποιούνται όμως δεν λένε να πάρουμε υποχρεωτικά ότι υπάρχει από παλιά.

> γενικά η προσθήκη κάτι νέου είναι δύσκολη ή περιττή

Πάλι, αυτό δεν το καταλαβαίνω. Δηλαδή αν κάτι είναι δύσκολο δεν μπορούμε να το επιχειρήσουμε; Θέλουμε μόνο εύκολα θέματα; Ακόμα, το περιττή αφορά την συνεισφορά; Διότι εγώ το να υπάρχει αυτή η σελίδα το θεωρώ πολύ πιο handy και ουσιώδες από το να αλλάξει ας πούμε το χρώμα σε μία σελίδα ή να μετακινήσω πράγματα. Επίσης πιστεύω δεν γίνετε όλα τα θέματα να είναι για 10 βαθμολογικά.

Τέλος δεν καταλαβαίνω γιατι να μπουν τόσες ετικέτες όπως το invalid και το noisy history σε ένα απλό issue (π.χ. νόμιζα ότι το noisy history αφορά τα commit όπως λέει η περιγραφή του).

Μετά από τις διευκρινίσεις μου, δεν μπορώ να προχωρήσω στο θέμα που ήδη έχω σκεφτεί και έχω ξεκινήσει προσπάθεια υλοποίησης;;

**Comment by epidrome** [comment]
συγνώμη, η μια ετικέτα μπήκε κατά λάθος, προφανώς δεν έχει σχέση με την συζήτηση εδώ αφού είναι για τα αιτήματα ενσωμάτωσης

ευχαρίστως να συζητήσουμε και από κοντά το θέμα αλλά με τα δεδομένα που βλέπω μέχρι τώρα δεν θέλουμε να φτιάξουμε μια ακόμη πυραμίδα (κατά άλαν κέη), σίγουρα όχι πριν λύσουμε προβλήματα που έχουν τα θεμέλια..
