### ISSUE TITLE
Τροποποίηση του footer της ιστοσελίδας

### ISSUE THREAD

**Issue by mariosconsta** [ioniodi/sitegr#377]
### Δήλωση Θέματος
- Βλέποντας τη γενική ιστοσελίδα παρατήρησα πως το footer είναι τεράστιο (βλέπετε την παρακάτω εικόνα). Παίρνει πάρα πολύ χώρο και είναι αισθητικά κακό. Σκοπός μου είναι να αλλάξω το layout του footer, είτε με drop-down menus, ή να ενώσω για παράδειγμα τα [Μαθήματα Προπτυχιακό (Π)] σε ένα, κλπ. Αυτό ίσος απαιτεί να προσθέσω έξτρα σελίδες και για αυτό βάζω δυσκολία hard.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @CptMike @solair3
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Ιστοσελίδα](https://epic-hamilton-da9ac8.netlify.app/)

![image](https://user-images.githubusercontent.com/22726730/161925674-1b762d4e-da6e-4283-af3d-018bfd13f145.png)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
αρχικά δες το αποθετήριο site-gr όπου είχε γίνει η σχετική συζήτηση και υλοποίηση και βάλε τον σχετικό σύνδεσμο, ώστε να μην μιλάμε στον αέρα, αυτό που βλέπεις έχει μια ιστορία και ένα σκεπτικό, για το οποίο φαίνεται πως έχεις άγνοια

πάντως η διατύπωση του θέματος είναι ασαφής αφού δεν συνοδεύεται από κάποιο ντέμο ούτε ενδεικτικές οθόνες πως το φαντάζεσαι, τα νέα μενού θέλουν νέες βιβλιοθήκες javascript? ενώ και η άποψη σου για την αισθητική είναι κάπως υποκειμενική

στο αποθετήριο site-gr θα βρεις σχετικά θέματα και προβλήματα που ίσως αξίζουν περισσότερο
