### ISSUE TITLE
Προσθήκη μαθήματος Ελεύθερης Επιλογής "Μουσείο και Κοινωνικά Δίκτυα" του Η' εξαμήνου

### ISSUE THREAD

**Issue by p18kout** [ioniodi/sitegr#378]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Για το 8ο παραδοτέο επέλεξα την προσθήκη του μαθήματος "Μουσεία και Κοινωνικά Δίκτυα" του Η' εξαμήνου στο site του τμήματος. Δημιούργησα το κατάλληλο αρχείο md του μαθήματος. **Σύνδεσμος επίσημης ιστοσελίδας:** https://ilam.ionio.gr/gr/studies/undergraduate/courses/1140/ , **Σύνδεσμος προσθήκης:** https://github.com/p18kout/all_collections/blob/master/_courses/museum-and-social-media.md
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19verg , @vasiliskampani
- Σχετικά σύνδεσμοι: https://github.com/ioniodi/sitegr/issues/349 , https://github.com/ioniodi/sitegr/issues/356

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [X] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by vasiliskampani** [comment]
Θα ήθελα να προσθέσεις το demo σου και τον σύνδεσμο της επίσημης ιστοσέλιδας που έκανες τις αλλαγές για να αξιολογήσουμε καλύτερα!

**Comment by p19verg** [comment]
@p18kout Καλό θα ήταν να το περιγράψεις λίγο πιο αναλυτικά στην σύντομη περιγραφή για να είναι κατανοητό τι θες να κάνεις και για ποιο μάθημα δίχως να χρειάζεται να διαβάζεις την επικεφαλίδα.Πάντως πολύ καλή παρατήρηση!!

**Comment by p18kout** [comment]
Έγιναν οι απαραίτητες αλλαγες !

**Comment by vasiliskampani** [comment]
> Έγιναν οι απαραίτητες αλλαγες !

Πράγματι έκανες κάποιες ενημερώσεις που χρειαζόντουσαν ωστόσο με προβληματίζουν κάποια πράγματα:

* Το μάθημα δεν είναι του τμήματος πληροφορικής όποτε δεν γνωρίζω εάν πρέπει να μπει στην ιστοσελίδα μας.  Όπως βλέπεις και [εδώ](https://epic-hamilton-da9ac8.netlify.app/courses/free-choice/) δεν προσθέτουμε τα μαθήματα ελεύθερης επιλογής απλά υπάρχει η επιλογή ελεύθερου μαθήματος  που μπορεί να επιλέξει ένας φοιτητής πληροφορικής σε αυτό το εξάμηνο.

* Σύμφωνα και με την [επίσημη ιστοσελίδα του πανεπιστημίου](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/) δεν βλέπω στο Η' εξάμηνο να έχει ελεύθερης επιλογής, μόνο στο Β'.

* Το θέμα που έχεις επιλέξει δεν ξέρω αν καλύπτει τα κριτήρια του δεύτερου αιτήματος ενσωμάτωσης επειδή δεν αρκεί μια απλή προσθήκη στο αποθετήριο sitegr άλλα να γίνει μία αλλαγή στο [ioniodi/minimal-ionio](https://github.com/ioniodi/minimal-ionio/) , χωρίς να είμαι απόλυτα σίγουρος ***το λέω με βάση τις οδηγίες*** .


Να σχολιάσει και ο @p19verg πάνω σε αυτά που έγραψα εάν συμφωνεί ή όχι επειδή κάτι μπορεί να μου διέφυγε

**Comment by p19verg** [comment]
Δυστυχώς όντως δεν καλύπτει πλήρως τις απαιτήσεις για άριστη βαθμολόγηση, ωστόσο μετράει ως αλλαγή, οπότε αν δεν στοχεύεις για το δέκα δεν νομίζω να υπάρχει θέμα. Τώρα, σχετικά με το θέμα ότι δεν είναι του πανεπιστημίου, συμφωνώ ότι μπορεί να προκαλέσει κανένα πρόβλημα εφόσον δεν είναι μάθημα του κλάδου της πληροφορικής αλλά γενικά του πανεπιστημίου, για να έχεις το κεφάλι σου ήσυχο καλό θα ήταν να ρωτήσεις τους διδάσκοντες.

**Comment by vasiliskampani** [comment]
Πολύ φοβάμαι, πέρα από το μπέρδεμα που θα προκαλέσει εάν προστεθεί στο site, δεν πιστεύω πως θα βαθμολογηθεί καν ως δεύτερο αίτημα ενσωμάτωσης . Ωστόσο εάν δεν ανοίξεις καινούργιο θέμα βάλε το συγκεκριμένο στην **αναφορά** σου και ας μην το ολοκλήρωσες , κάτι μπορείς να πιάσεις.

**Comment by vasiliskampani** [comment]
Πολύ φοβάμαι, πέρα από το μπέρδεμα που θα προκαλέσει εάν προστεθεί στο site, δεν πιστεύω πως θα βαθμολογηθεί καν ως δεύτερο αίτημα ενσωμάτωσης . Ωστόσο εάν δεν ανοίξεις καινούργιο θέμα βάλε το συγκεκριμένο στην **αναφορά** σου και ας μην το ολοκλήρωσες , κάτι μπορείς να πιάσεις. Και όπως είπε και ο @p19verg ρώτα τους καθηγητές καλύτερα εάν έχεις αμφιβολίες.

**Comment by diogenisAl** [comment]
@p18kout γενικά φαίνεται πως η συγκεκριμένη πρόταση έχει αρκετά μειονεκτήματα. Καλύτερα να γίνει διατύπωση νέας αλλαγής.

Επίσης, οφείλω ένα μπράβο τόσο στον @p18kout για την μέχρι τώρα προσπάθεια, αλλά και στους @vasiliskampani  @p19verg για τα εύστοχα σχόλια.
