### ISSUE TITLE
Βιοπληροφορική - Αφαίρεση Duplicate

### ISSUE THREAD

**Issue by Vuxxs** [ioniodi/sitegr#379]
### Δήλωση Θέματος
- Παρατήρησα ότι η [Βιοπληροφορική](https://epic-hamilton-da9ac8.netlify.app/courses/bioinformatics/) έχει ένα λανθασμένο [duplicate](https://epic-hamilton-da9ac8.netlify.app/msc/bio/) το οποίο θα αφαιρέσω / διορθώσω. Συγκεκριμένα, αλλαγές στο ``all_collections/_msc/bio.md``
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19kavv1 @p19vrou
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #362 #252 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19vrou** [comment]
Δε γνωρίζω αν είναι ακριβώς duplicate αλλά σίγουρα μπορείς να κάνεις αλλαγές ώστε να ισοδυναμούν στο ίδιο αρχείο για να εμφανίζονται σωστά πράγματα όπως ο κωδικός του μαθήματος, το εξάμηνο κλπ. Οπότε, πιστεύω είναι εντάξει το issue σου, απλά σίγουρα να δούμε αν θα πάρεις το green light πρώτα.

**Comment by p19kavv1** [comment]
Νομίζω ότι ο @p19vrou πρόσθεσε κάθε παρατήρηση που θα είχα.

**Comment by diogenisAl** [comment]
@Vuxxs καλή η ιδέα, αλλά μάλλον έχει γίνει μπέρδεμα με το μεταπτυχιακό. Δες τη Βιοπληροφορικής 6ου εξαμήνου [εδώ](https://di.ionio.gr/gr/studies/undergraduate-studies/curriculum/) και τη Βιοπληροφορική 2ου εξαμήνου [εδώ](https://di.ionio.gr/pms-rds/wp-content/uploads/2019/10/%ce%a0%ce%b5%cf%81%ce%b9%ce%b3%cf%81%ce%b1%cf%86%ce%ad%cf%82-v2.pdf).

Συνεπώς, αυτό το θέμα θα ήταν καλό για το 3ο παραδοτέο, αλλά δεν φαίνεται αρκετό για το 8ο παραδοτέο
