### ISSUE TITLE
Τροποποίηση των Τίτλων των καρτέλων

### ISSUE THREAD

**Issue by AimiliosPavlidis2001** [ioniodi/sitegr#380]
### Δήλωση Θέματος
-  Στην ιστοσελίδα οι βασικοί τίτλοι για τη κάθε καρτέλα (π.χ. στη καρτέλα προσωπικό ή και στις σπουδές) δεν ξεχωρίζουν από τις υποκεφαλίδες της κάθε κατηγορίας. Παρακάτω σε  μορφή σχολίου αναπαρήστανται τόσο εικόνες απο τη βασική ιστοσελίδα, αλλά και εικόνες απο το προσωπικό μου demo με βάση τη τροποποίηση που υλοποίησα. Γνωρίζω πως το θέμα είναι αρκετά εύκολο για τη δεύτερη ενσωμάτωση, όμως θεωρώ πως είναι ιδιαίτερα σημαντικό να προστεθεί. Η αλλαγή έχει γίνει στο [minimal-ionio](https://github.com/ioniodi/minimal-ionio) και συγκεκριμένα στο [_page.scss](https://github.com/ioniodi/minimal-ionio/blob/master/_sass/minimal-mistakes/_page.scss)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19kala @p19pasc 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Βασική Ιστοσελίδα](https://epic-hamilton-da9ac8.netlify.app/)

[Demo σύνδεσμος](https://aimiliospavlidis2001-sitegr-pr2.netlify.app/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by AimiliosPavlidis2001** [comment]
**Πριν την τροποποίηση στη καρτέλα "Προσωπικό"**
![before1-proswpiko](https://user-images.githubusercontent.com/72695605/162263623-d79e3aa8-2e6a-4ca5-9e63-d5eb023b21fc.PNG)

**Έπειτα από την τροποποίηση στη καρτέλα "Προσωπικό"**
![after1-proswpiko](https://user-images.githubusercontent.com/72695605/162263771-d3b19cb7-f43c-4f49-909d-6a8e3eabd8a7.PNG)


**Πριν την τροποποίηση στη καρτέλα "Σπουδές"
![before1-spoudes](https://user-images.githubusercontent.com/72695605/162263881-267c7194-b478-4031-8594-0db984c0dfeb.PNG)

**Έπειτα από την τροποποίηση στη καρτέλα "Σπουδές"
![after1-spoudes](https://user-images.githubusercontent.com/72695605/162264036-108d7426-35a4-4b3c-bd44-8cf2449e6b63.PNG)

**Πριν την τροποποίηση στη καρτέλα "Ανακοινώσεις"
![before1-anakoinwseis](https://user-images.githubusercontent.com/72695605/162264099-a6c7bc26-3120-4865-9436-e2ca46166cbd.PNG)

**Έπειτα από την τροποποίηση στη καρτέλα "Ανακοινώσεις"
![after1-anakoinwseis](https://user-images.githubusercontent.com/72695605/162264222-3b4534c7-d02a-4bf7-8a4c-62e213ed1f48.PNG)

**Comment by p19pasc** [comment]
Σύμφωνα με τις οδηγίες είναι δεκτές και οι μικρές αλλαγές διάδρασης ενώ βρίσκονται στο minimal ionio ως 2ρο αίτημα ενσωμάτωσης. Εκτός από τις τροποποίησεις απαιτείται να έχεις κατανοήσει και το τρόπο σύνδεσης των αποθετηρίων και αρχείων, οπότε η συνολική προσπάθεια δεν είναι τόσο μικρή. Θεωρώ πως η αλλαγή σου είναι μια καλή πινελιά στην ιστοσελίδα αυτή!

**Comment by p19kala** [comment]
> Η αλλαγή έχει γίνει στο [minimal-ionio](https://github.com/ioniodi/minimal-ionio) και συγκεκριμένα στο [_page.scss](https://github.com/ioniodi/minimal-ionio/blob/master/_sass/minimal-mistakes/_page.scss)

Σε αυτο καλο θα ειναι να προσθεσεις εστω τα δικα σου αποθετηρια για να δειξεις που γινεται η αλλαγη στο αρχειο. Ειδα μια αλλαγη που εκανες το `text-align: center`, αλλα δεν ξερω αν υπηρχαν κι αλλες. Επισης, στους "σχετικους συνδεσμους" εχεις βαλει την ιστοσελιδα στην οποια εργαζομαστε, οχι την επισημη (di.ionio.gr).

Καλη προσθηκη ειναι παντως! Η ενοτητα Προσωπικο θελει πολυ φτιαξιμο στη δομη της, το οποιο αναφεραμε και στην εβδομαδιαια συναντηση και ειναι μια καλη αρχη.

**Comment by epidrome** [comment]
η αλλαγή αφορά σε αρχείο του μητρικού θέματος minimal mistakes

αν μελετήσετε προσεκτικά την τεκμηρίωση της δικιά μας προσαρμογής minimal-ionio

θα δείτε ότι οι αλλαγές στα αρχεία του μητρικού δημιουργούν πρόβλημα σε μελλοντικές αναβαθμίσεις, υπάρχουν εκτενείς σχετικές συζητήσεις στο ιστορικό που εξηγούν τους λόγους

γενικά αποφεύγουμε αυτές τις αλλαγές στο αντίγραφο μας και προτιμούμε τις προσθήκες μόνο όταν είναι πολύ σημαντικές, 

και αν τις θεωρούμε σημαντικές τις κάνουμε απευθείας στο μητρικό, δλδ minimal-mistakes
