### ISSUE TITLE
Main menu staying on top while scrolling

### ISSUE THREAD

**Issue by p19kala** [ioniodi/sitegr#382]
### Δήλωση Θέματος
- Κάνει το navigation bar να μενει στο πανω μερος της σελιδας. Εψαξα αργοτερα στα issues για παρομοια θεματα (για τους σχετικους συνδεσμους) και εντοπισα ενα που ειναι το ιδιο, αλλα παρολο που ειχε παρει το "οκ", τελικα αμεληθηκε απο τον δημιουργο. Ειναι το θεμα #206 που εχω βαλει και παρακατω. Μιας και υλοποιησα τη λειτουργια, ειπα να το βαλω να το εχουμε, αν συμφωνειτε. 
- **Αρχεια που αλλαζουν:** [main.scss](https://github.com/p19kala/minimal-ionio/blob/demo-branch/assets/css/main.scss) στη κλαση .masthead. Συγκεκριμένα οι γραμμές 12 με 15. Βαζω το `z-index` μια ακραια τιμη (999) ωστε να υπερτερει παντα οποιαδηποτε (προϋπαρχουσα ή νεα) z-index τιμη απο αλλες κλασεις και ετσι να μην επικαλύπτεται. Για να ακολουθει τη σελιδα στο πανω μερος, βαζω το `top` με τιμη 0 και το `position` μετατρεπεται από relative σε sticky. Εβαλα και ενα `background` με το χρωμα της σελιδας για να γεμισω το border. Επισης, σχολίασα το κώδικα για μελλοντικα reviews.<br>
Demo link: https://p19kalasw.netlify.app/ (καθε σελιδα εχει το νεο χαρακτηριστικο)

Σημείωση: Μετά από συζήτηση σε συνάντηση, δεν πειράζω πλέον το αρχείο minimal-mistakes. Πηγαίνω στο main.css στο path /minimal-ionio/assets/css και προσθέτω τη λειτουργία μου στην κλάση masthead η οποία από ότι βλέπω κληρονομεί την masthead του minimal-mistakes, εκτός από ο,τι αλλάξουμε/προσθέσουμε. Οπότε πιστεύω έτσι λύνεται το πρόβλημα αν το minimal-mistakes κανει update στο μέλλον, δεν θα υπάρξει conflict.

- Εκτιμώμενη δυσκολία: medium
- Σχετικοί συνεργατές: @alexpoulis @AimiliosPavlidis2001
- Σχετικοί σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #206,  #375, [το μενου στην επισημη ιστοσελιδα, αλλα χωρις την αλλαγη στο στυλ οταν γινεται scroll](https://di.ionio.gr/)

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Καθως η αλλαγη ειναι στο αποθετηριο του minimal-ionio, το PR θα γινει εκει (αν παρω green light), αλλα για τη βαθμολογηση δεν γνωριζω αν το issue πρεπει να μεινει εδω ή να μετακινηθει στο minimal-ionio. Αναμενω απαντηση και σε αυτο.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by AimiliosPavlidis2001** [comment]
@p19kala η προσθήκη σου είναι πολύ σημαντική και η υλοποίηση της ιδέας σου σύμφωνα με το demo που παρέθεσες λειτουργεί πολύ καλά. Στον mozila firefox δεν υπήρχε κανένα θέμα τόσο από κινητές συσκευές όσο και από οθόνες υπολογιστή. Στο google chrome παρατήρησα ένα πρόβλημα που δε νομίζω να οφείλεται τόσο στον κώδικά σου, αφού γενικά το navigation menu στο πάνω μέρος της σελίδας έχει θέματα στον web browser αυτόν.

Συγκεκριμένα στα κινητά σύμφωνα με τη λειτουργία **inspect**:

Το menu παρουσιάζεται έτσι:

![προβλημα-chrome](https://user-images.githubusercontent.com/72695605/162624469-a6d5387f-e1ec-4739-b3ff-8acbc2425ffb.PNG)

Και όταν κάποιος πατήσει το σημαδάκι για να φανούν όλες οι επιλογές δε φαίνονται κάποιες από αυτές:

![προβλημα-chrome-v2](https://user-images.githubusercontent.com/72695605/162624514-ba5fcd39-7f60-4fb5-aa6e-7677075d1d76.PNG)

Όπως όμως διατύπωσα παραπάνω δε νομίζω να οφείλεται σε εσένα, απλώς ήθελα να το διατυπώσω για να μην υπάρχει παρεξήγηση. Έχεις κάνει πολύ καλή δουλειά και η προσθήκη σου είναι πολύ σημαντική.

Θεωρώ πως αξίζει να συνεχιστεί η διαδικασία για την ενσωμάτωση της ιδέας σου.

**Comment by p19kala** [comment]
Α ναι, αυτο το bug. Η πρωτη εικονα ειναι οντως bug και εψαξα να δω πως να το φτιαξω, αλλα χωρις επιτυχια. Φαινεται να ειναι τυχαιο το ποτε θα συμβει.

Η δευτερη δουλευει οπως πρεπει. Στο κουτακι μπαινουν οι σελιδες που "εξαφανιζονται" απο το navigation bar οταν η αναλυση ειναι πολυ μικρη και δεν χωρανε ολα τα αντικειμενα στην ιδια γραμμη. 

Ευχαριστω, συναδελφε, για την αξιολογηση!

**Comment by diogenisAl** [comment]
@p19kala 
> Αναμενω απαντηση και σε αυτο.

μπορεί να παραμείνει εδώ (κατά αναλογία με το all_collections) υπό την προϋπόθεση ότι το **closes issue** σε διαφορετικό αποθετήριο θα λειτουργήσει σωστά: [1](https://github.community/t/close-issue-with-pull-request-in-different-repository/156410) [2](https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github)

**Comment by p19kala** [comment]
Μετά από συζήτηση σε συνάντηση, δεν πειράζω πλέον το αρχείο minimal-mistakes. Πηγαίνω στο main.css στο path /minimal-ionio/assets/css και προσθέτω τη λειτουργία μου στην κλάση masthead η οποία από ότι βλέπω κληρονομεί την masthead του minimal-mistakes, εκτός από ο,τι αλλάξουμε/προσθέσουμε. Οπότε πιστεύω έτσι λύνεται το πρόβλημα αν το minimal-mistakes κανει update στο μέλλον, δεν θα υπάρξει conflict.

Παρακαλώ, αν μπορούν οι αξιολογητές να κάνουν άλλο ένα review @AimiliosPavlidis2001 @alexpoulis

**Comment by alexpoulis** [comment]
@p19kala και στο desktop και σε mobile φαίνεται να λειτουργεί κανονικά οπότε από εμένα είσαι οκ.

**Comment by AimiliosPavlidis2001** [comment]
@p19kala και από εμένα έχεις έγκριση, λαμβάνοντας υπ' όψιν το μήνυμα που έχω γράψει παραπάνω.

**Comment by epidrome** [comment]
θεωρώ πως αυτή η αλλαγή έχει τον κατάλληλο βαθμό δυσκολίας, αλλά δεν καταλαβαίνω πως βελτιώνει την ιστοσελίδα. ακόμη και αν υποθέσουμε ότι για κάποιον λόγο είναι καλή προσθήκη τότε θα πρέπει να σταλεί στο αρχικό θέμα και όχι εδώ αφού δεν προσφέρει κάτι ειδικά για την περίπτωση μας.

**Comment by p19kala** [comment]
> θεωρώ πως αυτή η αλλαγή έχει τον κατάλληλο βαθμό δυσκολίας, αλλά δεν καταλαβαίνω πως βελτιώνει την ιστοσελίδα. 

Είναι ένας εύκολος και γρήγορος τρόπος να κάνουμε περιήγηση. Για να δείτε τη χρησιμότητα του, πάτε σε μια σελίδα που έχει πολύ περιεχόμενο και κάντε scroll προς τα κάτω. Αν θέλετε να αλλάξετε σελίδα, πρέπει να ανεβείτε προς τα πάνω πάλι. Ενώ με την αλλαγή μου, αλλάζετε κατευθείαν σελίδα.
