### ISSUE TITLE
Ανανέωση Workflow οδηγιών στο Wiki

### ISSUE THREAD

**Issue by p17anto2** [ioniodi/sitegr#384]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Ανανέωση οδηγιών [Workflow στο Wiki](https://github.com/ioniodi/sitegr/wiki/Workflow). Αυτή τη στιγμή δεν αναφέρεται η ύπαρξη submodule και ο τρόπος διαχείρισής τους (υπάρχουν οδηγίες γενικά, αλλά όχι στο wiki). Επειδή αλλάζει ριζικά η διαδικασία συνεισφοράς, καθώς και είναι σημαντική αλλαγή, θεωρώ πως αρμόζει για 2ο παραδοτέο. Οι αλλαγές θα βασιστούν [σε post στα Discussions που έχω αναρτήσει](https://github.com/courses-ionio/help/discussions/544), έπειτα από ανατροφοδότηση από συμφοιτητές.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @john7665 @ApoLaz
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #209 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by ApoLaz** [comment]
Πιστεύω ότι είναι μια πάρα πολύ καλή και χρήσιμη προσθήκη για το wiki διότι είναι ένα πολύ σημαντικό κομμάτι του github και του μαθήματος. Και θα είναι ιδιαίτερα χρήσιμο και βοηθητικό γιατί πολλοί από τους συνάδερφους μας έρχονται για πρώτη φορά σε επαφή με τα submodules. Οπότε από εμένα έχεις το οκ!

**Comment by john7665** [comment]
Πολύ καλό! Από εμένα έχεις το οκ!

**Comment by epidrome** [comment]
οκ, μπορείς να το περάσεις στο γουίκι και να κάνεις όποια άλλη σχετική ενημέρωση
https://github.com/ioniodi/sitegr/wiki

**Comment by p17anto2** [comment]
Δεν βρήκα τρόπο να κάνω Pull Request, οπότε το ανέβασα και κλείνω το issue. Το αποτέλεσμα φαίνεται [εδώ](https://github.com/ioniodi/sitegr/wiki/Workflow/a2fd24063f6a157182d7ff3038fd1022da5220ae)
