### ISSUE TITLE
Προσθήκη Μαθήματος Επιλογής <<Κατανεμημένα Δικτυοκεντρικά Συστήματα>> στο προφίλ της κ. Χριστοπούλου

### ISSUE THREAD

**Issue by p19pasa** [ioniodi/sitegr#385]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Παρατηρήσαμε ότι λείπει το μάθημα <<Κατανεμημένα Δικτυοκεντρικά Συστήματα>> από την περιγραφή των μαθημάτων που διδάσκει η κ. Χριστοπούλου και θα ήθελα να το προσθέσω. Η αλλαγή θα γίνει μέσω του [submodule](https://github.com/ioniodi/all_collections/tree/master/_courses).
-  Αντίστοιχη σελίδα στον επίσημο ιστότοπο: [Προφίλ της κ. Χριστοπούλου](https://di.ionio.gr/gr/department/staff/335-christopoulou/)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19verg @PetroulaStylianou
- Σχετικά θέματα: https://github.com/ioniodi/sitegr/issues/351

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p19verg** [comment]
Γίνεται να βάλεις σαν reference 2 άτομα για το μάθημα <<Κατανεμημένα Δικτυοκεντρικά Συστήματα;

**Comment by p19pasa** [comment]
Πιστεύω πως ναι, γιατί και στην επίσημη ιστοσελίδα του Πανεπιστημίου το μάθημα υπάρχει και τον κ. Οικονόμου και στην κ. Χριστοπούλου

**Comment by epidrome** [comment]
@p19verg πως το κάνεις δεκτό χωρίς να μελετήσεις το ιστορικό;

https://github.com/ioniodi/sitegr/issues?q=author%3Ap19pasa

@p19pasa αφού έχεις κάνει το εύκολο τώρα είναι η ώρα για κάτι δύσκολο (όπως λένε οι οδηγίες)

**Comment by p19verg** [comment]
@epidrome Αν κατάλαβα σωστά θέλει να φαίνεται το μάθημα ότι το διδάσκει και η κ.Χριστοπούλου κάτι που στο ιστορικό της Ανδριάνας δεν υπάρχει ,υπάρχει απλά η προσθήκη του μαθήματος στο site γενικά

**Comment by p19pasa** [comment]
@epidrome καταλαβαίνω αυτό που λέτε απλώς θα ήθελα να ασχοληθώ με το θέμα που αναφέρω στο issue, καθώς πιστεύω ότι αξίζει να γίνει η αλλαγή που προτείνω για αυτό αναμένω το green light

**Comment by PetroulaStylianou** [comment]
Πολύ ωραία επιλογή θέματος!
