### ISSUE TITLE
Προσθήκη email του καθηγητή Γιώργου Κατωμέρη 

### ISSUE THREAD

**Issue by p19verg** [ioniodi/sitegr#387]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:Προσθήκη email του καθηγητή Γιώργου Κατωμέρη στο προφίλ σου στον κλάδο "Προσωπικό"Η αλλαγές θα γίνουν στο submodule [all_collections/_people](https://github.com/ioniodi/all_collections/tree/136ee3e7a605774d8080844cd613b55c895bd66f/_people)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19loli @odysseasp2019060
- Σχετικά θέματα:https://github.com/ioniodi/sitegr/issues/321 https://github.com/ioniodi/sitegr/issues/361
- Σχετικά σύνδεσμοι :
    Το προφίλ του κ.Κατωμέρη στην αυθεντική σελίδα του πανεπιστημίου.Πατήστε [εδώ](https://di.ionio.gr/gr/department/staff/575-katomeris/)
    Το προφίλ του κ.Κατωμέρη στην ανεπίσημη σελίδα του πανεπιστημίου.Πατήστε [εδώ](https://epic-hamilton-da9ac8.netlify.app/people/katomeris/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19verg** [comment]
Γίνεται να βάλεις σαν reference 2 άτομα για το μάθημα <<Κατανεμημένα Δικτυοκεντρικά Συστήματα;

**Comment by epidrome** [comment]
θα πρέπει να βρεις έναν τρόπο να ενεργοποιήσεις τους αξιολογητές ώστε να σχολιάσουν
