### ISSUE TITLE
Τροποποίηση του αρχείου του μαθήματος "Εξυπνα περιβαλλοντα και εφαρμογές" για να προστεθεί στην ιστοσελίδα

### ISSUE THREAD

**Issue by vasiliskampani** [ioniodi/sitegr#388]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών. Θα τροποποιήσω το αρχείο στο μάθημα **Έξυπνα περιβάλλοντα και εφαρμογές** που είχε προσθέσει παλαιότερος συμφοιτητής μου στο [all_collections](https://github.com/ioniodi/all_collections/blob/master/_courses/smart-technologies-and-applications.md/) ***αλλα δεν ήταν λειτουργικό*** στην ιστοσελίδα. Αυτο το παραδοτέο είναι το 3ο. Ελπίζω να θεωρηθώ εμπρόθεσμός ή τουλάχιστον να μου το θεωρήσετε χρονικά δεκτό σύμφωνα και με [αύτην](https://github.com/ioniodi/all_collections/pull/49/) την συζήτηση που είχαμε.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19verg , @p19pasc 
- Σχετικά σύνδεσμοι : #145
- [Σύνδεσμος](https://di.ionio.gr/gr/studies/undergraduate-studies/courses/641/) του μαθήματος στην επίσημη ιστοσελίδα
- [Σύνδεσμος](https://github.com/vasiliskampani/all_collections/blob/demo-branch-2/_courses/smart-technologies-and-applications.md/) του φακέλου που θα κάνω την αλλαγή μου
- [Σύνδεσμος](https://epic-hamilton-da9ac8.netlify.app/courses/#%CE%BC%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%B1-%CE%B5%CF%80%CE%B9%CE%BB%CE%BF%CE%B3%CE%AE%CF%82-6/) της ανεπίσημης ιστοσελίδας στο 8ο εξάμηνο πρίν την αλλαγή μου
- Το [demo](https://vasiliskampani-stap.netlify.app/courses/smart-technologies-and-applications/) μου

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p19pasc** [comment]
Έχεις έγκριση από εμένα

**Comment by p19verg** [comment]
Έκανες ολοκληρομένη παρατήρηση και πρόσθεσες όλους τους κατάλληλους συνδέσμους.Θεωρώ ότι σαν issue είναι ολοκληρομένο,μπράβο!!
