### ISSUE TITLE
Bug fix: Responsive Content στην σελίδα του Προσωπικού

### ISSUE THREAD

**Issue by Geoter711** [ioniodi/sitegr#389]
### Δήλωση Θέματος
- Όπως είχε παρατηρήσει και ο συμφοιτητής μου, το περιεχόμενο στην σελίδα του Προσωπικού δεν "αντιδράει" ανάλογα του viewport της συσκεύης, με το πρόβλημα σε μικρές οθόνες. Καθώς το green light είχε γίνει αλλά οι αλλαγές ποτέ δεν πραγματοποιήθηκαν, θα ήθελα να το ολοκληρώσω.

![image](https://user-images.githubusercontent.com/58696033/162583533-0110bbfa-4931-4a93-b2df-529bfd4af854.png)
![image](https://user-images.githubusercontent.com/58696033/162640485-87334f1d-9824-404e-a58e-9c3289a42f67.png)

Παρατήρησα ότι το πρόβλημα προκύπτει από το γεγονός ότι στο αρχείο```people-rank.html``` (https://github.com/ioniodi/minimal-ionio/blob/master/_includes/people-rank.html) τα διάφορα elements χρησιμοποιούν grid για το display τους, που παρόλο που είναι καλή επιλογή για σελίδα σε μεγάλες οθόνες, στην δικιά μας περίπτωση δημιουργεί προβλήματα. Το σκεπτικό είναι να χρησιμοποιηθούν media queries για το responsive κομμάτι. Το display θα αλλάξει από ```display: grid``` σε κάποιο άλλο είδους display (για την δικιά μας περίπτωση ίσως αρμόζει καλύτερα ```display: flex```), και αντί για την κλάση ```grid-container``` θα δημιουργήσω μία καινούρια κλάση για αυτόν τον σκοπό στο αρχείο ```main.scss``` (https://github.com/ioniodi/minimal-ionio/blob/master/assets/css/main.scss) (ίσως και να πραγματοποιηθούν αλλαγές σχετικά με την κλάση ```rank_title```, ακόμα θέλω να πειραματιστώ λίγο με τις αλλαγές).

~~Όσο αφορά το demo, σκοπεύω να το παραπέμψω σύντομα με τις αλλαγές!~~

Update: Εδώ είναι το [demo link](https://sitegr-geoter.netlify.app/people). Οι αλλαγές υπάρχουν στο εξής [branch](https://github.com/Geoter711/minimal-ionio/tree/2019145). Τελικά όντως άλλαξα το grid σε flexbox, το οποίο είχε πολύ καλά αποτελέσμα. Καθώς υπήρχαν προβλήματα με τα headings να είναι μέσα στο flexbox, αποφάσισα να τα διαχωρίσω από το container, όπως φαίνεται στο αρχείο ```people-rank.html```(https://github.com/Geoter711/minimal-ionio/blob/2019145/_includes/people-rank.html) Επίσης όντως δεν χρείαστηκε η χρήση του ```rank_title```. Το μόνο πρόβλημα μέχρι στιγμής είναι ότι για viewport width 600-767px έχει περίεργη συμπεριφορά καθώς το wrapping "σπάει" λίγο και δεν προσαρμόζει τα elements στο width (αλλά και πάλι δεν δημιουργείται το πρόβλημα από προηγουμένως). Ένα άλλο μικρότερο πρόβλημα είναι οτι το flexbox περιορίζεται σε 3 elements για τα τωρινά μεγέθη (σκοπέυω να πειραματιστώ περαιτέρω με αυτό εφόσον γίνει το green light!). Αν κάποιος συμφοιτητής έχει πρόταση προς την λύση αυτών θα ήταν σίγουρα θετικό. Μια εναλλακτική ήταν να χρησιμοποιηθεί grid έως ότου το σημειό στο οποίο χαλούσε αρκετά η ιστοσελιδά, και σε μικρότερα μεγέθη να χρησιμοποιηθεί flexbox, αλλά γρήγορα παρατήρησα ότι αυτό εμφάνιζει άλλα προβλήματα που η λύση τους δεν είναι αποδοτική ενώ θα χάθει και έως ένα σημείο η συνοχή. 

- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @alexpoulis @peteskk
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://github.com/ioniodi/sitegr/issues/189 

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by alexpoulis** [comment]
Για το bug το οποίο αναφέρεις άμα τσεκάρεις το mobile όντως θέλει να κάνεις zoom out και μετά το footer και το bar στην κορυφή της ιστοσελίδας «χαλάει»  όπως φαίνεται και στο screenshot οπότε φαίνεται σαν ένα σημαντικό θέμα. Θα περιμένω και το demo για να σου δώσω σίγουρα το οκ.
![image](https://user-images.githubusercontent.com/72515420/162619605-b9d3b366-43c9-4afc-9a5d-a855ee1870ee.png)

**Comment by Geoter711** [comment]
@alexpoulis Πολύ καλη παρατήρηση! Σκέφτηκα να το δείξω και εγώ αρχικά αλλά αποφάσισα προς όχι. Εφόσον τώρα όμως υπάρχει και στα comments, θα ήταν καλό να ύπαρχει και στο κείμενο του issue. Επίσης προστέθηκε ένα update σχετικά με το demo!

**Comment by PeteSKK** [comment]
Βλέπω οτι το σκέφτηκες το θέμα καλά. Μου αρέσει η ιδέα σου!

**Comment by diogenisAl** [comment]
Τι επιλέγεις τελικά @alexpoulis ;

**Comment by alexpoulis** [comment]
Ναι ξεχάστηκα, αλλά από ότι είδα στο demo φαίνεται καλό.
