### ISSUE TITLE
Αφαίρεση μαθήματος επιλογής ΣΤ' εξαμήνου «Μεταγλωττιστές», ένταξη νέου μαθήματος επιλογής ΣΤ' εξαμήνου «Θεωρία Γραφημάτων και Εφαρμογές».

### ISSUE THREAD

**Issue by FaidonTsetsis** [ioniodi/sitegr#39]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Το μάθημα των Μεταγλωττιστών πλέον έχει αφαιρεθεί από το ΣΤ' εξάμηνο και έχει δημιουργηθεί ένα καινούργιο μάθημα επιλογής το οποίο θα προστεθεί. με όνομα Θεωρία Γραφημάτων και Εφαρμογές.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [Χ] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [Χ] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
οι μεταγλωτιστές έχουν μεταφερθεί δεν έχουν διαγραφεί, παρακαλώ για μεγαλύτερη προσοχή, καθώς όλη η διαδικασία αξιολογείται, όπως λένε οι οδηγίες!

παρακαλώ μόνο μια αλλαγή, όχι δύο, ας κάνουν κάτι και οι άλλοι!
