### ISSUE TITLE
Χρήση θεωρίας χρωμάτων για την αλλαγή χρωμάτων του κάτω μέρους της ιστοσελίδας

### ISSUE THREAD

**Issue by PeteSKK** [ioniodi/sitegr#390]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα αλλάξω το χρώμα των γραμμάτων στο κάτω μέρος της σελίδας, εκεί που έχει γαλάζιο background, με αναφορά πάνω στην θεωρία χρωμάτων για μια πιο εύκολη ανάγνωση.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @gordthrow @Geoter711
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): 

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Σύμφωνα με την θεωρία χρωμάτων, προτείνονται κυρίως δύο τρόποι, είτε να κάνω τα γράμματα ένα παρόμοιο χρώμα με το background αλλά είτε σκούρο είτε ανοιχτό, πάντα να είναι σε αντίθεση, ή κόκκινο επειδή ταιριάζει με το συγκεκριμένο background

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Geoter711** [comment]
@PeteSKK Ενδιαφέρον ιδέα! Συμφώνω ότι όντως μία αλλαγή θα ήταν καλή καθώς όπως είναι τώρα "πετάγεται" πολύ έντονα. Θα πρότεινα ίσως παρόμοια χρώματα με αυτά που ήδη χρησιμοποιεί το πανεπιστήμιο αλλά δεν ξέρω αν σαν σκοπό θέλουμε κάτι τέτοιο ή κάτι πιο διαφορετικό! Θα ήθελα να ακούσω και την γνώμη του συνάδελφου @gordthrow σε αυτό!
