### ISSUE TITLE
Προσθήκη Ανακοίνωσης "Διαδικτυακή δράση STEM-Ρομποτικής"

### ISSUE THREAD

**Issue by P17mits1** [ioniodi/sitegr#391]
### Δήλωση Θέματος
- Στην κατηγοία των ανακοινώσεων θα προσθέσω την ανακοίνωση "Διαδικτυακή δράση STEM-Ρομποτικής".
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @p17papa @p17kots 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://di.ionio.gr/gr/news/23820/

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [X] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
θα πρέπει να βρεις έναν τρόπο να ενεργοποιήσεις τους αξιολογητές ώστε να σχολιάσουν
