### ISSUE TITLE
Προσθήκη ανακοίνωσης "Διαδικτυακό σεμινάριο της IEEE για συγγραφείς/ερευνητές στις 30 Μαρτίου"

### ISSUE THREAD

**Issue by vivikara** [ioniodi/sitegr#392]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: "Στην κατηγορία ανακοινώσεις θα προσθέσω την εξής: "Διαδικτυακό σεμινάριο της IEEE για συγγραφείς/ερευνητές στις 30 Μαρτίου"
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @perikarananou , @p17gera1 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [demo link](https://625000b24dad485759dd0367--adorable-medovik-d1a20a.netlify.app/posts/2022/03/28/diadiktiako-seminario-tis-ieee-gia-sygrafis-stis-30-martiou/), [di.ionio.gr](https://di.ionio.gr/gr/news/23727/) [σχετικό issue](https://github.com/ioniodi/sitegr/issues/273),[σχετικό issue](https://github.com/ioniodi/sitegr/issues/270)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p17gera1** [comment]
Πολύ ωραία η παρατήρηση σου, μπορείς να συνεχίσεις.

**Comment by perikarananou** [comment]
Καλή παρατήρηση!! Συνέχισε στην υλοποίηση.
