### ISSUE TITLE
Τροποποίηση του Ωρολογίου προγράμματος ΣΤ εξαμήνου- Παραδοτέο 3

### ISSUE THREAD

**Issue by xar1sgeovlacp2019059** [ioniodi/sitegr#393]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Οι αλλαγές θα γίνουν σε αυτό το αρχείο [Πρόγμαμμα ΣΤ] (https://github.com/ioniodi/all_collections/blob/136ee3e7a605774d8080844cd613b55c895bd66f/_timetables/sem_f.md), συγκεκριμένα θα αλλάζω το πρόγμαμμα γιατί κάποιες ώρες μαθημάτων είναι λανθασμένες και θα αλλάξω τους καθηγητές έτσι ώστε να ταιριάζουν στο επίσημο πρόγραμμα. [site](https://epic-hamilton-da9ac8.netlify.app/timetables/sem_f/)
το πρόγραμμα φαίνεται σωστό σε αυτό το [link](https://storied-cucurucho-77878f.netlify.app/timetables/sem_f//)
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @Geoter711 , @alexpoulis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [επίσημη ιστοσελίδα](https://di.ionio.gr/gr/students/schedule/)

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Απλά μια σημείωση: Επειδή η αλλαγή μου για το τρίτο παραδοτέο [issue](https://github.com/ioniodi/sitegr/issues/260) έγινε απο άλλο άτομο, ενώ είχα δηλώσει το issue αλλά δεν έγινε δεκτό το pull request, θα πρέπει να επαναλάβω την διαδικασία για το τρίτο παραδοτέο. 
### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@xar1sgeovlacp2019059 σε ποιο παραδοτέο αναφέρεσαι; Στο νο3 ή νο8;

**Comment by alexpoulis** [comment]
Οκ για το 3ο παραδοτέο οι αλλαγές φαίνονται καλές.

**Comment by Geoter711** [comment]
Οι αλλαγές των μαθημάτων είναι σωστές από την άποψη των ωρών! Αλλά νομίζω σε μερικούς καθηγητές έχεις βάλει τα ονόματα τους πριν την ορθή επανάληψη π.χ. Αναγνώριση Προτύπων κάνει ο κ. Βραχάτης και όχ ο κ. Βλάμος, την Παρασκευή μάθημα κάνει ο κ. Αλεξανδράκης στην Τεχνολογία Λογισμικού κτλ. Θεωρητικά μπορείς να βγάλεις και το "εξ αποστάσεως" κόμματι αλλά δεν ξέρω πως θεωρείται στα πλαίσια του issue, οπότε για τώρα προτείνω απλά αυτό με τα ονόματα!

**Comment by xar1sgeovlacp2019059** [comment]
Ωραία ολοκλήρωσα τις αλλαγές. Σχετικά με το κομμάτι του "εξ αποστάσεως", λογικά δεν είναι στα πλαίσια του issue. Σε περίπτωση που ήταν ,πιστεύω, οι αλλαγές θα είχαν μεγαλύτερη έκταση απ' ότι έπρεπε να είχαν.

**Comment by xar1sgeovlacp2019059** [comment]
Ωραία ολοκλήρωσα και αυτή την αλλαγή
