### ISSUE TITLE
social media integration: facebook

### ISSUE THREAD

**Issue by p19pasc** [ioniodi/sitegr#394]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσπάθησα να υλοποιήσω όσο καλύτερα μπορούσα το θέμα του [Wiki](https://github.com/ioniodi/sitegr/wiki/Archived-issues#%CE%94%CF%8D%CF%83%CE%BA%CE%BF%CE%BB%CE%B1) στο επίπεδο **Δύσκολο** το `social media integration: facebook`. Αυτό που κατάφερα είναι να υπάρχει ένα button στο κάτω μέρος  όλων των tabs(εκτός από τις ανακοινώσεις και την και την κεντρική).
Για να γίνει αυτό τροποποίησα το _config.yml αρχείο στο **sitegr** όπως φαίνεται στο [repository μου](https://github.com/p19pasc/sitegr/blob/aitima2-facebook/_config.yml) συγκεκριμένα έκανα τα `share: false` σε `share:true` όπου ήταν απαραίτητο(γραμμές 289,302).
Στο **minimal-ionio** τροποποίησα το [social-share.html](https://github.com/p19pasc/minimal-ionio/blob/aitima2-facebook/_includes/social-share.html) ώστε να υπάρχει μόνο το κουμπί του facebook και συγκεκριμένα έφτιαξα την εντολή `<h ref=...>` δίνοντας το κατάλληλο facebook url και σβήνοντας το κομμάτι της JS το οποίο θεωρούσα ότι δεν χρειαζόταν, διότι όταν θα κλικάραμε στο button, θα μας έκανε pop up ένα νέο παράρθυρο του browser.

Η ιστοσελίδα μου:[Netlify](https://p19pasc-aitima2-facebook.netlify.app/)

- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @AimiliosPavlidis2001 @p19kala
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): [Wiki](https://github.com/ioniodi/sitegr/wiki/Archived-issues#%CE%94%CF%8D%CF%83%CE%BA%CE%BF%CE%BB%CE%B1) (λινκ προς την επίσημη ιστοσελίδα δεν υπάρχει διότι δεν αντέγραψα την αλλαγή από εκεί)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19pasc** [comment]
Επειδή η αλλαγή δεν φαίνεται έντονα ανεβάζω αυτή τη φωτογραφία που φαίνεται το button του Facebook στο τέλος της ιστοσελίδας
![Screenshot from 2022-04-10 20-45-35](https://user-images.githubusercontent.com/72496151/162632437-57c43535-640b-42a7-ad85-684b99d68dd9.png)
.

**Comment by AimiliosPavlidis2001** [comment]
@p19pasc η αλλαγή σου φαίνεται να υλοποιήθηκε επιτυχώς όπως περιγράφεις και εσύ πέρα από τις 2 καρτέλες (όπου κάποιος άλλος μελλοντικά ίσως να μπορούσε να το επιλύσει) και για αυτό το λόγω εγκρίνω την ιδέα σου.

Μία μικρή σημείωση που δε νομίζω να ευθύνεσαι εσύ αλλά θα ήθελα να αναφέρω είναι πως στο **google Chrome** όταν ένας χρήστης σε μεγάλη οθόνη πατήσει πάνω στο εικονίδιο και έπειτα πατήσει το κουμπί επιστροφής για να επιστρέψει στην ιστοσελίδα μπορεί να μην εμφανίζεται η μπάρα στα δεξιά της οθόνης για την πλοήγηση του χρήστη.

![notice](https://user-images.githubusercontent.com/72695605/162635755-6025b1f3-8b75-4144-9725-16748892135e.PNG)

Όπως όμως διατύπωσα παραπάνω δε νομίζω να οφείλεται σε εσένα, απλώς ήθελα να το διατυπώσω για να μην υπάρχει παρεξήγηση. Η ενσωμάτωση που επιθυμείς να κάνεις έχει υλοποιηθεί αρκετά καλά και είναι πολύ σημαντική.

Θεωρώ πως αξίζει να συνεχιστεί η διαδικασία για την ενσωμάτωση της ιδέας σου.

**Comment by p19pasc** [comment]
> @p19pasc στην αρχική σελίδα και στις ανακοινώσεις δεν φαίνεται να υπάρχει το κουμπί. Επίσης, στο επίπεδο δυσκολίας **Δύσκολα**, το `social media integration: facebook` έχει συγκεκριμένη πρόταση/εστίαση: `(ad block check)`.

Θα δω μήπως μπορέσω να κάνω κάποια βελτείωση αλλιώς δεν θα μπορέσω να τα καταφέρω πλήρως

**Comment by diogenisAl** [comment]
@p19pasc καλή επιτυχία!
