### ISSUE TITLE
Δυναμική αλλαγή του background της κεντρικής σελίδας με βάση την συσκευή προβολής

### ISSUE THREAD

**Issue by p19zing** [ioniodi/sitegr#396]
### Δήλωση Θέματος
- Όπως αναφέρεται στο [Video background on home page](https://github.com/ioniodi/sitegr/wiki/Video-background-on-home-page), στην τελευταία παράγραφο (Εναλλακτικές Προσεγγίσεις), θα υλοποιήσω την πρόταση για δυναμική αλλαγή του background της κεντρικής σελίδας με βάση την συσκευή. πχ. Background video όταν ο user agent είναι PC/Laptop ή GIF/Image όταν ο user agent είναι Smartphone/Tablet. Η υλοποίηση θα γίνει κυρίως με **Javascript** στο sitegr και κατά την φόρτωση της σελίδας, αν ο user agent είναι κινητό, θα σβήνει το **iframe**  και θα το αντικαθιστά με **εικόνα**
- [Netlify link](https://p19zing-sitegr.netlify.app/). Αν μπείτε στη σελίδα με υπολογιστή βλέπετε κανονικά το βίντεο ενώ με κινητό δείχνει μια φωτογραφία του κτιρίου του τμήματος. Δεν έχω ολοκληρώσει το styling της εικόνας αλλά θα το κάνω μόλις γίνει αποδεκτό το issue.
- Εκτιμώμενη δυσκολία: **hard**
- Σχετικοί συνεργατές: @Vuxxs , @p19vrou
- Σχετικοί σύνδεσμοι: [Προσθήκη Βίντεο στο Υπόβαθρο ...](https://github.com/ioniodi/site-gr/issues/95) και [Δυναμικό περιεχόμενο στο υπόβαθρο της βασικής σελίδας](https://github.com/ioniodi/site-gr/issues/138)

### Pull Requests
[Pull request στο sitegr](https://github.com/ioniodi/sitegr/pull/400)

[Pull request στο minimal-ionio](https://github.com/ioniodi/minimal-ionio/pull/44)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by p19vrou** [comment]
Ενδιαφέρουσα ιδέα, δεν παρατηρώ κάποιο σχόλιο που χρειάζεται να κάνω αυτή την στιγμή. Μόλις πάρεις το green light, πιστεύω να μπορείς να συνεχίσεις.

**Comment by Vuxxs** [comment]
Πολύ καλή ιδέα και φαίνεται ταιριάζει για δεύτερο παραδοτέο σύμφωνα με τις παρατηρήσεις που δέχτηκα για το δικό μου.

**Comment by epidrome** [comment]
θεωρώ πως αυτή η αλλαγή έχει τον κατάλληλο βαθμό δυσκολίας, αλλά δεν καταλαβαίνω πως βελτιώνει την ιστοσελίδα. ακόμη και αν υποθέσουμε ότι για κάποιον λόγο είναι καλή προσθήκη τότε θα πρέπει να σταλεί στο αρχικό θέμα και όχι εδώ αφού δεν προσφέρει κάτι ειδικά για την περίπτωση μας.
