### ISSUE TITLE
Προσθήκη Ωρολόγιου Προγράμματος Προπτυχιακoύ Α' Εξαμήνου 

### ISSUE THREAD

**Issue by vasiliskampani** [ioniodi/sitegr#397]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών. Θα δημιουργήσω καινούργιο φάκελο στο [all_collections](https://github.com/vasiliskampani/all_collections/tree/P2019014)/_timetables/ και εκει θα προστεθεί το ωρολόγιο πρόγραμμα Α' εξαμήνου. Θεώρησα πώς είναι μια σημαντική προσθήκη παρότι γνωρίζω πως δεν επεμβαίνω καθόλου στο **minimal-ionio** κάτι το όποιο μειώνει την δυσκολία. 
***Σχετικά με το πρόγραμμα ο κ. Νικηφόρος που διδάσκει το μάθημα "Πληροφορική στις ανθρωπιστικές επιστήμες" στο εργαστήριο δεν έχει σύνδεσμο στο προφίλ του διότι δεν έχει προστεθεί ως μέλος προσωπικού στην ιστοσελίδα ακόμα και το μάθημα αγγλικά επίσης***
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργάτες: @xar1sgeovlacp2019059 , @p19pasc
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):  #53
- [Σύνδεσμος](https://github.com/vasiliskampani/all_collections/blob/P2019014/_timetables/sem_a.md/) του αρχείου που πρόσθεσα
- [Ωρολόγιο Πρόγραμμα Α΄ Εξαμήνου 2021-2022.pdf](https://github.com/ioniodi/sitegr/files/8460030/2021-2022.pdf)
- Το [demo](https://vasiliskampani-semester-a.netlify.app/timetables/sem_a/) μου

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέμα
τα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by vasiliskampani** [comment]
![Screenshot from 2022-04-11 01-08-00](https://user-images.githubusercontent.com/72518208/162641964-98937e57-6ba3-4c85-a70d-6cce4254dbfb.png)

![Screenshot from 2022-04-11 01-09-17](https://user-images.githubusercontent.com/72518208/162641978-53d046d5-b752-4a9c-9e44-5e253392953d.png)

**Comment by vasiliskampani** [comment]
**Οι αλλαγές μου και σε screenshot !!**

![Screenshot from 2022-04-11 01-08-00](https://user-images.githubusercontent.com/72518208/162642523-4c6aca65-cb16-4d72-a24f-f422bda6ead2.png)

![Screenshot from 2022-04-11 01-28-53](https://user-images.githubusercontent.com/72518208/162642527-ab9fcc96-4959-4eaf-ad95-3ff1db682de8.png)

**Comment by xar1sgeovlacp2019059** [comment]
Οι αλλαγές φαίνονται οκ από εμένα. Μπορείς να προχωρήσεις

**Comment by Tsimpliarakis** [comment]
Αυτή την στιγμή έχουμε Εαρινό εξάμηνο, πράγμα που σημαίνει πως το Α' εξάμηνο (χειμερινό) δεν πραγματοποιείται, οπότε το πρόγραμμα αυτό που ακριβώς βοηθάει και από που αντλεί τις πληροφορίες του;

Δεν στο λέω για κακό, απλά επειδή μιλήσαμε με τον κ. Χωριανόπουλο η συγκεκριμένη αλλαγή δεν θα γίνει δεκτή διότι απλά γίνεται προσθήκη περιεχομένου (επιφανειακά) αντί να εντρυφήσεις στον κώδικα του site. (Κι εγώ το ίδιο λάθος έκανα)

**Comment by vasiliskampani** [comment]
> Αυτή την στιγμή έχουμε Εαρινό εξάμηνο, πράγμα που σημαίνει πως το Α' εξάμηνο (χειμερινό) δεν πραγματοποιείται, οπότε το πρόγραμμα αυτό που ακριβώς βοηθάει και από που αντλεί τις πληροφορίες του;
> 
> Δεν στο λέω για κακό, απλά επειδή μιλήσαμε με τον κ. Χωριανόπουλο η συγκεκριμένη αλλαγή δεν θα γίνει δεκτή διότι απλά γίνεται προσθήκη περιεχομένου (επιφανειακά) αντί να εντρυφήσεις στον κώδικα του site. (Κι εγώ το ίδιο λάθος έκανα)

Οκεύ θα προσπαθήσω να υλοποιήσω κατι αλλό.

**Comment by Tsimpliarakis** [comment]
> > Αυτή την στιγμή έχουμε Εαρινό εξάμηνο, πράγμα που σημαίνει πως το Α' εξάμηνο (χειμερινό) δεν πραγματοποιείται, οπότε το πρόγραμμα αυτό που ακριβώς βοηθάει και από που αντλεί τις πληροφορίες του;
> > Δεν στο λέω για κακό, απλά επειδή μιλήσαμε με τον κ. Χωριανόπουλο η συγκεκριμένη αλλαγή δεν θα γίνει δεκτή διότι απλά γίνεται προσθήκη περιεχομένου (επιφανειακά) αντί να εντρυφήσεις στον κώδικα του site. (Κι εγώ το ίδιο λάθος έκανα)
> 
> Οκεύ θα προσπαθήσω να υλοποιήσω κατι αλλό.

Βάλε στην αναφορά σου και αυτό το Issue γιατί θα προσμετρηθεί θετικά στον βαθμό μόνο και μόνο για την προσπάθεια. 
Και για να σε βοηθίσω και λίγο, σε αυτό το παραδοτέο πρέπει να "βουτηξουμε" πιο βαθια στην σελιδα και να μην προσθεσουμε κατι ευκολο. Αντιθετως να διορθωσουμε καποιο bug ή να βελτιωσουμε καποια λειτουργια.

**Comment by vasiliskampani** [comment]
> > > Αυτή την στιγμή έχουμε Εαρινό εξάμηνο, πράγμα που σημαίνει πως το Α' εξάμηνο (χειμερινό) δεν πραγματοποιείται, οπότε το πρόγραμμα αυτό που ακριβώς βοηθάει και από που αντλεί τις πληροφορίες του;
> > > Δεν στο λέω για κακό, απλά επειδή μιλήσαμε με τον κ. Χωριανόπουλο η συγκεκριμένη αλλαγή δεν θα γίνει δεκτή διότι απλά γίνεται προσθήκη περιεχομένου (επιφανειακά) αντί να εντρυφήσεις στον κώδικα του site. (Κι εγώ το ίδιο λάθος έκανα)
> > 
> > 
> > Οκεύ θα προσπαθήσω να υλοποιήσω κατι αλλό.
> 
> Βάλε στην αναφορά σου και αυτό το Issue γιατί θα προσμετρηθεί θετικά στον βαθμό μόνο και μόνο για την προσπάθεια. Και για να σε βοηθίσω και λίγο, σε αυτό το παραδοτέο πρέπει να "βουτηξουμε" πιο βαθια στην σελιδα και να μην προσθεσουμε κατι ευκολο. Αντιθετως να διορθωσουμε καποιο bug ή να βελτιωσουμε καποια λειτουργια.

Ναι γνωρίζω τι αλλαγές χρειάζονται για το 8ο, το εγραψά και πάνω στο issue ότι είναι πολυ επιφανειακό το θέμα μου, ευχαριστώ για την αξιολόγηση πάντως!
