### ISSUE TITLE
Προσθήκη λειτουργίας theme switch button

### ISSUE THREAD

**Issue by KuhakuNeko** [ioniodi/sitegr#398]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα υλοποιήσω ένα κουμπί το οποίο θα επιτρέπει στο χρήστη την εναλλαγή μεταξύ χρωματικών θεμάτων του site ώστε να μην περιορίζετε στο ήδη υπάρχον mint theme. Κάνοντας κλικ στο κουμπί θα γίνετε εναλλαγή από το default θέμα σε ένα άλλο. Η ιδέα είναι το δεύτερο θέμα να είναι σκοτεινό αλλά μπορώ αντί να δημιουργήσω ως δεύτερο θέμα ένα custom dark theme να μπεί απλά κάτι άλλο. Με την προσθήκη αυτής της λειτουργίας το site ξεφεύγει από την χρήση του έτοιμου, συν ότι η αλλαγή σχετίζεται με την εισαγωγή μου. Η υλοποίηση γίνετε με html, css/scss, js, και κώδικα liquid.
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργάτες: @Orfeaslambrou @fireleaf22
- Σχετικοί σύνδεσμοι: [Δυναμική αλλαγή του background της κεντρικής σελίδας με βάση την συσκευή προβολής #396](https://github.com/ioniodi/sitegr/issues/396#issue-1199152362)

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [X] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by Tsimpliarakis** [comment]
Πολύ καλύτερο απο το 1ο σου Issue, απλά αφού μπήκες που μπήκες στον κόπο, θα πρότεινα να βάλεις Dark mode.

**Comment by Orfeaslambrou** [comment]
Πολύ καλή προσπάθεια, δουλεύει άψογα.Το δεύτερο θέμα αρκεί έτσι πως έχει γίνει ,δεν χρειάζεται πιστεύω dark mode.Για μένα  παίρνει οκ.

**Comment by diogenisAl** [comment]
@KuhakuNeko σε ποιο αρχείο/αποθετήριο θα γίνουν οι αλλαγές;
Παράλληλα, περιμένουμε την απάντηση από τον @fireleaf22

**Comment by KuhakuNeko** [comment]
@diogenisAl 
Χρειάστηκε να γίνουν αλλαγές και στα δύο αποθετήρια αλλά κυρίως στο minimal mistakes. Τα αρχεία που άλλαξα ήταν αρκετά, όχι μόνο ένα, και χρειάστηκε να δημιουργήσω και μερικά δικά μου. Οπότε, όπως και την άλλη φορά, θα χρειαστούν 2 PR.
