### ISSUE TITLE
Προσθήκη Download button στην σελίδα "Ωρολόγιο Πρόγραμμα"

### ISSUE THREAD

**Issue by p17simt** [ioniodi/sitegr#401]
### Δήλωση Θέματος
- Σκοπός μέσω της προσθήκης αυτής είναι να μπορεί ο φοιτητής με μία κίνηση να αποθηκεύει σε μορφή pdf το ωρολόγιο πρόγραμμα του εξαμήνου που τον ενδιαφέρει.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές:  @p17papa @axilleasmandravelis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): Η [σελίδα](https://epic-hamilton-da9ac8.netlify.app/timetables) που περιέχει το ωρολόγιο πρόγραμμα κάθε εξαμήνου, και η μέθοδος που θα ακολουθήσω για την μετατροπή βασίζεται στο [7ο παραδοτέο](https://github.com/courses-ionio/help/discussions/535). Το κουμπί αυτό θα προστεθεί δίπλα από κάθε link για το αντίστοιχο πρόγραμμα.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
μπράβο, καλή ιδέα, μερικά σχόλια:

1. γιατί θεωρείς σχετικούς τους συνεργάτες που έχεις βάλει; δεν μπόρεσα να βρω κάποια σχετική συνεισφορά με αυτό που θα κάνεις. πως θα σε βοηθήσουν στην αξιολόγηση της;

2. μπορούμε να έχουμε κάποιο αρχικό ντέμο;
