### ISSUE TITLE
Προσθήκη ανακοίνωσης "Ionian Wikithon 2022, 14 & 20 Μαΐου, Εργαστήριο Γαληνός, Τμήμα Πληροφορικής"

### ISSUE THREAD

**Issue by p17gera1** [ioniodi/sitegr#404]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Πρόκειται να προσθέσω την νέα ανακοίνωση, που αναφέρεται στο Ionian Wikithon 2022, 14 & 20 Μαΐου, Εργαστήριο Γαληνός, Τμήμα Πληροφορικής και που δημοσιεύθηκε στην επίσημη ιστοσελίδα του τμήματος μας. 
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργάτες: @vivikara και @alexpoulis
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): Η [ανακοίνωση](https://di.ionio.gr/gr/news/23978/) και το [Demo](https://62816e1688893004df0823ad--reliable-toffee-4628a4.netlify.app/posts/2022/05/09/ionian-wikithon-2022-14-20-maiou-ergastirio-galinos-tmhma-plhroforikis/)
[1ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/266)
[2ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/269)
[3ο προηγούμενο σχετικό θέμα](https://github.com/ioniodi/sitegr/issues/270)

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι **το περιεχόμενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by vivikara** [comment]
Πολύ καλή η προσθήκη σου. Συνέχισε έτσι!

**Comment by diogenisAl** [comment]
Χρειαζόμαστε την απάντηση και του @alexpoulis

**Comment by alexpoulis** [comment]
Το κοίταξα και εγώ και φαίνεται οκ.
