### ISSUE TITLE
Προσθήκη του μαθήματος "Δίκτυα I" στην καθηγήτρια Ελένη Χριστοπούλου.

### ISSUE THREAD

**Issue by PetroulaStylianou** [ioniodi/sitegr#406]
### Δήλωση Θέματος
- Προσθήκη του μαθήματος "Δίκτυα I" στην καθηγήτρια Ελένη Χριστοπούλου.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p19pasa, @AnastasiaMariaStefani
- Αντίστοιχη σελίδα στον επίσημο ιστότοπο: [Επίσημη σελίδα](https://di.ionio.gr/gr/department/staff/335-christopoulou/)
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): https://github.com/ioniodi/sitegr/issues/251

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p19pasa** [comment]
καλό θα ήταν να βάλεις τικ και να τσεκάρεις τις υπευθυμίσεις
