### ISSUE TITLE
Προσθηκη ανακοινωσης "Πρόγραμμα Ορκωμοσιών Μαΐου 2022 (Κέρκυρα, Ληξούρι, Λευκάδα)"

### ISSUE THREAD

**Issue by p18kana** [ioniodi/sitegr#408]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη της ανακοίνωσης ''Πρόγραμμα Ορκωμοσιών Μαΐου 2022 (Κέρκυρα, Ληξούρι, Λευκάδα)'' από https://di.ionio.gr/gr/news/24014/ που αναρτήθηκε την 17-05-2022 στην επίσημη σελίδα του τμήματος
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @p18kout @p18balt 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): #266 #269 

### Υπενθυμίσεις
- [X] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [X] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [X] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [X] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by diogenisAl** [comment]
@p18kana xρειάζεται η έγκριση από @p18kout και @p18balt για να πάρεις το **green light**

**Comment by p18balt** [comment]
Έχεις την έγκριση μου προχώρησε στις αλλαγές.

**Comment by p18kout** [comment]
Έχεις την έγκριση μου !
