### ISSUE TITLE
Πρόσθεση νέας καθηγήτριας Δέσποινα Μουρατίδη στην υποκατηγορία `Ακαδημαϊκοί Υπότροφοι`

### ISSUE THREAD

**Issue by nkanagno** [ioniodi/sitegr#414]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:
   - Αλλαγή:
    Πρόσθεση νέας καθηγήτριας [`Δέσποινα Μουρατίδη`](https://di.ionio.gr/gr/department/staff/841-mouratidi) στην υποκατηγορία `Ακαδημαϊκοί Υπότροφοι`.
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Axileaszervos @AlxiKan
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
 Ιστοσελίδα `netlify` ιονίου πανεπιστημίου με την κατηγορία `προσωπικό`: [nelify/people](https://epic-hamilton-da9ac8.netlify.app/people/)
`Επίσημη` ιστοσελίδα ιονίου πανεπιστημίου με την κατηγορία `Ακαδημαικοί υποτρόφοι`: [di.ionio/academic-scholars](https://di.ionio.gr/gr/department/staff/academic-scholars/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

@epidrome

**Comment by epidrome** [comment]
@nkanagno αρκεί να κάνεις μια αλλαγή μόνο!

**Comment by nkanagno** [comment]
το άλλαξα θα κάνω απλώς την αλλαγή : 
   - Αλλαγή 1η: 
    Στη κατηγορία προσωπικό επιλέγω να αλλάξω επίπεδο (rank) τον καθηγητή [`Εμμανουήλ Μάγκο`](https://di.ionio.gr/gr/department/staff/93-magkos)  από 
    `Αναπληρωτή Καθηγητή` σε `Καθηγητή`.

**Comment by epidrome** [comment]
@nkanagno το θέμα θα κλείσει αυτόματα όταν γίνει δεκτό το αντίστοιχο αίτημα
