### ISSUE TITLE
Αφαίρεση της καθηγήτριας Αγγελικής Τσώχου από την κατηγορία Επίκουροι Καθηγητές και την προσθήκη στην κατηγορία Αναπληρωτές Καθηγητές.

### ISSUE THREAD

**Issue by Axileaszervos** [ioniodi/sitegr#415]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:
  * Αλλαγή:
    Αφαιρώ την καθηγήτρια [Αγγελική Τσώχου](https://di.ionio.gr/gr/department/staff/428-tsohou/) από την κατηγορία `Επίκουροι Καθηγητές` και την προσθέτω στην κατηγορία `Αναπληρωτές Καθηγητές.`

- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργάτες: @AlxiKan @nkanagno
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
  * Η επίσημη [ιστοσελίδα](https://di.ionio.gr/gr/department/staff/professors/) των μελών ΔΕΠ του τμήματος πληροφορικής του ιονίου πανεπιστημίου. 
  * Η επίσημη [ιστοσελίδα](https://di.ionio.gr/gr/department/staff/administrative-staff/) του Διοικητικού Προσωπικού του τμήματος πληροφορικής του ιονίου πανεπιστημίου.
  * Η ανεπίσημη [ιστοσελίδα](https://epic-hamilton-da9ac8.netlify.app/) του τμήματος πληροφορικής του ιονίου πανεπιστημίου.

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
@Axileaszervos αρκεί να κάνεις μόνο μια από τις δύο αλλαγές

**Comment by epidrome** [comment]
@Axileaszervos το θέμα θα κλείσει αυτόματα όταν γίνει δεκτό το αντίστοιχο αίτημα
