### ISSUE TITLE
Προσθήκη του μαθήματος επιλογής "Παιδαγωγικά" στο πρόγραμμα σπουδών προπτυχιακού.

### ISSUE THREAD

**Issue by AlxiKan** [ioniodi/sitegr#416]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
  - Προσθήκη του μαθήματος επιλογής `Παιδαγωγικά` (Β' Εξάμηνο)
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @epidrome @nkanagno @Axileaszervos
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα): 
  - [Επίσημο Πρόγραμμα Σπουδών Προπτυχιακού](https://di.ionio.gr/gr/studies/undergraduate-studies/curriculum/)
  - [Ανεπίσημο Προγραμμα Σπουδών Προπτυχιακού](https://epic-hamilton-da9ac8.netlify.app/courses/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

**Comment by epidrome** [comment]
@AlxiKan αρκεί να κάνεις ένα μάθημα, άφησε κάτι και για τους επόμενους! 😄

**Comment by AlxiKan** [comment]
@epidrome Έγιναν οι αλλαγές.
