### ISSUE TITLE
Προσθήκη της ιστοσελίδας Erasmus+, με πίνακες που χρησιμοποιούν έτοιμα δεδομένα από το all_collection

### ISSUE THREAD

**Issue by nkanagno** [ioniodi/sitegr#426]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών:
  - Προσθήκη της ιστοσελίδας Erasmus+ με πίνακες που χρησιμοποιούν έτοιμα δεδομένα από το all_collection. Πιο συγκεκριμένα, έφτιαξα χρησιμοποιώντας liquid τους 2 πίνακες που έχει ήδη στην επίσημη ιστοσελίδα και στο [all_collection](https://github.com/nkanagno/all_collections/tree/master/_courses) έφτιαξα 2 νέες μεταβλητές σε κάθε μάθημα που υπάρχει στους πινάκες. Η πρώτη μεταβλητή είναι η `Erasmus_courses_with_English_instruction` όπου δείχνει αν στο συγκεκριμένο μάθημα γίνεται διδασκαλία στην αγγλική γλώσσα ή όχι (δηλαδή αν ανοίκει στον πρώτο πίνακα ή στον δεύτερο). Η δεύτερη μεταβλητή είναι η `AA` όπου χρησιμοποιήτε προκειμένου να ταξινομηθούν σωστά τα μαθήματα σε κάθε πίνακα. 
  - link πίνακας 1:  [erasmus-table1.html](https://github.com/nkanagno/minimal-ionio/blob/master/_includes/erasmus-table1.html)
  - link πίνακας 2: [erasmus-table2.html](https://github.com/nkanagno/minimal-ionio/blob/master/_includes/erasmus-table2.html)
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @AlxiKan @Axileaszervos 
- Σχετικά σύνδεσμοι (π.χ., στην επίσημη ιστοσελίδα, προηγούμενα σχετικά θέματα):
  - Η ιστοδελίδα [Erasmus+](https://di.ionio.gr/gr/students/erasmus/) στην επίσημη σελίδα του τμήματος.
## Demo link:
- [<h1>demo link</h1>](https://nkanagno-sitegr.netlify.app/erasmus/)

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο και μοναδικό τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωσης)
- [x] Έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες, όπως σύνδεσμος στην σελίδα που αλλάζω ή/και σύνδεσμο στην αντίστοιχη σελίδα της επίσημης σελίδας με την ενημερωμένη πληροφορία.
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light
- [x] Για την δεύτερη συνεισφορά έχω υλοποιήσει μια νέα λειτουργία και έχω εντοπίσει δύο σχετικούς αξιολογητές όπως φαίνεται στο λινκ που δίνω παραπάνω, διαφορετικά δεν γίνονται δεκτά θέματα που αφορούν απλή συνεισφορά περιεχομένου όπως στην πρώτη συνεισφορά

@epidrome

**Comment by epidrome** [comment]
@nkanagno demo link?

**Comment by nkanagno** [comment]
Οι απαιτούμενες αλλαγές έγιναν!
