### ISSUE TITLE
Εισαγωγή μαθηματος επιλογής  ΣΤ' Εξαμήνου "Ασφάλεια Δικτύων Υπολογιστών και Επικοινωνιών"

### ISSUE THREAD

**Issue by rmfe** [ioniodi/sitegr#43]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Θα γίνει προσθήκη των μαθημάτων επιλογής του ΣΤ' εξαμήνου  "Ασφάλεια Δικτύων Υπολογιστών και Επικοινωνιών".
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@c15pati καλύτερα μια αλλαγή ο καθένας μόνο!!

**Comment by rmfe** [comment]
Θα προσθέσω μόνο το μάθημα "Ασφάλεια Δικτύων Υπολογιστών και Επικοινωνιών".
