### ISSUE TITLE
Αντικατάσταση του μαθήματος μαθηματικός προγραμμματισμος με το μάθημα Πολιτικές και Τεχνολογίες Προστασίας της Ιδιωτικότητας

### ISSUE THREAD

**Issue by p15xiar** [ioniodi/sitegr#46]
### Δήλωση Θέματος
- Αφαίρεση του μαθήματος Μαθηματικός Προγραμματισμός και εισαγωγή του μαθήματος Πολιτικές και Τεχνολογίες προστασίας της ιδιωτικότητας, του διδάσκοντα, της περιγραφής του μαθήματος καθώς και του κωδικού, των εβδομαδιαίων ωρών και των ECTS μονάδων του μαθήματος
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
duplicate #36
