### ISSUE TITLE
Προσθήκη πληροφοριών για Διδακτορικές Σπουδές

### ISSUE THREAD

**Issue by vxsilis** [ioniodi/sitegr#48]
### Δήλωση Θέματος
- Στην κατηγορία "σπουδές" κάτω-κάτω θα προσθέσω πληροφορίες που αφορούν τις διδακτορικές σπουδές
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
οι διδακτορικές σπουδές είναι λίγο περίεργη περίπτωση και θέλει αλλαγές-κατανόηση σε αρκετά αρχεία

πάντως, αν θες να κάνεις μια πιο αναλυτική πρόταση με λινκ της υλοποίησης στο δικό σου φορκ να το δούμε εκεί πριν το φέρουμε εδώ

για την ώρα κάνε κάτι πιο απλό

**Comment by vxsilis** [comment]
Ακολούθησα το επίσημο σαιτ της σχολής που περιέχει απλά 2 pdf και ημερομηνίες σχετικά με το πότε δέχονται αιτήσεις για διδακτορικές. Δεν ήταν κάτι το περίπλοκο. 

Λινκ του σάιτ με την δικιά μου τροποποίηση κάτω-κάτω: https://vxs-sitegr.netlify.app/courses/

**Comment by epidrome** [comment]
ok, ωραίο είναι!
