### ISSUE TITLE
Προσθήκη μαθήματος ελεύθερης επιλογής Β' εξαμήνου "Διαχείριση Επιχειρησιακών Λειτουργιών"

### ISSUE THREAD

**Issue by p16pyla** [ioniodi/sitegr#50]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών: Προσθήκη του μαθήματος ελεύθερης επιλογής Β' εξαμήνου "Διαχείριση Επιχειρησιακών Λειτουργιών" που δεν υπάρχει.
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [X] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [X] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [X] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ποιο είναι το λινκ για αυτό το μάθημα στην επίσημη ιστοσελίδα;

**Comment by p16pyla** [comment]
Είναι μάθημα από το τίμημα τουρισμού, στην επίσημη ιστοσελίδα αναφέρεται στο courses μάλλον ως HY-008 Module from another Department of the Ionian University https://di.ionio.gr/en/studies/undergraduate-studies/courses/643/  το εχω επιλέξει εγώ και κάποιοι συμφοιτητές μου ωστόσο στην επίσημη ιστοσελίδα δεν αναφέρεται κατι περισσότερο

**Comment by epidrome** [comment]
καλύτερα να μείνουμε κοντά στην επίσημη, διάλεξε κάτι άλλο
