### ISSUE TITLE
Προσθήκη Ωρολόγιου Προγράμματος ΣΤ' Εξαμήνου 

### ISSUE THREAD

**Issue by AlexisTsiranidis** [ioniodi/sitegr#53]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα: Προσθήκη Ωρολόγιου Προγράμματος ΣΤ' Εξαμήνου 

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Θα μπορούσες να είσαι λίγο πιο αναλυτικός σχετικά με το τι θα κάνεις;

**Comment by AlexisTsiranidis** [comment]
Στο section Ωρολόγιο πρόγραμμα υπάρχουν  Προπτυχιακό Β' Εξάμηνο, Προπτυχιακό Δ' Εξάμηνο και θα προσθέσω το Προπτυχιακό ΣΤ' Εξάμηνο. εδώ https://epic-hamilton-da9ac8.netlify.app/timetables/
