### ISSUE TITLE
Ενημέρωση ρόλων Πρύτανη και Προέδρου τμήματος

### ISSUE THREAD

**Issue by runtheorun-exe** [ioniodi/sitegr#62]
### Δήλωση Θέματος
- Επκαιροποίηση πληροφοριών θέσεων Πρύτανη και προέδρου τμήματος.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by runtheorun-exe** [comment]
Σε επιπλέον αναζήτηση επι του θέματος διαπιστώθηκε η έλλειψη καταχώρησης για τον νέο πρύτανη του Ι.Π. στο 
/all_collections/_people/, επομένως υπάρχουν 2 επιλογές:

- Είτε να δημιουργήσω νέα καταχώρηση για τον κύριο Φλώρο και κατόπιν να τροποποιήσω το λινκ ["Πρύτανης Ιονίου Πανεπιστημίου](https://epic-hamilton-da9ac8.netlify.app/people/vchris/)
- Είτε να περιοριστώ μόνο στην καταχώρηση πληροφοριών για τον κύριο Φλώρο, αποδεσμεύοντας το task που πρότεινα νωρίτερα.

**Comment by c15pati** [comment]
Το καλύτερο είναι να κάνεις 1 από τα δύο tasks. Δηλαδή ή πρύτανη, ή πρόεδρο για να μιλήσω για το αρχικό post. Και όσον αφορά το δεύτερο σχόλιο νομίζω καταλαβαίνεις.

**Comment by runtheorun-exe** [comment]
Υποθέτω καταλαβαίνω, τροποποιώ την αρχική πρόταση αμέσως.

**Comment by runtheorun-exe** [comment]
Δημιουργία νέου issue και κλείσιμο του παρόντος for beauty reasons.
