### ISSUE TITLE
Προσθήκη διοικητικό υπάλληλο 

### ISSUE THREAD

**Issue by KaterinaLaz** [ioniodi/sitegr#64]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών : Προσθήκη διοικητικό υπάλληλο Κατερίνα Ράπτη
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Το θέμα σου έχει όλες τις εκτιμώμενες δυσκολίες; 
Η δήλωση θέματος είναι εκεί για κάποιο λόγο...

**Comment by KaterinaLaz** [comment]
Ενημέρωσα το πεδίο "Εκτιμώμενη δυσκολία"

**Comment by epidrome** [comment]
@KaterinaLaz 
άρκει να γίνει μια αλλάγή,
μήπως κάποιος έχει δεσμεύσει ήδη κάτι? #30
