### ISSUE TITLE
Προσθήκη μαθήματος επιλογής ΣΤ εξαμήνου "Βιοπληροφορική"

### ISSUE THREAD

**Issue by p18vogd** [ioniodi/sitegr#71]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία:  easy
- Σχετικοί συνεργατές: @
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει περιγραφικό τίτλο και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by akontinis** [comment]
Το εχει προτεινει αλλος και εχει παρει green light #43

**Comment by rmfe** [comment]
Στην περιγραφή έγραψα οτι θα κάνω 2 προσθήκες μαθημάτων αλλά τελικά διέγραψα την προσθήκη του μαθήματος τη Βιοπληροφορικής, μετά από την παρατήρηση του καθηγητή, οπότε μπορείς να το κάνεις.
