### ISSUE TITLE
Απορια για την εργασια

### ISSUE THREAD

**Issue by p16andr** [ioniodi/sitegr#75]
@c15pati @epidrome
Καλησπέρα, εχω μια απορια οσον αφορα την διαδικασια με το CMS. Εχω αλλαξει τα settings μου και στο αποθετηριο με το config.yml αρχείο και τα Netlify settings. Δεν θα πρεπει να με κανετε invite τωρα για να μπορεσω να μπω στην σελίδα admin του sitegr;;;

**Comment by p17kots** [comment]
Απορίες για το μάθημα [εδώ](https://github.com/courses-ionio/sw/issues/915),όχι στα issue των site!

**Comment by epidrome** [comment]
όχι, τα λινκ του νετλιφαη για τα αιτήματα που στέλνετε εδώ δημιουργούνται αυτόματα με το πρόθεμα ντιπλοη πριβιου, π.χ., δες ένα από τα ανοιχτά αιτήματα
