### ISSUE TITLE
Προσθήκη πληροφοριών Φλώρου Ανδρέα

### ISSUE THREAD

**Issue by runtheorun-exe** [ioniodi/sitegr#76]
### Δήλωση Θέματος
- Προσθήκη πληροφοριών του πρύτανη στο /all_collections/_people/  όπως παρέχονται απο [εδώ](https://avarts.ionio.gr/gr/department/people/97-floros/)
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ο πρύτανης δεν ανήκει στο τμήμα, όπως φαίνεται και στο επίσημο σάητ του τμήματος καθώς και στο λινκ που στέλνεις

υπάρχουν πολλά σημεία στο σάητ που αξίζουν διόρθωσης-προσθήκης, παρακαλώ για μεγαλύτερη προσοχή!
