### ISSUE TITLE
Ενημέρωση Ρόλου Προέδρου Τμήματος

### ISSUE THREAD

**Issue by runtheorun-exe** [ioniodi/sitegr#78]
### Δήλωση Θέματος
- Επικαιροποίηση συνδέσμου προέδρου τμήματος (εφόσον [εδώ](https://epic-hamilton-da9ac8.netlify.app/people/vlamos/) βλέπουμε τον προηγούμενο πρόεδρο τμήματος.
- Εκτιμώμενη δυσκολία: very easy
- Σχετικοί συνεργατές: 
- Σχετικά θέματα:

### Υπενθυμίσεις
- [x] Έχω βάλει σύντομο τίτλο (π.χ., το όνομα της σελίδας ή της ανακοίνωης) και έχω ενημερώσει τα παραπάνω πεδία με περισσότερες λεπτομέρειες (π.χ., λινκ σε αρχεία ή φακέλους που αλλάζουν ή εξωτερικές πηγές) για τις προσθήκες που θα κάνω
- [x] Έχω ελέγξει ότι **το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος** σε προηγούμενο issue ανοιχτό ή κλειστό
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by c15pati** [comment]
Θα ήθελα στο pr να προσθέσεις όνομα, επώνυμο και AM

**Comment by runtheorun-exe** [comment]
Ενημέρωση του pr, προσθήκη ονοματεπώνυμου και ΑΜ
